---
title: "Investigation of results"
author: "MK Heun"
date: "June 29, 2015"
output: pdf_document
---

```{r setup, echo=FALSE, include=FALSE}
require(EconModels)
require(EconData)
require(dplyr)
require(ggplot2)
require(xtable)
```

```{r models}
# Set working directory to the location of these data files relative to the location of this file.
setwd("../..")
fileName <- "ESEE2015Models.rds"
fileNameCST <- "EESE2015ModelsCST.rds"
# load from the file on disk
models <- readRDS(fileName)
modelsCST <- readRDS(fileNameCST)
```

```{r investigation}
mod <- models$PT$adjusted$withE$CES$ekl
naturalCoef(mod)
summary(mod)

EconModels:::sse(mod)

attempts <- attr(mod, "model.attempts")

df <- lapply(attempts, function(attempt){
  coeffs <- naturalCoef(attempt)
  sse <- sum(resid(attempt)^2)
  coeffs$sse <- sse
  return(as.data.frame(coeffs))
}) %>% do.call(plyr::rbind.fill, .)
```


```{r all_model_attempts, tidy=FALSE, comment=NA, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
print(xtable(df), type = "latex", include.rownames = T, floating=FALSE)
```

```{r sse, tidy=FALSE, comment=NA, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
print(xtable(select(df, sse), digits = 6), type = "latex", include.rownames = T, floating=FALSE)
```

```{r make model}
formulas <- 
  list( 
    PT = c(unadjusted = build_formula("iGDP", list("iKstkS.L", "iL", "iXpMP", "iYear")),
             adjusted = build_formula("iGDP", list("iKservS.L", "ihLest", "iUMP", "iYear"))),
    UK = c(unadjusted = build_formula("iGDP", list("iKstkO.WwithRD", "iL", "iXp", "iYear")),
             adjusted = build_formula("iGDP", list("iKservO.WwithRD", "ihLest", "iU", "iYear")))
  )
countries <- names(formulas)
flavors <- names(formulas$PT)

# Create the historicalData data frames
historicalData <- list()
commonVars <- c("Year", "Country", "Source")
historicalData$PT <- filter(IST, Country == "PT") 
historicalData$PT <- historicalData$PT[ , unique(c(commonVars,
                                                   all.vars(formulas$PT$unadjusted), 
                                                   all.vars(formulas$PT$adjusted)))]
historicalData$UK <- filter(Leeds, Country == "UK")
historicalData$UK <- historicalData$UK[ , unique(c(commonVars,
                                                   all.vars(formulas$UK$unadjusted), 
                                                   all.vars(formulas$UK$adjusted)))]


modMade <- cesModel(formulas$PT$adjusted, data=historicalData$PT, nest=c(3,1,2))
# Compare with model from models
rbind(naturalCoef(models$PT$adjusted$withE$CES$ekl), naturalCoef(modMade))
```
