% This article has been prepared for publication in Energy Economics in RStudio with knitr.
% According to http://www.elsevier.com/author-schemas/the-elsarticle-latex-document-class, we should be using the
% elsarticle.cls file.
% According to http://cdn.elsevier.com/assets/pdf_file/0006/109392/journal_refstyles.pdf, we should be using
% elsarticle-template-2-harv.tex as the template for the text.
% Furthermore, we should be using model2-names.bst for the bibliographic references.
% The approach here is to load the frontmatter and backmatter from elsarticle-template-2-harv.tex
% both ahead of and behind the text for our paper.
% -- Matthew Kuperus Heun, 2013-01-18

%% This is file `elsarticle-template-2-harv.tex',
%%
%% Copyright 2009 Elsevier Ltd
%%
%% This file is part of the 'Elsarticle  Bundle'.
%% ---------------------------------------------
%%
%% It may be distributed under the conditions of the LaTeX Project Public
%% License, either version 1.2 of this license or (at your option) any
%% later version.  The latest version of this license is in
%%    http://www.latex-project.org/lppl.txt
%% and version 1.2 or later is part of all distributions of LaTeX
%% version 1999/12/01 or later.
%%
%% The list of all files belonging to the 'Elsarticle Bundle' is
%% given in the file `manifest.txt'.
%%
%% Template article for Elsevier's document class `elsarticle'
%% with harvard style bibliographic references
%%
%% $Id: elsarticle-template-2-harv.tex 155 2009-10-08 05:35:05Z rishi $
%% $URL: http://lenova.river-valley.com/svn/elsbst/trunk/elsarticle-template-2-harv.tex $
%%
\documentclass[preprint,authoryear,12pt]{elsarticle}

%% Use the option review to obtain double line spacing
%% \documentclass[authoryear,preprint,review,12pt]{elsarticle}

%% Use the options 1p,twocolumn; 3p; 3p,twocolumn; 5p; or 5p,twocolumn
%% for a journal layout:
%% \documentclass[final,authoryear,1p,times]{elsarticle}
%% \documentclass[final,authoryear,1p,times,twocolumn]{elsarticle}
%% \documentclass[final,authoryear,3p,times]{elsarticle}
%% \documentclass[final,authoryear,3p,times,twocolumn]{elsarticle}
%% \documentclass[final,authoryear,5p,times]{elsarticle}
%% \documentclass[final,authoryear,5p,times,twocolumn]{elsarticle}

%% if you use PostScript figures in your article
%% use the graphics package for simple commands
%% \usepackage{graphics}
%% or use the graphicx package for more complicated commands
%% \usepackage{graphicx}
%% or use the epsfig package if you prefer to use the old commands
%% \usepackage{epsfig}

%% The amssymb package provides various useful mathematical symbols
\usepackage{amssymb}
%% The amsthm package provides extended theorem environments
%% \usepackage{amsthm}

\usepackage{wrapfig}    % Allows wrapping of text around figures
\usepackage{soul}       % Provides strikethrough text
\usepackage{float}      % Allows precise positioning of tables and figures within the text
\usepackage{amsmath}    % Allows \begin{equation*} \end{equation*} for unnumbered equations
\usepackage{multirow}   % To create multirow tables
\usepackage{hyperref}   % To create hyperlinks in the paper
\usepackage{microtype}  % produces hanging punctuation and beautiful type


% From http://economics.utoronto.ca/osborne/latex/BIBTEX.HTM
\newcommand{\citeapos}[1]{\citeauthor{#1}'s (\citeyear{#1})} % Posessive citations. 

%% The lineno packages adds line numbers. Start line numbering with
%% \begin{linenumbers}, end it with \end{linenumbers}. Or switch it on
%% for the whole article with \linenumbers after \end{frontmatter}.
%% \usepackage{lineno}

%% natbib.sty is loaded by default. However, natbib options can be
%% provided with \biboptions{...} command. Following options are
%% valid:

%%   round  -  round parentheses are used (default)
%%   square -  square brackets are used   [option]
%%   curly  -  curly braces are used      {option}
%%   angle  -  angle brackets are used    <option>
%%   semicolon  -  multiple citations separated by semi-colon (default)
%%   colon  - same as semicolon, an earlier confusion
%%   comma  -  separated by comma
%%   authoryear - selects author-year citations (default)
%%   numbers-  selects numerical citations
%%   super  -  numerical citations as superscripts
%%   sort   -  sorts multiple citations according to order in ref. list
%%   sort&compress   -  like sort, but also compresses numerical citations
%%   compress - compresses without sorting
%%   longnamesfirst  -  makes first citation full author list
%%
%% \biboptions{longnamesfirst,comma}

% \biboptions{}

\usepackage[shownotes]{authNote}

\journal{Energy Economics}

\begin{document}

<<setup, echo=FALSE, message=FALSE, eval=TRUE>>=
require(EconModels)
require(EconData)
require(lattice)
require(latticeExtra)
require(ggplot2)
require(car)
require(mosaic)
require(xtable)
require(nlmrt)
# require(micEconCES)
require(plyr)
require(dplyr)
# Provides access to data melting. 
# See http://cran.r-project.org/web/packages/reshape2/reshape2.pdf
require(reshape2) 
# tikz allows use of LaTeX formatting and font in graphs. 
# Allows for a consistent look across the paper.
# See http://r-forge.r-project.org/R/?group_id=440 for instructions 
# on installing tikzDevice.
# require(tikzDevice) 
trellis.par.set(theme=theme.mosaic())
options(width=75)
options(show.signif.stars=TRUE)
require(knitr)

opts_chunk$set(
  # ********************************************************
  eval=TRUE,
  # ********************************************************
  # tikz allows LaTeX code in graphical output. 
  # E.g., "$y$" for a variable name in the legend for a graph.  
  # dev='tikz',
  tidy=FALSE,
  comment=NA,
  # Tells whether to cache output from chunks are saved. Cacheing saves time. 
  # However, references to LaTeX tables DO NOT WORK if cacheing is turned on.
  cache=FALSE,
  warning=FALSE,  #Tells whether to show warnings in the output.
  # Turns off messages for all chunks. 
  # Set TRUE on an individual chunk to see it.
  message=FALSE, 
  # Tells whether to echo code for all chunks. 
  # Set TRUE on an individual chunk to see its code.
  echo=FALSE     
)
@

<<constants, include=FALSE, eval=TRUE>>=
# Graph Heights
maxHeight <- 8.5 # Inches
ninePanelScatterGraphHeight <- maxHeight # Inches
# ninePanelTernaryGraphHeight <- 7 # Inches
# ninePanelSpaghettiGraphHeight <- 7 # Inches

# Graph Widths
maxWidth <- 6.5 # Inches
fourPanelScatterGraphWidth <- maxWidth # Inches
# threePanelScatterGraphWidth <- maxWidth*0.75 # Inches
# onePanelScatterGraphWidth <- maxWidth*0.25
# fourPanelTernaryGraphWidth <- maxWidth
# twoPanelTernaryGraphWidth <- maxWidth*0.45
# fourPanelSpaghettiGraphWidth <- maxWidth
# twoPanelSpaghettiGraphWidth <- maxWidth*0.55
# onePanelSpaghettiGraphWidth <- maxWidth*0.4

presentationGraph1RowHeight <- 2.8 # Inches
presentationGraph2ColWidth <- 2 # Inches
presentationGraph1ColWidth <- 2*presentationGraph2ColWidth
# keyTextSize <- 0.85 # 85% of normal size
# keyColumns <- 1 # Want only 1 column in the key for lattice graphs
# defaultKeyXLoc <- 0.01 # x position of the key. This default is good for 9-panel graphs.
# defaultKeyYLoc <- 0.95 # y position of the key. This default is good for 9-panel graphs.
# Parameter graphs are tricky to ensure same size. I've found that with height set to 5 in for the 
# cd graphs and 2.93 in for the sf graphs, I get a nearly-exact match with graph size. From these settings I 
# can set up 2 equations:
#    5 in = 2*hgraph + haxis
#    2.93 in = hgraph + haxis
# to estimate that h_axis = 0.86 in and hgraph = 2.05 in.
h_param_graph <- 2.07 # Inches for a single panel
h_param_axis <- 0.86 # Inches (also includes whatever margin is applied)
# sfParameterGraphHeight <- h_param_graph + h_param_axis
cdParameterGraphHeight <- 2*h_param_graph + h_param_axis
cesParameterGraphHeight <- 3*h_param_graph + h_param_axis
linexParameterGraphHeight <- h_param_graph + h_param_axis
sfParameterGraphWidth <- maxWidth
cdParameterGraphWidth <- maxWidth
cesParameterGraphWidth <- maxWidth
linexParameterGraphWidth <- maxWidth
# Other graph parameters that apply to all graphs
scaleTextSize <- 0.8  # Multiple of normal size
scaleTickSize <- -0.5 # 50% of normal size and pointing INWARD!

spaghettiGraphLevel <- 0.95 # Spaghetti graph bands will encompass 95% of the data.
@

<<data, include=FALSE>>=
# Load historical data
# In Rstudio, this paper is generated from it's directory, which is "Article".
# We need to define paths relative to the location of the paper. 
# Relative path to historical data from Article
historicalData <- Econ2011 # From the EconData package

# Load coefficients from all models in one large data frame
coeffs_df <- tbl_df(AllCoef)
# Load fitted data from all models in one large data frame
fitted_df <- tbl_df(AllFitted)

# Load the original models.
oModels <- OrigModels
@

% These equations are used in several locations in the paper.
% By defining commands for them, we ensure consistent appearance
% of the equations when they are used.

% Add an argument if you want a label. Example: "\label{eq:CES}"
\newcommand{\ceskl}[1]{\begin{equation} #1
  y = \gamma \: A \: \left[\delta_1 k^{-\rho_1} 
      + (1-\delta_1)l^{-\rho_1} \right]^{-1/\rho_1}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}}

\newcommand{\ceskle}[1]{\begin{equation} #1
  y = \gamma \: A \: \left\{\delta \left[\delta_1 k^{-\rho_1} 
      + (1-\delta_1)l^{-\rho_1} \right]^{\rho/\rho_1} 
      + (1-\delta) e^{-\rho} \right\}^{-1/\rho}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}
}

\newcommand{\ceslek}[1]{\begin{equation} #1
  y = \gamma \: A \: \left\{\delta \left[\delta_1 l^{-\rho_1} 
      + (1-\delta_1) e^{-\rho_1} \right]^{\rho/\rho_1} 
      + (1-\delta) k^{-\rho} \right\}^{-1/\rho}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}
}

\newcommand{\cesekl}[1]{\begin{equation} #1
  y = \gamma \: A \: \left\{\delta \left[\delta_1 e^{-\rho_1} 
      + (1-\delta_1) k^{-\rho_1} \right]^{\rho/\rho_1} 
      + (1-\delta) l^{-\rho} \right\}^{-1/\rho}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}
}


\begin{frontmatter}

%% Title, authors and addresses

%% use the tnoteref command within \title for footnotes;
%% use the tnotetext command for the associated footnote;
%% use the fnref command within \author or \address for footnotes;
%% use the fntext command for the associated footnote;
%% use the corref command within \author for corresponding author footnotes;
%% use the cortext command for the associated footnote;
%% use the ead command for the email address,
%% and the form \ead[url] for the home page:
%%
%% \title{Title\tnoteref{label1}}
%% \tnotetext[label1]{}
%% \author{Name\corref{cor1}\fnref{label2}}
%% \ead{email address}
%% \ead[url]{home page}
%% \fntext[label2]{}
%% \cortext[cor1]{}
%% \address{Address\fnref{label3}}
%% \fntext[label3]{}

\title{An Empirical Analysis of the Role of Energy in Economic Growth}

%% use optional labels to link authors explicitly to addresses:
%% \author[label1,label2]{<author name>}
%% \address[label1]{<address>}
%% \address[label2]{<address>}

\author[CalvinEngr]{Matthew Kuperus Heun\corref{cor1}}
\ead{mkh2@calvin.edu}
\author[Stellenbosch]{Martin de Wit}
\author[CalvinMath]{Randall J. Pruim}
\author[CalvinEngr]{Caleb Reese}
\author[CalvinEngr]{Lucas Timmer}

\cortext[cor1]{Corresponding author}
\address[CalvinEngr]{Engineering Department, Calvin College, Grand Rapids, MI 49546, USA}
\address[Stellenbosch]{Faculty of Economics and Management Sciences, School of Public Leadership, Stellenbosch University, P.O. Box 610, Bellville 7535, South Africa}
\address[CalvinMath]{Mathematics \& Statistics Department, Calvin College, Grand Rapids, MI 49546, USA}

\begin{abstract}
%% Text of abstract
**** Add abstract ****
\end{abstract}

\begin{keyword}
%% keywords here, in the form: keyword \sep keyword
economic growth \sep energy \sep Cobb-Douglas \sep CES \sep LINEX
%% MSC codes here, in the form: \MSC code \sep code
%% or \MSC[2008] code \sep code (2000 is the default)
\end{keyword}

\end{frontmatter}

% \linenumbers
%% main text

\section*{Notes from Martin}

**** Additional references requested by Martin. Incorporate into paper? ****

\citet{Lindenberger:2011dx}

\citet{Stresing:2008cq}

**** Notes from Martin ****

To be included somewhere.

Introduction

[1. Listen to what others say
Identify key issues and important voices]

The availability of adequate energy at affordable costs 
has become an important strategic issue in recent years.
Despite a slowdown in economic growth worldwide, 
longer-term trends in energy use remain strongly upwards, 
as the dynamics of energy markets are increasingly determined by emerging economies, 
notably China, India, and the Middle East \citep{IEA:2012ty}. 
A large body of literature points to the fact that 
economic growth and energy consumption are closely correlated 
and for a diverse set of countries such as 
the United States \citep{Stern:2000wq, Cleveland:1984p5055}, 
India \citep{Paul:2004jl}, 
China \citep{Wang:2011fe}, 
South Africa \citep{Menyah:2010hl, Odhiambo:2009hj} and 
sixteen Asian countries \citep{Lee:2008dm}
to name a few, 
although the causal relationship from energy consumption 
to economic growth remains controversial \citep{Chen:2012fs, Ozturk:2010kb}. 
\citet[p. 347]{Ozturk:2010kb} in a survey of the literature on the topic, 
concluded that there is 
``\dots no consensus neither on the existence nor on the direction of 
causality between these variables in the literature,'' 
but does point out that ``\dots causality is running from 
electricity consumption to economic growth 
in the most of these studies [surveyed].''

Those that have accepted that energy use is closely correlated with
economic performance in one form or another
have expressed further concerns on the negative effects of 
rising energy prices and fossil fuel depletion 
on current and future economic growth.
\citet{Benes:2012tm}, incorporating views on both
geological physical constraints and 
technological solutions to oil production, 
suggest a near doubling of the real price of over the next decade.  
\citet{Kumhof:2012ua} point out that 
significant impacts on GDP growth could occur
for larger oil supply shocks, 
assuming production functions where oil plays a prominent role 
and reduced possibilities for substitution away from oil.  
\citet{Nel:2010fv} argue for the 
``\dots vital importance of energy security \dots'' 
on the basis of a model based on an explicit 
energy-based formulation of economic growth.  
\citet{Hamilton:2013vc} argues that 
``[c]oping with a final peak in world oil production \dots 
[will] have much in common with previous historical episodes that resulted from 
temporary geopolitical conflict, 
being associated with significant declines in employment and output. 
If the future decades look like the last 5 years, we are in for a rough time.'' 

The current trends in energy production and consumption and 
the possible dire impacts on the world economy 
as argued by above-mentioned scholars 
have further raised the question of
whether and how to include appropriate energy indicators 
in economic growth modeling.  
\citet[p. 26]{Stern:2011bq} provides an overview of how energy is included 
in mainstream economic, resource economic, and ecological economic models of growth.  
\citeauthor{Stern:2011bq} points out that energy is usually \emph{not included} 
as a factor of production in mainstream economic growth models, 
that energy is seen as the \emph{central driver of growth} 
in ecological economic (including biophysical economic) models, 
and that energy \emph{is included} in resource economic models, 
but \emph{remains isolated} within this sub-discipline.  
To break through this theoretical impasse, 
Stern proposes a synthesized CES production function 
where the constraints or abundance of energy 
determines whether to include energy explicitly 
as a factor of production.  
On the basis of this model, 
\citet[p. 45]{Stern:2011bq} points out that 
energy availability plays
``\dots a key role in enabling growth,''
despite the evidence of decreasing energy consumed per unit of output.  
He concludes, based on theory and time-series results, 
that including energy in the production function is warranted, 
and that further clarification is needed 
on the role of energy in economic growth.  

The inclusion of energy as a factor of production 
in CES and Cobb-Douglas production functions 
is generally accepted by most 
resource and energy economists and economic growth modelers 
\citep{Smulders:2003wc, vanderZwaan:2002wn, Kemfert:1998vd}.
Researchers interested in explaining long-term economic growth 
and possible constraints on growth 
have started to include energy as an explicit factor of production
\citep{Froling:2009vo, Tahvonen:2001tz}.  
An alternative approach, attempting to be 
``\dots more consistent with physical laws \dots'' \citep{Ayres:2001tx}
and classified by \citet{Stern:2011bq} as an ecological economic model of growth, 
is the LINEX production function, 
combining capital (non-ICT and ICT), 
labour, and useful work. In the LINEX model, 
technological change affects only 
the amount of useful work done per joule of exergy \citep{Ayres:2005kn}.

Unsatisfactorily, the choice of a production function 
and the parameters used to populate these functions 
affects results significantly.
This situation leaves far too much latitude 
for misuse of model specifications 
and selection of parameters 
to support certain theories (rather than empirically testing the theories
and parameters \emph{before} they are employed).  
For example, \citet{Lecca:2011kr} pointed out that 
the modellers' choice for the structure of a production function 
reflects his or her assumptions about
the elasticities among inputs, and 
``\dots the point at which energy enters the [nested CES] production function 
has a significant impact on CGE [computable general equilibrium] model results.''
\citet{Duffy:2000ty} rejected the Cobb-Douglas production function altogether, 
finding that capital and labour are more substitutable 
in richer countries and less substitutable in poorer countries 
than Cobb-Douglas implies.  
However, \citet{Miller:2008vd} points to the 
``\dots reasonably accurate long-term economic forecasts,'' 
achieved with the use of Cobb-Douglas production functions in economic models.  
\citet{Shen:2013vp} provide a recent example 
wherein empirical analysis on the estimated substitution elasticities 
is performed before choosing any particular 
nested CES production function structure. 
As a result, \citeauthor{Shen:2013vp} propose an atypical structure 
for the Chinese economy. **** More detail here about nesting? ****  
Both the choice of production function structure 
and the value of the model parameters 
drive model results, and empirical and statistical testing 
of such approaches is prudent, but rarely conducted.

[2. Find our own voice
What is our own argument?]

These are not idle debates. 
Economic growth models are often used to inform economic policy,
and the paths of economies worldwide are determined by
such policy choices. 
Therefore, we agree with those who have serious concerns 
about the reliability of the results from economic growth models \citep{Lecca:2011kr}. 
\citet{Lecca:2011kr} and **** and what? **** would like to add
**** ``would like to add'' or ``add''?**** that the inclusion of energy 
would only further complicate issues.  **** Prev. sentence is unclear. ****
We do except **** do you mean ``accept'' or ``expect'' here? ****, however, 
that macroeconomic policymaking is needed 
and is increasingly informed by integrated energy-economic models, 
in a world where energy constraints are possible 
\citep{Beckman:2011gb, Benes:2012tm, Nel:2010fv}.  
We support the call from \citet{Shen:2013vp} that both
the structure of the production function 
and the parameters used to populate this function
need empirical testing. 
Furthermore, the quantification of energy ($q$, $x$, or $u$) 
needs to be empirically assessed.  **** Need more on topic of energy quantification above. ****
Building on the argument of \citet{Stern:2011bq} 
that energy may or may not be required in production functions 
depending on its abundance or scarcity, 
we will further argue in this paper that different types of countries 
may need different factors of production to explain their respective growth paths.  
This further leaves open the possibility for 
different explanations of growth in various countries
at different stages of their development, 
a central point of long-wave economic growth modeling 
\citep{Froling:2009vo, Jones:2001wn, Galor:2000up}. 
**** Should we discuss the longwave literature above? ****

To gain insights from different countries across different stages of development, 
we present a comparative analysis among 
the World Bank’s main categories of countries, 
namely Developed Countries (DCs), 
Newly Industrialized Countries (NICs), 
OPEC countries, and 
Least Developed Countries (LDCs). 
**** Move the previous sentence to the ``approach'' section below? ****

Approach

Build on articles using R to test econ growth PF, 
question what is reported when doing these tests (shen/whalley and others who have used micEconCES). 


Discussion and Insights

Does analysis differ from others in the conversation?
Yes, differs as follows:
\begin{itemize}
\item{if one do these test, report on all $\delta$, $\sigma$, $\gamma$, and $\lambda$ 
values as well as sse. 
Good fits not evidence of best values, must report uncertainties as well.}
\item{What motivates nesting of CES? Not well behaved $\rho$ results, driving $\sigma$s.
Different type of CES with parsimonious factors, sigmas can be generated but not that easy (idea Randy).
If you run all 3 nesting options, you can identify elasticities of all three factors in relation to each 
other. Furthermore, you can determine which two factors are driving overall behavior in the aggregate function.}
\item{necessary of different factors in PF to explain growth for countries in diff. development status}
\end{itemize}

What do we add to the conversation?

\begin{itemize}

\item{We are able to gain rich insights 
on what really drives growth from detailed analysis (including uncertainties) 
by testing all functional forms across many different 
economy types.}

\item{We were unable to gain new insights from the various energy quantifications that we tried.}

\item{We find, surprisingly, that energy is not necessary 
to be included alongside $k$ and $l$ in all PF. Models with energy and models without energy
all perform well on an R$^2$ basis.}

\item{We also find that 

(1) covariance of energy($e$) with both $k$ and $l$ is very high, with few exceptions (UK?).

(2) with few exceptions, $\sigma_{(kl)e}$, $\sigma_{ke}$, and $\sigma_{le}$ 
are all very low (indicating complementarity) (verify!!!!), and 

(3) energy-only models (SF$e$ and LINEX) achieve very good fits, just like CD$e$ and CES$e$.
(should we make this point or not?)}

\item{What does that mean? 
It is a fallacy to think that saying energy is unnecessary 
to include in an equation means energy is unimportant for economic growth. How to support this argument?

If you find that energy is unnecessary to include alongside capital and labor 
to explain growth in one economy at the macro, aggregated level, 
you should not assume that energy is unimportant as a driver for economic growth for all economies.
For developed economies, energy is captial intensive: you need to have large capital to make use 
of energy. In developing economies, you don't need capital to make use of energy. 
Rather, you need labor.

We need to verify the above by comparison with our results.}

\item{Also signals that different types of countries likely 
to react differently to energy constraints. 
Interpret $\sigma$ here, substitution possibilities.}

\end{itemize}

More work?




Big picture
[insert test test]

Why do we do this? Want to link energy and economics on national level 
and in a modeled approach,informing energy policy during energy transitions.
Usually macro energy economic models rely on PF with energy included. 
Key papers using CES in energy economics incl high impact such as 
Stern, Gerlagh, Tol etc. 
Cite in introduction met energy economists using PF approaches, specially CES.
But, which form to choose and using which parameters? 
Literature is inconclusive, very little actual empirical testing of such functions. 
Mostly CES in CGE models used by Wbank and others. 
CD adviced to be used by CBO. 
How do we select a functional form and what are the parameters to be used? On what basis do we select?

We aim. to search for empirically robust solution, one that stands up to statistical testing.

What we find is counterintuitive for many cases: dropping energy from the PF has little impact, 
but some notable exceptions. 
On other hand, only including energy in a PF of LINEX form also yields good results and stats tests. 
Is not a simple case for dropping energy, but acknowledging its key role. 
Do we support the call for better bottom-up understanding? 
What do we say on the limitations of macroeconomic modelling approaches altogether? 
(Note such limitations are well known in ME literature, for example capital controversy Robinson).
We speculate on implications for choosing PF in energy economic models that inform growth policy.

Points on paper so far
1. Does the relative small differences in fit between different production functions warrant 
such a large debate on validity of one vs other? Clearly not. 
CD been used by economists for ease of use and extreme flexibility (Miller).  
PF generally used on instrumentalist grounds if give reasonable good description of data. 
NK econ theory provide poor causal explanation of observed data, 
but yet CD shows very good fit (miller, p17). 
CES is  more general, but is a liability in forecasting because difficult 
to get estimate of EoS that is consistent across studies (Miller, p26). 
Aggregation is problem of both CD and CES functional forms, 
so being careful when making strong inferences that cannot be justified.

2. We think we can contribute by emphasising the need 
for proper stats testing or inconsistent reporting on use of preferred functions. 
Problems with empirical testing presented by Shen, Serrenho.
What are our issues with multivariate OLS (Serrenho)?

3. Are we joining the forced choice between production functions or 
acknowledge the similar problems with aggregate prod functions in general? 
Do we see this as sufficient evidence to doubt the top-down approach to econ growth altogether?

4. R2 is a very crude measure and only very minor improvements 
are achieved when others factors such as energy is added in a CD. 
We concur. Puzzling is conclusion that such minor improvements 
does prove the need to include energy in PF (Serrenho).

5. We do think it is a choice between CD and CES (Miller) as 
both have serious deficiencies after stats tests.

6. One central issue within PF is elasticity of subs (EoS). 
That is the \%ch in factor proportions ( k,l, etc) 
because of one unit ch in MRTS. 
MRTS is rate at which one factor can be substituted for another holding output constant. 
EoS is low in Leontief cases, L shaped isoquants.

7. Miller makes the point that even if parameters in model are stats artifacts, 
they are still useful for forecasting. Do we agree?

8. Is Ockham's razor relevant to what we are doing?

9. Assumptions of CD are strongly rejected by empirical work, Miller still makes case for using CD.

11. What about energy augmented 

10. TZ case
CDno e: almost 80\% l
CD with e: 25\% energy, rest c,importance of l drops to 0
CES no e: 20\% c ($\sigma$), 80\% l, but large range
CES with e: fig 35 e may be NB
LINEX: one of lowest ct parameters (low relative importance of labour eff compared to cap eff)
Does this mean that relative small increases in cap eff can really lift the economy?

11. ZA case
CD no e: roughly half c, l
CD with e: roughly half, c, e, importance of l drops to 0
CES no e: 10\% c, 25\% l ??
CES with e: fig 35 e may be NB
LINEX: one of highest ct parameters (high relative importance of labour eff compared to cap eff)
Does this mean that relative small increases in labour eff can really lift the economy?

12. Capital starved Zambia. Very high importance. Understand CES param better.

Discussion: What is Next?

a. A comparative analysis between diff PF reveal interesting 
enough information to warrant a more diffused approach to countries. 
Thus, we have a case for doing this for  all countries in the world 
(or at least those representative of countries in different groups 80/20)

b. If c is relatively more important than labour or energy 
for growth and if capital stock is low, a situation one would expect in LDCs, 
a relative small addition of capital stock can give relatively large returns in terms of growth.

c. Now it becomes interesting, in a 'stages of growth' approach, 
using LT econ data it may be the case that the importance 
of factors are different across growth stages. 
It would need a composite type of analysis - both stock and importance.

d. Is it possible to have evidence of diff stocks and diff importances across phases of growth? 
Maybe test this for a data rich nation that has worked through these stages, 
we try to identify them and do partial analysis on time periods coinciding with these stages.

Should we eliminate $u$ data? Only 3 countries. Only 20 years. Doesn't add much insight. 
Too bad, but perhaps necessary to simplify paper.

Discussions:

Counterfactuals: energy, cap, labour what ifs for future.

interpretation of type of economies, what does the data presentation say 
on relative change in each input and change in GDP?

Forcing const elast of subs in CES thru nested structures violates 
observation that more than two factor will not be const. elasticities Uzawa 1962.

R programming dealt with nested CES see paper discussion on Kemfert.

Next steps:

Stages of growth crowd implicitly assumes countries at similar stage of growth will
have similar values for $\alpha$, $\beta$, $\gamma$. However, our results show
that not to be true. Needs further exploration to cover more (all?) countries.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction} 
\label{sec:Introduction}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



**** Notes on the introduction from Martin ****

1. Set scene through energy economic modelling papers. 
Point out that PF approaches are alive and well (Stern, Tol, Gerlagh, World Bank, IMF), 
short lit review as part of a longer introduction.  
Mention competing PF approaches and parameter choice. 
On what basis selection and how estimate parameters? 

2. Point out the need for adequate statistical testing and economic interpretation, 
citing some earlier critical papers on PF limitations. Take issue with 

3. Spell out the contribution we will be making in this paper, 
we are taking the approach that all models are wrong but some are useful. 
We are after generating insights even after deeper assumptions of econ growth theory are very limiting.

4. Introduce coordinates of analysis.





**** Orignial introduction that MKH wrote ****

Neoclassical economic growth theory attributes output ($Y$) to factors of production:
capital stock ($K$) and labor ($L$). The Cobb-Douglas production function 
is the 
canonical representation of indexed economic output ($y$) as a function of indexed 
labor ($l$), indexed capital stock ($k$), and an additional exogenous, time-dependent 
term.%
\footnote{The time-dependent term in production functions is often linked
to ``technological progress,'' but that is a very narrow reading of Solow's original intent:
\begin{quote}
  It will be seen that I am using the phrase ``technical change''
  as a short-hand expression for any kind of shift 
  in the production function. 
  Thus slowdowns, speed-ups, improvements in the education of the labor force, 
  and all sorts of things will appear as ``technical change.''~\citep{solow1957technical}
\end{quote}
}
This production function can be expressed as
\begin{equation} \label{eq:CD}
  y = \theta \mathrm{e}^{\lambda(t-t_0)} k^\alpha l^\beta \;,
\end{equation}
where 
\begin{itemize}
	\item $y \equiv Y/Y_{0}$,  % why was 0 typeset as mathrm??
	\item $k \equiv K/K_{0}$, 
	\item $l \equiv L/L_{0}$, 
	\item $Y$ represented by GDP, 
	\item $K$ expressed in currency units, 
	\item $L$ expressed in workers or work-hours/year, 
	\item $t$ (time) is measured in years, 
	\item e is the base of the natural logarithm, and 
	\item 0 subscripts indicate values at an initial year.%
\footnote{Dimensionless, indexed quantities are represented by 
lower-case symbols 
($y$, $k$, $l$, $e$, $q$, $x$, and $u$), and dimensional 
quantities are represented by upper-case symbols 
($Y$, $K$, $L$, $E$, $Q$, $X$, and $U$). 
Model parameters are represented by Greek letters
($\alpha$, $\beta$, $\lambda$, $\theta$).} 
\end{itemize}
%Mathematically, $A$ is nothing more than a fitting parameter 
%that aligns the predictions of Equation~\ref{eq:CD} 
%with historical data. 
%Thus, we refer to $A$ as the ``residual'' in this paper.} 
%term ($A$):

% $A$ is the residual term, 
% with $\lambda$ 
% indicating the change of the residual over time (in units of 
% year$^{-1}$).
Neoclassical economic growth theory as expressed in the Cobb-Douglas production 
function makes no attempt to describe the mechanisms that affect
economic growth, nor does it attempt to describe how such things as
slowdowns, speedups, and improvements of the education of the labor force
($\lambda$) might vary from one economy to the next. 
The parameters $\alpha$ and $\beta$ indicate the relative roles 
of capital and labor in the economy.
Typically, the constraint $\alpha + \beta = 1$ is assumed, 
indicating constant returns to scale.


As shown in Equation~\ref{eq:CD} above, neoclassical economic theory does not 
include an explicit term for the role of energy in economic growth. However, 
\citet{Bashmakov:2007ek}, \citet{Hamilton:2009ui}, \citet{Murphy:2011jh}, 
\citet{Benes:2012tm}, \citet{Kumhof:2012ua}, and others indicate that the 
importance of energy for economic growth may far outweigh its cost share in the 
economy. That neoclassical economic growth theory ignores energy is, therefore, 
cause for concern, and inquiry into the proper approach for including energy 
as a factor of production in economic growth modeling is both relevant and important.

Some energy economists augment economic growth models by including energy as an 
additional (or the only) factor of production. However, there is little agreement 
on how this should be done. Neither the mathematical form of the energy-augmented 
production function nor the quantification of energy are consistent in the 
literature. There has been little empirical work assessing the predictive ability 
of various energy-augmented production functions for different types of economies. 
And, very few studies of the importance of energy in economic growth include 
rigorous statistical assessments of energy-related fitting parameters. This paper 
contributes to the literature by applying statistically rigorous 
methods along two coordinates of analysis: form of the energy augmented 
production function and type of economy.

The remainder of this paper is organized as follows. Section~\ref{sec:Coordinates} 
discusses the coordinates of analysis described above. 
Section~\ref{sec:Sources_of_Data} details sources of data and calculations to 
generate time series for economic output and factors of production. 
The procedures for and results from parameter estimation for the various production functions 
are discussed in Section~\ref{sec:Parameter_Estimation}. 
Section~\ref{sec:Discussion_of_Results} discusses implications of the parameter estimation 
results, and Section~\ref{sec:Conclusion} concludes. 
An appendix provides details of all statistical results.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Coordinates of Analysis} 
\label{sec:Coordinates}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

This section describes the two coordinates of analysis and briefly reviews 
literature related to each.


%++++++++++++++++++++++++++++++
\subsection{Mathematical Forms of the Energy-augmented Production Function} 
\label{sec:Prod_Func_Forms}
%++++++++++++++++++++++++++++++

In this paper, we assess three prominent energy-augmented production functions 
that appear in the literature: 
Cobb-Douglas (CD), 
Constant Elasticity of Substitution (CES), and 
LINear EXponential (LINEX). 
The following subsections describe each.


%------------------------------
\subsubsection{Cobb-Douglas (CD) Production Function} 
\label{sec:CDe}
%------------------------------

The capital-labor Cobb-Douglas production function shown in Equation~\ref{eq:CD}
can be augmented to include an energy term:

\begin{equation} \label{eq:CDe}
  y = \theta \mathrm{e}^{\lambda(t-t_0)}  k^\alpha l^\beta e^\gamma \;,
\end{equation}
where $e \equiv E/E_0$, and $E$ is in units of energy per time, typically TJ/year. 
The energy-augmented Cobb-Douglas production function 
is often assumed to have constant returns to scale for the three factors 
of production: $\alpha + \beta + \gamma = 1$.

\citet{Ayres:2008cl} uses Equation~\ref{eq:CDe} with exergy ($x$) and 
useful work ($u$) quantifications for $e$ to describe historic Japanese 
and American economies from 1900-2000. \citet{Froling:2009vo} uses an 
energy-augmented Cobb-Douglas production function with thermal energy 
quantification ($q$) to describe output for the global economy from 1800--1970. 
Fr\"{o}ling's model endogenizes labor with respect to fertility 
and mortality rates and separates thermal energy into two types: biomass 
energy and coal energy. 
\citet{Serrenho:2010vq} use the log transform of 
the energy-augmented Cobb-Douglas function with thermal energy 
quantification ($q$) to describe output for the EU-15 countries. 
Serrenho divides thermal energy into renewables, non-renewables, 
wastes, and imports. 
The main argument of these papers is that 
energy is an important driver of growth and needs to be included
as an essential factor of production.

**** Martin: add more here about the conclusions of each paper regarding 
the role of energy in economic growth? Add additional literature? 
Or, adjust as you see fit. Especially, are there any confidence intervals 
or statistical evaluation in each of these studies? ****


%------------------------------
\subsubsection{Constant Elasticity of Substitution Production Function (CES)} 
\label{sec:CES}
%------------------------------

Other energy economists use an energy-augmented 
Constant Elasticity of Substitution (CES) production function to 
describe economic growth. The \texttt{R} \citep{R} package 
\texttt{micEconCES} \citep{Henningsen:2011td} estimates CES production 
functions of the following forms (among others):

\ceskl{\label{eq:CES}}

\ceskle{\label{eq:CESkle}}

\noindent Equation~\ref{eq:CES} is a CES production function with 
capital stock ($k$) and labor ($l$) factors of production. 
Equation~\ref{eq:CESkle} augments Equation~\ref{eq:CES} with energy 
using a ($kl$)($e$) nesting structure, as is typical in the literature. 
Equation~\ref{eq:CES} is a degenerate form of Equation~\ref{eq:CESkle} 
where $\delta \rightarrow 1$. 

$\gamma$ is a fitting parameter that represents productivity. 
The fitting parameters $\rho_1$ and $\rho$ indicate elasticities 
of substitution ($\sigma_1$ and $\sigma$).
The elasticity of substitution 
between capital ($k$) and labor ($l$) is given by 
$\sigma_1 = \frac{1}{1+\rho_1}$, and
the elasticity of substitution between ($kl$) and ($e$) is given by 
$\sigma = \frac{1}{1+\rho}$. 
As $\rho_1 \rightarrow 0$, $\sigma_1 \rightarrow 1$,
and the embedded CES production function for $k$ and $l$ degenerates 
to the Cobb-Douglas production function.
Similarly, as $\rho \rightarrow 0$, $\sigma \rightarrow 1$,
and the CES production function for $(kl)$ and $(e)$ degenerates 
to the Cobb-Douglas production function.
As $\sigma \rightarrow \infty$ ($\rho \rightarrow -1$), 
($kl$) and ($e$) are perfect substitutes. 
As $\sigma \rightarrow 0$ ($\rho \rightarrow \infty$), 
($kl$) and ($e$) are perfect complements: 
no substitution is possible. Similarly, 
as $\sigma_1 \rightarrow 0$ ($\rho_1 \rightarrow \infty$),
$k$ and $l$ are perfect complements.
$\delta_1$ describes the relative importance of capital ($k$)
and labor ($l$), and
$\delta$ describes the importance of ($kl$) relative to ($e$).

Constraints on the fitting parameters include 
$\delta_1 \in [0,1]$,
$\delta \in [0,1]$,
$\rho_1 \in [-1,0) \cup (0,\infty)$, and
$\rho \in [-1,0) \cup (0,\infty)$. 

Two other nestings of the factors of production ($k$, $l$, and $e$)
are possible with the CES model.

\ceslek{\label{eq:CESlek}}

\cesekl{\label{eq:CESekl}}

\noindent Note that the $\rho$ ($\sigma$) and $\delta$ parameters have different
meanings that depend upon the nesting of the factors of production.
**** Do we want to define different variables that indicate meaning, 
such as $\sigma_{kl}, \sigma_{(kl)e}, \delta_{(ek)l}$, and the like? If so, we'll 
need to translate from $\rho$ and $\sigma$ in \texttt{cesEst} to the correct
variable names in the paper. ****


**** Describe here how 
we implemented the constraints. ****

\citet{VanderWerf:2008tc} evalutes various nested CES production 
functions for 12 OECD countries with respect to climate change policy. 
\citeauthor{VanderWerf:2008tc} concludes that ($kl$)($e$) nesting structure 
best fits historical data. \citet{Lecca:2011kr} also evaluate a variety of 
CES production functions using a KLEM structure to determine how the various 
options for nesting the energy factor of production affect predictive ability. 
\citet{Stern:2012ey} also use a CES production function of the form ($kl$)($e$). 
\citeauthor{Stern:2012ey} apply their CES function to the Swedish economy 
from 1800-2000 and demonstrate the importance of the transition from wood to 
fossil fuels for economic growth. \citet{Shen:2013vp} included energy 
in nested aggregated CES production functions 
for China and found that the best nesting structure is ($le$)($k$).


**** Martin: add more here about the conclusions of each paper regarding 
the role of energy in economic growth? Add additional literature? 
Or, adjust as you see fit. Especially, are there any confidence 
intervals or statistical evaluation in each of these studies? ****

%------------------------------
\subsubsection{LINEX Production Function} 
\label{sec:LINEX}
%------------------------------

A third production function, the LINear EXponential (LINEX) function
\begin{equation} \label{eq:LINEX}
  y = \theta \; \mathrm{e}^{a_0\left[2 \left(1 - \frac{1}{\rho_k} \right) 
    + c_t \left(\vphantom{\frac{1}{\rho_k}}\rho_l - 1 \right)\right]} \; e \;,
\end{equation}
was derived from thermodynamic considerations
\citep{Kummel:1980wx,Kummel:1982vy,Kummel:1985vz,Kummel:1989tf,Kummel:2002tx,Kummel:2010vz}. 
In contrast to both the Cobb-Douglas model (Equations~\ref{eq:CD} and 
\ref{eq:CDe}) and the CES model (Equations~\ref{eq:CES}--\ref{eq:CESekl}), 
the LINEX model (Equation~\ref{eq:LINEX}) does not include a generic, 
time-dependent augmentation term ($A$).
The LINEX models assumes energy ($e$) is the only factor of production.

The LINEX model does, however, include terms that represent
efficiencies among capital, labor, and energy, in the form of 
the ratios $\rho_k$ and $\rho_l$ which are defined by\footnote{The notation
for the LINEX model breaks from the conventions used in the Cobb-Douglas and CES
models:  $a_0$ and $c_t$ are parameters and $\rho_k$ and $\rho_l$ are not.}
%
\begin{equation} \label{eq:rho_k}
  \rho_k \equiv \frac{k}{(1/2)(l+e)}
\end{equation}
and
\begin{equation} \label{eq:rho_l}
  \rho_l \equiv \frac{l}{e}
\end{equation}
and represent 
(\ref{eq:rho_k}) capital stock increase relative to the average of labor and energy and 
(\ref{eq:rho_l}) labor increase relative to energy.
The effect of energy ($e$) on production is enhanced if either

\begin{itemize}
\item{capital stock ($k$) has increased more than the average 
      of labor ($l$) and energy ($e$), i.e. if $\rho_k >$ 1, or}
\item{labor ($l$) has increased more than energy ($e$), i.e. if $\rho_l >$ 1.}
\end{itemize}
%
An economy that increases 
capital stock ($k$) and labor ($l$) at the same rate as energy will have
capital and labor efficiency ratios ($\rho_k$ and $\rho_l$, respectively) of unity.
In that case, economic output ($y$) increases at the same rate as energy consumption ($e$).
According to the LINEX model, an economy that increases 
capital stock ($k$) without a commensurate increase in labor ($l$) 
and energy ($e$) will experience an increase in output ($y$) in excess 
of its increase of energy consumption ($e$), because
\(
\mathrm{e}^{a_0\left[2 \left(1 - \frac{1}{\rho_k} \right) 
    + c_t \left(\vphantom{\frac{1}{\rho_k}}\rho_l - 1 \right)\right]}
	> 1.
\) 
Similarly, an economy benefits by increasing labor ($l$) 
without a commensurate increase in energy ($e$). 
Thus, $\rho_k$ is an 
efficiency of using additional labor and energy to make 
additional capital stock available to the economy, 
and $\rho_l$ is an efficiency of using additional energy to make 
additional labor available to the economy. 
Increases in $\rho_k$ and $\rho_l$ provide upward pressure on economic output ($y$),
as the only factor of production ($e$) is used more efficiently.

The parameter $a_0$ represents the overall importance of efficiencies $\rho_k$ and $\rho_l$, 
and the parameter $c_t$ represents the relative importance 
of the labor efficiency term ($\rho_l$) compared to the capital stock efficiency term ($\rho_k$). 
Both $a_0$ and $c_t$ are assumed constant with respect to time. 

\citet{Kummel:2002tx} use the 
LINEX production function to describe economic output 
for the economies of the U.S., Japan, and Germany. 
\citet{Warr:2010ga} compare the LINEX production function with 
the Cobb-Douglas production function to assess economic growth 
for Austria, the United Kingdom, the United States, and Japan. 
\citet{Ayres:2005kn} argued that introducing energy inputs 
in traditional production functions does not improve its explanatory power, 
but including useful work in a LINEX function does. 

\authNote{Martin: add more here about the conclusions of each paper 
regarding the role of energy in economic growth? Add additional literature? 
Or, adjust as you see fit. Especially, are there any confidence intervals 
or statistical evaluation in each of these studies?}

\authNote{If we want to keep this quote, it should be clearer what point we are trying to
make with it. ---rjp}
\citet{Abramovitz:1956aa} wrote:

\begin{quote}
  This result [that ``technological progress'' explained
  175\% of the growth of the US economy since 1870] is surprising in the lopsided
  importance which it appears to give to productivity increase,
  and it should be, in a sense, sobering, if not discouraging,
  to students of economic growth.
  Since we know little about the causes of productivity increase,
  the indicated importance of this element may be taken to be some sort of measure
  of our ignorance about the causes of economic growth in the United States
  and some sort of indication of where
  we need to concentrate our attention.
\end{quote}


%++++++++++++++++++++++++++++++
\subsection{Economy Types} 
\label{sec:Economy_Types}
%++++++++++++++++++++++++++++++

In the energy-economic growth literature, the focus is 
almost exclusively on developed economies from North America 
or Europe. Examples include \citet{Kummel:1980wx} applying 
LINEX to describe the West German economy, \citet{Serrenho:2010vq} 
applying Cobb-Douglas variants to EU-15 countries, 
\citet{VanderWerf:2008tc} applying CES nesting variants 
to the 12 OECD countries, \citet{Lecca:2011kr} applying 
CES nesting variants to the Scottish economy, \citet{Stern:2012ey} 
applying CES to describe the Swedish economy, and \citet{Warr:2012cg} 
using LINEX and Cobb-Douglas to describe the Austrian, 
American, British, and Japanese economies.

But, the near-exclusive focus on developed economies closes off 
the possibility of discovering any role that energy plays 
in the economic development process. In this paper we analyze at least 
two economies in each of the following four categories: 
Developed, 
NICs,\footnote{Newly Industrialized Countries}
OPEC, and 
LDCs.\footnote{Lesser Developed Countries} 
(See Table~\ref{tab:Economy_Examples}.)

\begin{table} \caption{Example economies and years of evaluation.} \label{tab:Economy_Examples} 
  \begin{center}
    \begin{tabular}{r c c l l} 
      \multirow{3}{*}{Developed} & \includegraphics[height=0.11in]{flag/flag_US.png} & US & USA & \multirow{3}{*}{1980--2011}\\
                                 & \includegraphics[height=0.11in]{flag/flag_UK.png} & UK & United Kingdom & \\
                                 & \includegraphics[height=0.11in]{flag/flag_JP.png} & JP & Japan          & \\
      \hline
      \multirow{2}{*}{NICs}      & \includegraphics[height=0.11in]{flag/flag_CN.png} & CN & China & \multirow{2}{*}{1991--2011}        \\
                                 & \includegraphics[height=0.11in]{flag/flag_ZA.png} & ZA & South Africa & \\
      \hline
      \multirow{2}{*}{OPEC}      & \includegraphics[height=0.11in]{flag/flag_SA.png} & SA & Saudi Arabia & \multirow{2}{*}{1991--2011} \\
                                 & \includegraphics[height=0.11in]{flag/flag_IR.png} & IR & Iran         &  \\
      \hline
      \multirow{2}{*}{LDCs}      & \includegraphics[height=0.11in]{flag/flag_TZ.png} & TZ & Tanzania & \multirow{2}{*}{1991--2011}     \\
                                 & \includegraphics[height=0.11in]{flag/flag_ZM.png} & ZM & Zambia      & \\
    \end{tabular}
  \end{center}
\end{table}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Sources of Data}
\label{sec:Sources_of_Data}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

To assess energy-augmented models of economic growth along the 
coordinates of analysis outlined in Section~\ref{sec:Coordinates}, 
historical data for economic output ($Y$), capital stock ($K$), 
labor ($L$), and thermal energy ($Q$)   %, exergy ($X$), and useful work ($U$) 
are required. Subsections below describe sources for and calculations 
to obtain historical data. A final subsection presents the historical 
data in graphical form.

%++++++++++++++++++++++++++++++
\subsection{Economic Output} 
\label{sec:Economic_Output_Data}
%++++++++++++++++++++++++++++++

We measure economic output ($Y$) by gross domestic product (GDP). 
GDP data in real 2005 U.S. dollars for developed countries (1980--2011) 
and all other countries (1991--2011) was obtained from 
the World Bank's Global Economic Prospects (GEP) database 
\citep{WorldBankGEP:2013a}.

%++++++++++++++++++++++++++++++
\subsection{Capital Stock} 
\label{sec:Capital_Stock_Data}
%++++++++++++++++++++++++++++++

Gross capital stock in real 2005 U.S. dollars 
for developed countries (1980--2011) and 
all other countries (1991--2011) was obtained from 
the World Bank's Global Economic Prospects (GEP) database 
\citep{WorldBankGEP:2013a}.

%++++++++++++++++++++++++++++++
\subsection{Labor and Employment}
\label{sec:Labor_Data}
%++++++++++++++++++++++++++++++

Total employment and average hours worked per worker per year 
for the developed nations (United States, United Kingdom, and Japan) 
for 1980--2011 were obtained from the United States 
\citet[Tables 6 and 7]{BLS:2013a}. Total hours worked per year was 
calculated by multiplying total employment by average hours worked 
per worker per year.  

The World Bank's World Development Indicators database 
\citep{WorldBankWDI:2013a} provides the employment to population 
ratio for people fifteen and older, total population, and a percentage 
of people under fifteen for other economies (South Africa, China, Iran, 
Saudi Arabia, Tanzania, and Zambia) for 1991--2011. The population 
of people under fifteen years of age was subtracted from total population 
to calculate the population of people fifteen and older. 
Total employment was calculated by multiplying the employment to 
population ratio of people fifteen and older by the population 
of people fifteen and older.

%++++++++++++++++++++++++++++++
\subsection{Energy} 
\label{sec:Energy_Data}
%++++++++++++++++++++++++++++++

To account for all energy input to an economy, we summed consumption data 
for many energy sources, including coal, oil and petroleum products, 
dry natural gas and natural gas plant liquids, nuclear power generation, 
and renewable energy sources (solar, wind, geothermal, biomass/fuel wood, 
and hydro). We also added human and animal muscle work. 
Similar to the economic data discussed in 
Sections~\ref{sec:Economic_Output_Data}--\ref{sec:Labor_Data}, 
we obtained energy data for developed countries from 1980--2011. 
For all other countries, 
we obtained energy data for 1991--2011. 

Thermal energy ($Q$) for fuels (in units of TJ/year) was calculated by

\begin{equation} \label{eq:thermal_energy}
  Q_{fuel} = C_{fuel}h_{fuel}
\end{equation}

\noindent where $C_{fuel}$ is the consumption rate of the fuel 
(in units of short tons/year for coal, barrels/year for oil and petroleum, 
ft$^3$/year for dry natural gas and natural gas plant liquids, 
and m$^3$/year for biomass/fuel wood) and $h_{{fuel}}$ is 
the heat content of the fuel (in kJ/short ton for coal, kJ/barrel for oil, 
kJ/ft$^3$ for dry natural gas and natural gas plant liquids, 
and kJ/kg for biomass/fuel wood). Fuel wood density of 300~kg/m$^3$ 
was taken from \citet{Ragland:2013wp} at the low end of the range 
of density of dry wood and bark.

Yearly consumption rates ($C_{fuel}$) of coal, oil and petroleum, 
dry natural gas and natural gas plant liquids, and biofuels 
(ethanol and biodiesel) were obtained from the \citet{EIA:2013a} 
for all economies. Yearly average heat content data for coal, oil, 
and natural gas and natural gas plant liquids was obtained from the 
EIA for all economies. We used lower (net) heating values of 
26.8~MJ/kg \citep[Table~A-27]{Cengel:2011ww} and 37.8~MJ/kg 
\citep[Table~7.3]{Gupta:2010vg} for the heat content of ethanol 
and corn-based biodiesel, respectively. Yearly consumption and 
heat content data for biomass/fuel wood was obtained from the 
``Fuelwood'' time series of the FAO Statistics Database 
\citep{FAO:2013a}.

For renewable and nuclear energy sources, yearly electricity 
generation (in BTU/year) was available directly from 
the \citet{EIA:2013a} for all economies, so 
Equation~\ref{eq:thermal_energy} was unnecessary.

Animal and human muscle work was estimated using an approach 
similar to \citet{Ayres:2010ug}, using data from Warr's 
REXS database \citep{Warr:2012a} and results from 
\citet{Wirsenius:2000vi}. For animal work, our analysis was 
restricted to draught animals (horses and mules). Muscle work 
from animals ($Q_{animals}$) was calculated using

\begin{equation} \label{eq:animal_muscle}
  Q_{animals} = Q_{m,horse}N_{horses} + Q_{m,mule}N_{mules}
\end{equation}

\noindent where $Q_m$ is metabolizable energy (in kcal/day-animal) 
and $N$ is the number of animals. Metabolizable energy values 
($Q_{m,horses}$ = 19,110 kcal/day-horse and $Q_{m,mules}$ = 
7,215 kcal/day-mule) were taken from \citet{Warr:2012a}. 
$Q_m$ represents the amount of energy in the feed consumed by 
animals for a day of work, and they are assumed constant for 
all countries and years. The number of horses and mules for 
each economy was taken from the ``Live Animals'' section of the 
FAO Statistics online database \citep{FAO:2013a}.

Human muscle power was calculated in a similar manner:

\begin{equation} \label{eq:human_muscle}
  Q_{workers} = Q_{m,workers} N_{workers}
\end{equation}

\noindent where the value of $Q_{m,workers}$ is the ``the amount 
of food available for human consumption'' (i.e., at the wholesale level) 
taken from the 
\citet[``\texttt{Dietary~Energy~Cons.~Countries}'' tab]{FAO:2013b}. 
The value for $N_{workers}$ was obtained from the labor time series 
for each economy as discussed in Section~\ref{sec:Labor_Data}.

<<Historical_Graph, fig.pos="H", fig.align='center', fig.width=3, fig.height=7.5, fig.cap="Historical data: indexed GDP ($y$), capital stock ($k$), labor ($l$), and thermal energy ($q$).">>=
historicalPlot(historicalData)
@

%++++++++++++++++++++++++++++++
\subsection{Historical Data} 
\label{sec:Historical_Data}
%++++++++++++++++++++++++++++++

Figure~\ref{fig:Historical_Graph} presents historical data, 
including indexed values for 
output ($y$), 
capital stock ($k$), 
labor ($l$), and 
energy ($q$) 
for 1980--2011 (developed economies) and 1991--2011 (other economies). 
Factors of production track each other closely, 
and high covariances among these variables can be seen in 
Tables~\ref{tab:Covariance_US}--\ref{tab:Covariance_ZM}. 
\authNote{Do we want to discuss the covariances?}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Parameter Estimation}
\label{sec:Parameter_Estimation}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%++++++++++++++++++++++++++++++
\subsection{Point Estimates}
%++++++++++++++++++++++++++++++

Each of the economic growth models discussed in 
Section~\ref{sec:Prod_Func_Forms} has parameters which must be estimated (fitted)
using data for each economy (see Section~\ref{sec:Economy_Types}).
We obtained parameter estimates by applying the method of least-squares to 
log-transformed data using the \texttt{R} \citep{R} functions
\texttt{lm} (for Cobb-Douglas and LINEX models) 
and \texttt{cesEst} \citep{Henningsen:2011td} (for CES models). 
\authNote{Need to check how CES is being fit and adjust this accordingly.}%

Although the details vary from model to model, each of our three models has the general form
\[
y = f(t,k,l,e; \theta) + \mathrm{error} \;,
\]
where $\theta$ is a vector of parameters for the function $f$.
\authNote{if we use $\theta$ this way, we need a new scaling parameter. --rjp}%
Parameter estimates are chosen to minimize
\[
\sum_{i} (y_i - f(t,k,l,e; \theta) )^2
\]
within constraints.
For the optimal parameter values $\hat \theta$, we define the 
fitted response by
\[
\hat y_i = f(t_i, k_i, l_i, e_i; \hat \theta)
\]
and the residuals
as the difference between the observed response and the fitted response
\begin{equation} \label{eq:residual}
  r_i 
  = y_i - \hat y_i
  = y_i - f(t,k,l,e; \hat\theta)
\end{equation}
The details for each of the models (including the effects of using 
log transformations) are discussed below.


%After back transforming to the natural scale of the data, the 
%residuals have a multiplicative rather than additive affect.
%The reflects an assumption that variability in GDP is roughly 
%proportion to GDP rather than constant.



%++++++++++++++++++++++++++++++
\subsection{Resampling Methods}
\label{sec:Resampling}
%++++++++++++++++++++++++++++++

Bootstrappng is a statistical resampling technique for assigning
measures of accuracy and precision to sample estimates by measuring
properties of an estimator when sampling from a resampling
distribution.  
Resampling distributions can be formed in a number of 
ways in accordance with the type of data, experimental design,
and modeling assumptions involved.  
In each case, many new resamples 
are created, each of which is a randomized version of the original sample data to 
which the desired analysis method can be applied.  
By investigating, for example,
the variability of a parameter estimate from one resample to another,
one can learn about the precision of the estimation method.
\authNote{Add some references here. --rjp}

In the context of linear models (regression), resamples are generally created
by residual resampling.  In our case, we formed resamples by adding to the fitted 
response ($\hat{y}$) the product of a residual from the original model fit and 
random sign ($-1$ or $1$, each with probability $0.5$).  
For the case of Cobb-Douglas and LINEX models, 
this residual resampling occurs on the 
log-transformed data.

Intuitively, this method assumes that the residuals are indicative of 
the variability (from many potential sources) inherent in the data so that
it would be unsurprising if the residual from 
any particular year had been observed in a different year. 
Thus, a resampled response $\tilde Y'$ can be computed as 
\[
\tilde Y_i' = \hat y_i \pm r_j
\]
where 
\[
r_i = y_i - \hat y_i
\]
both the sign ($\pm$) and the index of the residual ($j$, typically different from $i$) 
are chosen at random (with replacement). 
% Resampling in this way has the consequence 
% that a resampled time series could have non-unity first-year GDP ($\tilde Y_1 \neq 1$),
% so a renormalization takes place using the initial GDP from the
% resampled data as the new baseline, not the observed GDP in year 1.
% \begin{equation} \label{eq:resample_y}
% 	\tilde y_i  = \frac{\tilde Y_i'}{\tilde Y_1'}
% \end{equation}
% to obtain a resampled indexed GDP time series.
We repeated the resampling process 1000 times for each
combination of growth model and country, 
both with and without energy as appropriate.

The coefficients from the fit to a resampled time series
(the ``resample coefficients'') will be different from the coefficients 
obtained from the fit to historical data (the ``base coefficients'').
When these resample coefficients are highly variable, 
it is an indication
that the data do not determine the parameter estimates very precisely.
Lack of precision can stem from a number of factors, most obviously
a poor model fit, low model sensitivity to one or more parameters, 
or correlations between parameter estimates.
\authNote{This is not precisely true:
Large residuals in the fit to historical data (the ``base fit'')
are expected to produce large variation in resample coefficient values
(when the resampling is repeated 1000 times),
indicating less certainty in the value
of those coefficients. 
Similarly, small base fit residuals are expected to produce small
variation in resample coefficient values, indicating more-precise knowledge
of the model coefficients.
--rjp}


It is important to note that large residuals can arise from either
(a) poor quality historical time series data, or 
(b) a mathematical model that does not describe the underlying phenomena well.
It is also important to note that (c) even when the residuals are small and the 
model produces fitted values that track the observed data closely, it may
yet be difficult to estimate some or all of the model parameters precisely.
The resampling method employed herein reflects all three of these potential 
sources of uncertainty in parameter estimates.

\authNote{Should the description of model fitting come before or after 
the description of resampling?}


%++++++++++++++++++++++++++++++
\subsection{Cobb-Douglas Models}
\label{sec:CD_Parameter_Estimation}
%++++++++++++++++++++++++++++++

The Cobb-Douglas model without energy is given by 
Equation~\ref{eq:CD}. Equation~\ref{eq:CD} was
reparameterized as

\begin{equation} \label{eq:CD_reparam}
  y = \theta \mathrm{e}^{\lambda (t-t_0)} k^{\alpha} l^{1-\alpha}
\end{equation}

\noindent to ensure $\alpha + \beta = 1$ for constant returns to scale. 
$\lambda$ and $\alpha$ were estimated by the 
\texttt{R} \citep{R} function \texttt{lm} in log-transform space. 
If the estimated value for $\alpha$ was found outside the interval $[0,1]$, 
we set $\alpha$ to its boundary value and re-estimated $\lambda$. 
The value of $\beta$ was found with $\beta = 1 - \alpha$. 

To estimate the parameters $\lambda$, $\alpha$, $\beta$, and $\gamma$ 
in the energy-augmented Cobb-Douglas model, Equation~\ref{eq:CDe} 
was reparameterized as

\begin{equation} \label{eq:CDe_AB_reparam}
  y = \theta \mathrm{e}^{\lambda (t-t_0)} k^{\min(a,b)} l^{|b-a|} e^{1 - \max(a,b)}
\end{equation}

\noindent with 
$\alpha = \min(a,b)$, 
$\beta = |b-a|$, and 
$\gamma = 1 - \max(a,b)$.
The reparameterization ensures that $\alpha + \beta + \gamma = 1$,
thereby providing constant returns to scale.
The \texttt{R} \citep{R} function \texttt{lm} was used to estimate 
values of $\lambda$, $a$, and $b$ in log-transform space.
If the fitted value for $a$ ($b$) fell outside the range $[0,1]$, it was 
set equal to its boundary value and both $\lambda$ and $b$ ($a$) 
were re-estimated.

% The \texttt{nls} parameter estimation algorithm can encounter convergence difficulty 
% when the optimal value for the parameter represented by the absolute value function 
% (in Equation~\ref{eq:CDe_AB_reparam}, $\beta$) 
% lies near a boundary. If the absolute value exponent caused non-convergence of the 
% \texttt{nls} function, second and, if necessary, third reparameterizations 
% were attempted:
% 
% \begin{equation} \label{eq:CDe_CD_reparam}
%   y = A k^{1 - \max(c,d)} l^{\min(c,d)} e^{|d-c|}; A = \mathrm{e}^{\lambda (t-t_0)}
% \end{equation}
% 
% \begin{equation} \label{eq:CDe_FG_reparam}
%   y = A k^{|g-f|} l^{1 - \max(f,g)} e^{\min(f,g)}; A = \mathrm{e}^{\lambda (t-t_0)}
% \end{equation}
% 
% \noindent If none of the three reparameterizations converged, 
% the parameterization with the smallest sum of square errors ($sse$)
% was used. \ref{sec:Convergence_Resample_Models} shows the 
% fraction of unconverged models for each model type. 
% The above approach resulted in very few unconverged
% Cobb-Douglas resample models, even with \Sexpr{numResamples()} resamples.

Figure~\ref{fig:CD_Ternary_Scatter_Graph} shows ternary plots 
for $\alpha$, $\beta$, and $\gamma$ parameter values 
for Cobb-Douglas (without and with energy) resample models.
Each reample is shown as a gray dot on the graph. 
The fit to historical data is shown as a gray crosshairs.

Figure~\ref{fig:CD_GDP_Spaghetti_Graph} compares predictions 
from the Cobb-Douglas models 
(without and with energy) to historical data.
Historical data are shown as a black line. 
The fit to historical data is shown as a white line.
The gray band encompasses 95\% of the fits to resampled data.

\twocolumn{}
<<CD_Ternary_Scatter_Graph, fig.pos="H", fig.align='center', fig.width=2.9, fig.height=7.7, fig.cap="Cobb-Douglas resample model parameters.">>=
cdCoeffsData <- filter(coeffs_df, model=="cd", nestStr %in% c("iK+iL", "iK+iL+iQ"))
standardTriPlot(data=cdCoeffsData, facet_formula=country~energy)
@

<<CD_GDP_Spaghetti_Graph, fig.pos="H", fig.align='center', fig.width=3, fig.height=8.2, fig.cap="Cobb-Douglas fitted models.">>=
cdFittedData <- filter(fitted_df, model=="cd", nestStr %in% c("iK+iL", "iK+iL+iQ"))
spaghettiPlot(data=cdFittedData, facet_formula=Country~energy, level=spaghettiGraphLevel) +
    labs(y="Indexed GDP (1980=1 or 1991=1)")
@
\onecolumn{}


%++++++++++++++++++++++++++++++
\subsection{CES Models}
\label{sec:CES_Parameter_Estimation}
%++++++++++++++++++++++++++++++

The CES model without and with energy is given by 
Equations~\ref{eq:CES}--\ref{eq:CESekl}. 
The \texttt{R} \citep{R} package \texttt{micEconCES} 
\citep{Henningsen:2011td} was used to estimate parameters 
$\lambda$, $\gamma$, $\delta$, $\delta_1$, $\rho$, and $\rho_1$. 
The \texttt{cesEst} function of \texttt{micEconCES} provides 
several algorithm options for parameter estimation.
The default algorithm (Levenberg-Marquardt) does not respect
parameter constraints (see Section~\ref{sec:CES}) and, 
in our testing, nearly always violated them, often returning
negative values for elasticity of substitution ($\sigma$) parameters.
Thus, we used the two fitting algorithms available in \texttt{cesEst} that
respect coefficient constraints: \texttt{PORT} and \texttt{L-BFGS-B}. 

Our CES parameter estimation algorithm starts with an eleven-value grid search
in $\rho$ and $\rho_1$ (9, 2, 1, 0.43, 0.25, 0.1, -0.1, -0.5, -0.75, -0.9, -0.99),
which corresponds to $\sigma$ and $\sigma_1$ values of
0.1, 0.33, 0.5, 0.7, 0.8, 0.9, 1.11, 2, 4, 10, and 100, respectively.
During the grid search, values of $\rho$ and $\rho_1$ are fixed,
and values of $\lambda$, $\gamma$, $\delta$, and $\delta_1$ are estimated 
by gradient search with the \texttt{PORT} and \texttt{L-BFGS-B} algorithms.
In all, 121 gradient searches in $\lambda$, $\gamma$, $\delta$, and $\delta_1$
at grid points representing all combinations of $\rho$ and $\rho_1$ are attempted.
During the grid search portion of our algorithm, starting values for the free parameters
are $\lambda$ = 0.015/year, $\delta$ = 0.5, $\delta_1$ = 0.5, 
and $\gamma$ is set to a value such that the mean of the residuals is zero
by the \texttt{cesEst} function.

Next, a gradient search (using both \texttt{PORT} and \texttt{L-BFGS-B}) 
is attempted wherein all fitting parameters 
($\lambda$, $\gamma$, $\delta$, $\delta_1$, $\rho$, and $\rho_1$)
are allowed to float. 
The start values for fitting parameters are taken from 
the grid search fit that provided the lowest $sse$.

If resampled data are being fitted, a prior fit to historical data is available.
In the final step of our algorithm, 
a gradient search (using both \texttt{PORT} and \texttt{L-BFGS-B})
uses coefficients from the best 
fit to historical data as its starting point. 
In this final gradient search, all model parameters 
($\lambda$, $\gamma$, $\delta$, $\delta_1$, $\rho$, and $\rho_1$)
are considered free parameters.

The fit with lowest $sse$ of all above trials is deemed the winner,
and its fitting parameters are used as the model.

\citet{Henningsen:2011td}, 
in their detailed analysis of \citet{Kemfert:1998vd}, found that 

\begin{quote}
\ldots the Levenberg-Marquardt and the \texttt{PORT} algorithms 
are---at least in this study---most likely to find the 
coefficients that give the best fit to the model, 
where the \texttt{PORT} algorithm can be used to restrict the estimates 
to the economically meaningful region.
\end{quote}

In our testing, we found that to be mostly true. 
\texttt{PORT} nearly always provided lower
$sse$ than \texttt{L-BFGS-B}, despite the fact that 
\texttt{L-BFGS-B} often reports convergence
and \texttt{PORT} does not for the same data
(i.e., for the same $y$, $k$, $l$, and $e$ data).

Coefficients for each resampled CES model for all countries and all nests
are shown in 
Figures~\ref{fig:CES_lambda_gamma_graph}--\ref{fig:CES_sigma_delta_graph}. 
The white crosshair on each graph shows the location 
of the fit to historical data. 
In Figures~\ref{fig:CES_sigma1_delta1_graph} and~\ref{fig:CES_sigma_delta_graph},
the bottom of the vertical axis represents $\sigma = 0$.
The top of the vertical axis represents $\sigma = \infty$.

Note that as $\delta$ or $\delta_1$ approaches 0 (1) 
in Equations~\ref{eq:CES}--\ref{eq:CESekl},
the corresponding value of $\sigma$ or $\sigma_1$ becomes irrelevant, and
resample points along the left (right) edge of
Figures \ref{fig:CES_sigma1_delta1_graph} and \ref{fig:CES_sigma_delta_graph}
are equivalent.
That is, all points along the left (right) edge of
Figures \ref{fig:CES_sigma1_delta1_graph} and \ref{fig:CES_sigma_delta_graph}
have the same $sse$. 
As a consequence, 
the \texttt{cesEst} fitting algorithm has no way 
to discriminate among points along the left (right) edge of
Figures \ref{fig:CES_sigma1_delta1_graph} and \ref{fig:CES_sigma_delta_graph}. 
Thus, resample point estimates where $\delta$ or $\delta_1$ approaches 0 (1)
tend to cluster at the locations of the initial grid search in 
$\sigma$ or $\sigma_1$
(0.1, 0.33, 0.5, 0.7, 0.8, 0.9, 1.11, 2, 4, 10, and 100).

<<CES_lambda_gamma_graph, fig.pos="H", fig.align='center', fig.width=fourPanelScatterGraphWidth, fig.height=ninePanelScatterGraphHeight, fig.cap="$\\lambda$ and $\\gamma$ values for CES resample models.">>=
cesCoeffsData <- filter(coeffs_df, model=="ces", nestStrParen %in% c("(iK + iL) + ()", 
                                                                     "(iK + iL) + (iQ)", 
                                                                     "(iL + iQ) + (iK)", 
                                                                     "(iQ + iK) + (iL)"))
standardScatterPlot(data=cesCoeffsData, mapping=aes(gamma_coef, lambda), facet_formula=country~nestStrParen, alpha=0.05) +
    scale_x_continuous(breaks=c(0.9, 1.0, 1.1)) +
    scale_y_continuous(breaks=c(0, 0.025, 0.05, 0.075)) +    
    labs(x=expression(gamma), y=expression(lambda))
@

<<CES_sigma1_delta1_graph, fig.pos="H", fig.align='center', fig.width=fourPanelScatterGraphWidth, fig.height=ninePanelScatterGraphHeight, fig.cap="$\\sigma_1$ and $\\delta_1$ values for CES resample models.">>=
standardScatterPlot(data=cesCoeffsData, mapping=aes(delta_1, sigma_1), facet_formula=country~nestStrParen, alpha=0.05) +
    coord_trans(y="sigma") +
    scale_x_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    scale_y_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    labs(x=expression(delta[1]), y=expression(sigma[1]))
@

<<CES_sigma_delta_graph, fig.pos="H", fig.align='center', fig.width=4.5, fig.height=7, fig.cap="$\\sigma$ and $\\delta$ values for CES resample models.">>=
standardScatterPlot(data=subset(cesCoeffsData, nestStrParen != "(iK + iL) + ()"),
                    mapping=aes(delta, sigma), facet_formula=country~nestStrParen, alpha=0.05) +
    coord_trans(y="sigma") +
    scale_x_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    scale_y_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    labs(x=expression(delta), y=expression(sigma))
@

We can develop pseudo $\alpha$, $\beta$, and $\gamma$ parameters 
for the CES model, based on values of $\delta$ and $\delta_1$.
Table~\ref{tab:CES_abg_equations} shows the permuted equations for each CES nesting.

\begin{table} \caption{Equations for $\alpha$, $\beta$, and $\gamma$ for the various CES nestings.} 
\label{tab:CES_abg_equations} 
  \begin{center}
    \begin{tabular}{c c c c c} 
      Nesting    & Equation        & $\alpha$                & $\beta$                 & $\gamma$                \\
      \hline
      ($kl$)     & \ref{eq:CES}    & $\delta_1$              & $1 - \delta_1$          & 0                       \\
      ($kl$)$e$  & \ref{eq:CESkle} & $\delta \delta_1$       & $\delta (1 - \delta_1)$ & $1 - \delta$            \\   
      ($le$)$k$  & \ref{eq:CESlek} & $1 - \delta$            & $\delta \delta_1$       & $\delta (1 - \delta_1)$ \\
      ($ek$)$l$  & \ref{eq:CESekl} & $\delta (1 - \delta_1)$ & $1 - \delta$            & $\delta \delta_1$       \\
    \end{tabular}
  \end{center}
\end{table}

Figure~\ref{fig:CES_ternary_graph} shows 
$\alpha$, $\beta$, and $\gamma$ parameters for the CES model for all nests and countries.
Figure~\ref{fig:CES_ternary_graph} is comparable to
the ternary graph for the Cobb-Douglas models, 
Figure~\ref{fig:CD_Ternary_Scatter_Graph}.

<<CES_ternary_graph, fig.pos="H", fig.align='center', fig.width=5.5, fig.height=7.5, fig.cap="$\\alpha$, $\\beta$, and $\\gamma$ values for CES resample models.">>=
standardTriPlot(data=cesCoeffsData, facet_formula=country~nestStrParen)
@

Figure~\ref{fig:CES_Spaghetti_Graph} compares CES model predictions 
to historical data for all nestings. 
Historical data are shown as a black line. 
The fit to historical data is shown as a white line.
The gray band encompasses 95\% of the fits to resampled data.

<<CES_Spaghetti_Graph, fig.pos="H", fig.align='center', fig.width=6.5, fig.height=8.5, fig.cap="CES fitted models.">>=
cesFittedData <- filter(fitted_df, model=="ces", nestStrParen %in% c("(iK + iL) + ()", 
                                                                     "(iK + iL) + (iQ)", 
                                                                     "(iL + iQ) + (iK)", 
                                                                     "(iQ + iK) + (iL)"))
spaghettiPlot(data=cesFittedData, facet_formula=Country~nestStrParen, level=spaghettiGraphLevel) +
    labs(y="Indexed GDP (1980=1 or 1991=1)")
@

Figure~\ref{fig:CES_Spaghetti_Graph_CN} shows details of the resample fits for China with the (kl)e nesting.
Again, historical data are shown as a black line. 
The fit to historical data is shown as a white line.
The gray band encompasses 95\% of the fits to resampled data.

<<CES_Spaghetti_Graph_CN, fig.pos="H", fig.align='center', fig.width=maxWidth, fig.height=maxHeight, fig.cap="CES fitted models for China with the (kl)e nesting.">>=
spaghettiPlot(data=subset(cesFittedData, Country=="CN" & nestStrParen=="(iK + iL) + (iQ)"), level=spaghettiGraphLevel) +
    labs(y="Indexed GDP (1980 = 1 or 1991 = 1")
@


%++++++++++++++++++++++++++++++
\subsection{LINEX Models}
\label{sec:LINEX_Parameter_Estimation}
%++++++++++++++++++++++++++++++

The LINEX model is given in Equation~\ref{eq:LINEX}. 
If the fitting algorithm drives $a_0 \rightarrow 0$, 
any changes to $c_t$ have no effect on $sse$, 
leading the fitting algorithm to report non-convergence. 
To avoid this problem, we transformed the LINEX model into

\begin{equation} \label{eq:LINEX_transformed}
  y = Ae; 
  A = \mathrm{e}^{\left[2 a_0 \left(1 - \frac{1}{\rho_k} \right) 
    + a_1 \left(\vphantom{\frac{1}{\rho_k}}\rho_l - 1 \right)\right]},
\end{equation}

\noindent where $a_1 \equiv a_0 c_t$. 
We used the \texttt{lm} function in \texttt{R}
\citep{R} to estimate least-squares values for $a_0$ and $a_1$ in 
Equation~\ref{eq:LINEX_transformed}. 
We recovered a value for $c_t$ with $c_t = a_1 / a_0$. 
The reparameterization
shown in Equation~\ref{eq:LINEX_transformed} reduced the number of 
unconverged resample fits to zero: 

Figure~\ref{fig:LINEXq_Resample_Graph}
shows the coefficients estimated from resampled data.

Figure~\ref{fig:LINEX_Spaghetti_Graph} compares LINEX model predictions to historical data.
Historical data are shown as a black line. 
The fit to historical data is shown as a white line.
The gray band encompasses 95\% of the fits to resampled data.

\twocolumn{}
<<LINEXq_Resample_Graph, fig.pos="H", fig.align='center', fig.width=2, fig.height=7, fig.cap="LINEX model (with energy) resampling results.">>=
linexCoeffsData <- filter(coeffs_df, model=="linex", energy=="iQ")
standardScatterPlot(data=linexCoeffsData, aes(a_0, c_t), facet_formula=country~energy, alpha=0.05) +
    labs(x=expression(a[0]), y=expression(c[t])) +
     scale_x_continuous(limits=c(-1, 2), breaks=c(-1, 0, 1.0, 2.0)) +
     scale_y_continuous(limits=c(0, 10), breaks=c(0, 5, 10))
@

<<LINEX_Spaghetti_Graph, fig.pos="H", fig.align='center', fig.width=2, fig.height=7.1, fig.cap="LINEX fitted models.">>=
linexFittedData <- filter(fitted_df, model=="linex", energy=="iQ")
spaghettiPlot(data=linexFittedData, facet_formula=Country~energy, level=spaghettiGraphLevel) +
    labs(y="Indexed GDP (1980=1 or 1991=1)")
@
\onecolumn{}

%++++++++++++++++++++++++++++++
\subsection{Parameter Estimation Summary}
\label{sec:Parameter_Estimation_Summary}
%++++++++++++++++++++++++++++++

**** Include a table here of important values. 
Include a table of convergence? (In appendix?)
Martin to suggest the form of this table after working 
on the interpretation for a while. ****


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Discussion of Results}
\label{sec:Discussion_of_Results}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Drive towards new insights from our stats tested comparative approach.

**** Notes for interpretation of results ****

R$^2$ not a good measure. 
Limited insights are obtained from $t$ and $p$ values, 
especially on PFs that have parameters with constraints (CD, CES).

We found that we are able to maintain good fits while respecting theoretical foundations
of the models (i.e., respect parameter constraints). No need to relax parameter constraints
and, thereby, contradict micro foundations.

CD assumes $\sigma_1 = 1$. CES doesn't assume a value for $\sigma_1$. 
The $\sigma_1$ vs. $\delta_1$ graphs for CES without energy often have 
two frequent values for $\sigma_1$.  One of those frequent values is
nearer to $\sigma_1 = 1$. When CD and CES without energy do not agree on 
share values (CD: $\alpha$ compared to $\beta$, CES: $\delta_1$) for the 
base curve fit (red dot), they do agree for the data that clusters near 
$\sigma_1 = 1$ for the CES fits.

Country interpretation

Comparison Cobb Douglas and CES results.

%++++++++++++++++++++++++++++++
\subsection{United States} 
\label{sec:InterpUS}
%++++++++++++++++++++++++++++++

CD: Energy is unnecessary

CES with $q$:

($kl$): $\delta_1 = 0.3, \sigma_1 = 0.8$. $k$ is less necessary. 
Complements, but close to substitutes.
signal of substitutability in the spread.

($kl$)$e$: energy is unnec ($\delta = 1$). 
$\delta_1 = 0.45$: $k$ and $l$ are about equally necessary.
$\sigma_1 = 0.8$: $k$ and $l$ are slight complements. 
Spread on $0.25 < \sigma_1 < \infty$, signalling 
possibilities of substitution.

($el$)$k$: energy is unnec. ($\delta_1$ is 0); 

($le$)$k$ no indication
Relative consistent signal that energy is unnec.

CES with $u$: 

($kl$)$e$: $\delta = 1$, signalling $e$ unnecessary. 
$\sigma = 0.8$, indicating clost to substitutability,
but still complementary. 
$\delta_1 = 0.25$, with large spread. not strong for $k$.
$\sigma_1 \rightarrow \infty$, but with large spread from 0.2 upward. 
Signals complementarity between $k$ and $l$.

%++++++++++++++++++++++++++++++
\subsection{United Kingdom} 
\label{sec:InterpUK}
%++++++++++++++++++++++++++++++

CD: Capital is unnec.

CES with $q$: 

($kl$): $\delta_1 = 0.7, \sigma_1 = 0.35$. 
$kl$ complementary, $k$ is more important, because $\delta_1 > 0.5$. 
Large spread on $\delta_1$. 
Complementary signal is consistent, however.

($kl$)$e$: energy is unnec ($\delta = 1$). 
$\delta_1 = 0.25$, $k$ is less necessary. 
$\sigma_1 \rightarrow \infty$, giving strong $kl$ substitutability signal.

($le$)$k$ capital is unnec. ($\delta = 1$); 

($ek$)$l$ ($\delta_1 = 0$) energy is unnec.

Thus, inconsistent results, possibly look at different time series 
as massive changes in economic policy in Uk economic history

CES with $u$: 

($kl$)$e$: $\delta = 1$, $u$ is unnecessary. 
$\sigma = 0.8$, approache complementarity between $kl$ and $e$.
$\delta_1 = 0.1$. 
$\sigma_1 \rightarrow \infty$, indicating substitutability between $k$ and $l$.


%++++++++++++++++++++++++++++++
\subsection{Japan} 
\label{sec:InterpJP}
%++++++++++++++++++++++++++++++

CD: energy is unnec.

CES with $q$: 

($kl$): $\delta_1 = 0.7, \sigma_1 = 0.25$. Very little scatter. Both are well-known. 
$l$ is close to unnecessary. $k$ and $l$ are complements.

($kl$)$e$: no indications, all are important. $\delta = 0.6$, both $kl$ and $e$ are necessary.
$0.5 < \delta < 1$.
$\sigma=0.1$ signalling complementarity betwen $kl$ and $e$.
$\delta_1 = 0.8$ signalling $l$ is almost unnecessary. 
$\sigma_1 = 0.1$, signalling complementarity 
between $k$ and $l$.

($le$)$k$: no indications, all are important. 

($ek$)$l$: no indications, all are important. 

weak signal that labour is less necessary 
(($kl$)$e$ $delta_1 = 0.86$ and ($ek$)$l$ $\delta = 0.89$)

Thus, inconsistent results.

CES with $u$: 

($kl$)$e$: $\delta = 0.6, \sigma = 0.4$. Complementarity between $kl$ and $e$.
$\delta_1 = 1$, indicating $l$ unnecessary. $\sigma_1 = 0.1$, indicating complementarity
between $k$ and $l$. Need only one of $k$ or $l$ in your equation, but they are
complemetary! You need one to have the other.


%++++++++++++++++++++++++++++++
\subsection{China} 
\label{sec:InterpCN}
%++++++++++++++++++++++++++++++

CD: energy not necessary, capital less necessary

CES with $q$: 

($kl$): $\delta_1 = 0.3$, so $k$ is getting close to unnecessary. $\sigma_1 = 1.25$.
$k$ and $l$ are substitutes. Large spread in $\delta_1$ from 0.1 to 1.0. Large spread in
$\sigma_1$, but most points have $\sigma_1 > 1$.

($kl$)$e$: $\delta = 0.8$. however, strong signal at $0.8 < \delta < 1$, 
signalling that energy is less necessary. $0.5 < \delta < 1$. $\sigma = 0.5$, 
signalling complementarity between $kl$ and $e$. 
$\delta_1 = 1$, signalling that $l$ is unnecessary. $\sigma_1 = 0.1$, signalling
that $k$ and $l$ are complementary. Both $\delta_1$ and $\sigma_1$ have large spreads, 
so our confidence in these results is low.

($le$)$k$: labour is unnnec ($\delta_1 = 0$); 

($ek$)$l$ energy is unnec. ($\delta_1 \rightarrow 0$)

Strong signal that energy is unnec, but the labour and capital signals are conflicting

%++++++++++++++++++++++++++++++
\subsection{South Africa} 
\label{sec:InterpZA}
%++++++++++++++++++++++++++++++

CD: Labour is unnec.

CES with $q$: 

($kl$): $\delta_1 = 0.35, \sigma_1 = 0.8$. $k$ is relatively less necessary. $k$ and $l$ 
are complements but relatively close to being substitutes. Spread is tight between 
$0.25 < \delta_1 < 0.5$ and $\sigma_1$ is consistently complementary 
between $0.1 < \sigma_1 < 0.8$.

($kl$)$e$: labour is unnec. ($\delta_1 = 1$). $\delta = 0.25$, signalling complemtarity 
between $kl$ and $e$, but large spread from 0 to 1. $\sigma$ and $\sigma_1$ are both 0, 
indicating perfect complements betwen $kl$ and $e$ and between $k$ and $l$.

($le$)$k$ labour is unnec. ($\delta_1 = 0$); 

($ek$)$l$ labour is unnec. ($\delta = 1$)

Consistent signal that labour is unnec.

%++++++++++++++++++++++++++++++
\subsection{Saudi Arabia} 
\label{sec:InterpSA}
%++++++++++++++++++++++++++++++

CD: no indications

CES with $q$: 

($kl$): $\delta_1 = 0.85$. $l$ is unnecessary. 
$\sigma_1 = 0.1$ indicating strong complementarity between 
$k$ and $l$. Spread of $0.15 < \delta_1 < 1$. 
$0 < \sigma_1 < 0.8$, signalling complementarity.

($kl$)$e$: $\delta = 0.6$, $e$ is less necessary (weak signal). 
Big spread on $\delta$ between 0 and 0.8.
$\sigma = 0.1$ indicating complementarity between $kl$ and $e$. $\delta_1 = 0.8$ 
(with large spread between 0.3 and 1), labor is less necessary.
$\sigma_1 = 0.1$: very complementary between $k$ and $l$.

($le$)$k$:

($ek$)$l$: weak signal that labour is unnec ($\delta = 0.93$)

Almost consistent signal that no indocations.

%++++++++++++++++++++++++++++++
\subsection{Iran} 
\label{sec:InterpIR}
%++++++++++++++++++++++++++++++

CD: energy is unnec.

CES with $q$: 

($kl$): $\delta_1 = 0.3$. Spread $0 < \delta_1 < 0.7$. $0 < \sigma_1 < 0.8$. $\sigma_1 = 0$. 
Strong complementarity. $k$ is less necessary compared to $l$.

($kl$)$e$: energy is unnec ($\delta=1$). 
$\sigma = 0.75$ indicating complementarity between $kl$ and $e$, approaching substitutibility.
$\delta_1 = 0.3, \sigma_1 = 0$ indicating strong perfect complementarity between $k$ and $l$.

($le$)$k$: energy is unnec. ($\delta_1=1$); 

($ek$)$l$: labour is unnec. ($\delta=1$)

%++++++++++++++++++++++++++++++
\subsection{Tanzania} 
\label{sec:InterpTZ}
%++++++++++++++++++++++++++++++

CD: labour in unnec.

CES with $q$: 

($kl$): $\delta_1 = 0.8$ $0.3 < \delta_1 < 1$ signalling labor is less necessary.
$\sigma_1 = 0.1$ $0 < \sigma_1 < 0.8$, signalling complementary $k$ and $l$.

($kl$)$e$: labour is unnec ($\delta_1=0.97$). 
$\delta = 0.45$, so $kl$ and $e$ both necessary, but 
$\sigma \rightarrow \infty$, so $kl$ and $e$ has perfect substitutibility.
$\sigma_1 = 0.1$, so $k$ and $l$ are perfect complements. 
Spread on $\delta$ is large (0.2 to 1).
So, we are unsure about the value of $\delta$.

($le$)$k$: weak signal that energy is unnec. ($\delta_1=0.92$); 
very weal signal capital is unnec ($\delta=0.84$); 

($ek$)$l$: labour is unnec. $\delta=0.96$

Consistent signal that labour is unnec, with exception of one nesting.

%++++++++++++++++++++++++++++++
\subsection{Zambia} 
\label{sec:InterpZM}
%++++++++++++++++++++++++++++++

CD: labour is unnec; energy is unnec.

CES with $q$: 

($kl$): $\delta_1 = 1$: $l$ is unnecessary. 
$0.5 < \delta_1 < 1$. $\sigma_1 = 0.8$ without any 
noticeable spread indicating complemetary.

($kl$)$e$: labour is unnec. ($\delta_1=1$). 
$\delta = 0.6$, $kl$ and $e$ are both necessary. 
$\sigma \rightarrow \infty$, signalling substitutability between $kl$ and $e$. 
$\sigma_1 = 0.8$ with very large spread between 0 and 2. 
Approaching substitutability between $k$ and $l$ and perfect substitutibility
between $kl$ and $e$. Very little certainty here.

($le$)$k$: ($\delta_1=0$); 

($ek$)$l$: labour is unnec. ($\delta=1$)

Consistent signal that labour is unnec.


Discussion of results: 

How to get better consistent signals?

\begin{itemize}
\item{Use CD as starting points and do CES convergence on that basis.}
\item{Do scatterplots to get range of uncertainty inputs, then re-interpret. 
$\delta$ against $\sigma$ plots, as well as $\delta_1$ and $\sigma_1$ plots.}
\end{itemize}

Thus, to do the fitting well we need to understand:
\begin{itemize}
\item{nesting}
\item{algorithm}
\item{starting values}
\end{itemize}
esp. for CES.

(Maybe illustrate with one case study such as China what implications are).

How do we compare with LINEX results?

CES is a broader specification of CD, LINEX is not. 
In LINEX neither $\delta$s nor $\sigma$s are generated. 
Only efficiency terms are generated in LINEX, 
thus in other words economic growth is only possible by increased efficiency. 
The efficiency of using energy is driven by capital stock. 
The objective/growth engine is to increase capital 
at a rate that is faster then growth in labour and energy.  
Increasing labour relative to energy gives a muted benefit. 
LINEX derived for Germany: only really applicable when energy and capital are complements.

Discussion in relation to other papers. 
Problems with other papers:
\begin{itemize}
\item{If not giving you all parameters}
\item{Not explain nesting approach}
\item{No CI on data}
\end{itemize}

Economic interpretation (revisit after scatterplot information)
Developed economies: Capital and energy is complementary (US: labour and energy substitutable)
NICs: Capital and energy complementary, but labour and energy more substitutable
OPEC: Labour and energy complementary (mixed results on capital and energy)
LDCs: Labour and energy complementary, Capital and energy perfect substitutes.





%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Conclusion}
\label{sec:Conclusion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Future Work}
\label{sec:FutureWork}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Acknowledgements}
\label{sec:Acknowledgements}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Funding for Caleb Reese and Lucas Timmer was provided 
by the Jack and Lois Kuipers Applied Mathematics Endowment and 
the Calvin College Alumni Association. 
Partial support for Matthew Kuperus Heun was 
provided by a Calvin College Research Followship. 
Partial funding for Martin de Wit was provided 
by the South African National Research Foundation (NRF).\footnote{Any opinion, 
findings, and conclusions or recommendations expressed herein are those 
of the authors, and, therefore, NRF does not accept any liability in regard thereto.} 
The authors are grateful to Benjamin S. Warr (INSEAD) for providing 
the REXS database \citep{Warr:2012a}. 
The authors thank Loren L. Heun (Western Michigan University) 
for insightful critique of the statistical analyses presented herein.
The computations in this paper were accomplished using \url{http://dahl.calvin.edu}, 
a Beowulf cluster built with support from the National Science Foundation's 
Major Research Instrumentation and Cyber Infrastructure programs, 
grant number OCI-0722819.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Reproducible Research}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In the spirit of Reproducible Research \citep{Gandrud:2013vx}, 
all data, spreadsheets, \texttt{R} code \citep{R}, and other materials 
associated with this paper can be found at\\*
\protect\url{https://github.com/MatthewHeun/Econ-Growth-R-Analysis}.

%% The Appendices part is started with the command \appendix;
%% appendix sections are then done as normal sections
%% \appendix
%% \section{}
%% \label{}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\appendix
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Covariance Tables}
\label{sec:Covariance_Tables}
\setcounter{table}{0} % Restarts table number counter at 0 in this section.
\setcounter{figure}{0} % Restarts figure number counter at 0 in this section.
\setcounter{equation}{0} % Restarts equation counter to 0 in this section.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Convergence of Resample Models}
\label{sec:Convergence_Resample_Models}
\setcounter{table}{0} % Restarts table number counter at 0 in this section.
\setcounter{figure}{0} % Restarts figure number counter at 0 in this section.
\setcounter{equation}{0} % Restarts equation counter to 0 in this section.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The following table shows the fraction of resample models 
that did not achieve convergence when estimating model parameters.

<<Unconverged_Frac_Table, results='asis'>>=
# printFracUnconvergedXtable()
  data <- fracUnconvergedResampleFitsAll(baseResample=baseResample)
  dataXtable <- xtable(x=data, 
                       caption="Fraction of unconverged resample models", 
                       label="tab:frac_unconverged_models",
                       digits = 3,
                       align = "rl|cc|ccccccccc") #Sets alignment of the numbers in the columns)
  print(dataXtable, 
        caption.placement="top", 
        size="\\tiny",
        table.placement="H",
        include.rownames=FALSE)
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{95\% Confidence Intervals}
\label{sec:Confidence_Intervals}
\setcounter{table}{0} % Restarts table number counter at 0 in this section.
\setcounter{figure}{0} % Restarts figure number counter at 0 in this section.
\setcounter{equation}{0} % Restarts equation counter to 0 in this section.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Resample coefficients in the scatter plots 
can be represented as 95\% confidence intervals 
by finding the parameter values associated with 
the middle 95\% of the data for each model parameter.
This appendix provides tables and graphs of the 95\% confidence
intervals on fitted model parameters. 


%++++++++++++++++++++++++++++++
\subsection{Cobb-Douglas Models}
%++++++++++++++++++++++++++++++

The 95\% confidence intervals associated with 
the without-energy column of Figure~\ref{fig:CD_Ternary_Scatter_Graph} 
are shown in Table~\ref{tab:CD_Parameters_No_Energy}.

<<CD_Params_Table, results='asis'>>=
printCDParamsTable(energyType="none", baseResample=baseResample)    #Without energy
@

The data in Table~\ref{tab:CD_Parameters_No_Energy} are plotted in
Figure~\ref{fig:CD_Params_Graph}.

<<CD_Params_Graph, fig.pos="H", fig.width=cdParameterGraphWidth, fig.height=cdParameterGraphHeight, fig.cap="Cobb-Douglas (without energy) model parameters. Vertical bars indicate 95\\% confidence intervals.">>=
createCDParamsGraph(energyType="none", baseResample=baseResample)
@

The 95\% confidence intervals associated with 
the with-energy column of Figure~\ref{fig:CD_Ternary_Scatter_Graph} 
are shown in Table~\ref{tab:CD_Parameters_With_Q}
and Figure~\ref{fig:CDq_Params_Graph}.

<<CDq_Params_Table, results='asis'>>=
printCDParamsTable(energyType="Q", baseResample=baseResample)   #With energy
@

<<CDq_Params_Graph, fig.pos="H", fig.width=cdParameterGraphWidth, fig.height=cdParameterGraphHeight, fig.cap="Cobb-Douglas (with energy) model parameters. Vertical bars indicate 95\\% confidence intervals.">>=
createCDParamsGraph(energyType="Q", baseResample=baseResample)
@


%++++++++++++++++++++++++++++++
\subsection{CES Models}
%++++++++++++++++++++++++++++++

The 95\% confidence intervals associated 
with ($kl$) nest columns of 
Figures~\ref{fig:CES_lambda_gamma_graph}--\ref{fig:CES_ternary_graph}
are shown in Tables~\ref{tab:CES_Parameters_A} 
and \ref{tab:CES_Parameters_B} and Figure~\ref{fig:CES_Params_Graph}.

<<CES_Params_Table, results='asis'>>=
print(cesParamsTableA(energyType="none", nest="(kl)", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")
print(cesParamsTableB(energyType="none", nest="(kl)", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")
@

<<CES_Params_Graph, fig.pos="H", fig.width=cesParameterGraphWidth, fig.height=cesParameterGraphHeight, fig.cap="CES (without energy, ($kl$) nesting) model parameters. Vertical bars indicate 95\\% confidence intervals.">>=
createCESParamsGraph(energyType="none", nest="(kl)", baseResample=baseResample)
@

The 95\% confidence intervals associated 
with ($kl$)$e$ nest columns of 
Figures~\ref{fig:CES_lambda_gamma_graph}--\ref{fig:CES_ternary_graph}
are shown in Tables~\ref{tab:CES_Parameters_A_With_Q_(kl)e} and 
\ref{tab:CES_Parameters_B_With_Q_(kl)e} and Figure~\ref{fig:CESq_Params_Graph_kle}.

<<CESq_Params_Table_kle, results='asis'>>=
print(cesParamsTableA(energyType="Q", nest="(kl)e", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")
print(cesParamsTableB(energyType="Q", nest="(kl)e", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")


@

<<CESq_Params_Graph_kle, fig.pos="H", fig.width=cesParameterGraphWidth, fig.height=cesParameterGraphHeight, fig.cap="CES (with energy, ($kl$)$e$ nesting) model parameters. Vertical bars indicate 95\\% confidence intervals.">>=
createCESParamsGraph(energyType="Q", nest="(kl)e", baseResample=baseResample)
@

The 95\% confidence intervals associated 
with ($le$)$k$ nest columns of 
Figures~\ref{fig:CES_lambda_gamma_graph}--\ref{fig:CES_ternary_graph}
are shown in Tables~\ref{tab:CES_Parameters_A_With_Q_(le)k} and 
\ref{tab:CES_Parameters_B_With_Q_(le)k} and Figure~\ref{fig:CESq_Params_Graph_lek}.

<<CESq_Params_Table_lek, results='asis'>>=
print(cesParamsTableA(energyType="Q", nest="(le)k", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")
print(cesParamsTableB(energyType="Q", nest="(le)k", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")

@

<<CESq_Params_Graph_lek, fig.pos="H", fig.width=cesParameterGraphWidth, fig.height=cesParameterGraphHeight, fig.cap="CES (with energy, ($le$)$k$ nesting) model parameters. Vertical bars indicate 95\\% confidence intervals.">>=
createCESParamsGraph(energyType="Q", nest="(le)k", baseResample=baseResample)
@

The 95\% confidence intervals associated 
with ($ek$)$l$ nest columns of 
Figures~\ref{fig:CES_lambda_gamma_graph}--\ref{fig:CES_ternary_graph}
are shown in Tables~\ref{tab:CES_Parameters_A_With_Q_(ek)l} and 
\ref{tab:CES_Parameters_B_With_Q_(ek)l} and Figure~\ref{fig:CESq_Params_Graph_ekl}.

<<CESq_Params_Table_ekl, results='asis'>>=
print(cesParamsTableA(energyType="Q", nest="(ek)l", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")
print(cesParamsTableB(energyType="Q", nest="(ek)l", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")

@

<<CESq_Params_Graph_ekl, fig.pos="H", fig.width=cesParameterGraphWidth, fig.height=cesParameterGraphHeight, fig.cap="CES (with energy, ($ek$)$l$ nesting) model parameters. Vertical bars indicate 95\\% confidence intervals.">>=
createCESParamsGraph(energyType="Q", nest="(ek)l", baseResample=baseResample)
@


%++++++++++++++++++++++++++++++
\subsection{LINEX Model}
%++++++++++++++++++++++++++++++

The 95\% confidence intervals associated with Figure~\ref{fig:LINEXq_Resample_Graph}
are shown in Table~\ref{tab:LINEX_Parameters_With_Q} and Figure~\ref{fig:LINEXq_Params_Graph}.

<<LINEX_Params_Table, results='asis'>>=
print(linexParamsTable(energyType="Q", baseResample=baseResample), 
      caption.placement="top", 
      sanitize.colnames.function = identity, 
      size="\\tiny",
      table.placement="H")
@

<<LINEXq_Params_Graph, fig.pos="H", fig.width=linexParameterGraphWidth, fig.height=linexParameterGraphHeight, fig.cap="LINEX model parameters. Vertical bars indicate 95\\% confidence intervals.">>=
createLINEXParamsGraph(energyType="Q", baseResample=baseResample)
@


%% References
%%
%% Following citation commands can be used in the body text:
%%
%%  \citet{key}  ==>>  Jones et al. (1990)
%%  \citep{key}  ==>>  (Jones et al., 1990)
%%
%% Multiple citations as normal:
%% \citep{key1,key2}         ==>> (Jones et al., 1990; Smith, 1989)
%%                            or  (Jones et al., 1990, 1991)
%%                            or  (Jones et al., 1990a,b)
%% \cite{key} is the equivalent of \citet{key} in author-year mode
%%
%% Full author lists may be forced with \citet* or \citep*, e.g.
%%   \citep*{key}            ==>> (Jones, Baker, and Williams, 1990)
%%
%% Optional notes as:
%%   \citep[chap. 2]{key}    ==>> (Jones et al., 1990, chap. 2)
%%   \citep[e.g.,][]{key}    ==>> (e.g., Jones et al., 1990)
%%   \citep[see][pg. 34]{key}==>> (see Jones et al., 1990, pg. 34)
%%  (Note: in standard LaTeX, only one note is allowed, after the ref.
%%   Here, one note is like the standard, two make pre- and post-notes.)
%%
%%   \citealt{key}          ==>> Jones et al. 1990
%%   \citealt*{key}         ==>> Jones, Baker, and Williams 1990
%%   \citealp{key}          ==>> Jones et al., 1990
%%   \citealp*{key}         ==>> Jones, Baker, and Williams, 1990
%%
%% Additional citation possibilities
%%   \citeauthor{key}       ==>> Jones et al.
%%   \citeauthor*{key}      ==>> Jones, Baker, and Williams
%%   \citeyear{key}         ==>> 1990
%%   \citeyearpar{key}      ==>> (1990)
%%   \citetext{priv. comm.} ==>> (priv. comm.)
%%   \citenum{key}          ==>> 11 [non-superscripted]
%% Note: full author lists depends on whether the bib style supports them;
%%       if not, the abbreviated list is printed even when full requested.
%%
%% For names like della Robbia at the start of a sentence, use
%%   \Citet{dRob98}         ==>> Della Robbia (1998)
%%   \Citep{dRob98}         ==>> (Della Robbia, 1998)
%%   \Citeauthor{dRob98}    ==>> Della Robbia


%% References with bibTeX database:

\bibliographystyle{model2-names}
%%\bibliography{<your-bib-database>}
\bibliography{EconGrowth.bib}

%% Authors are advised to submit their bibtex database files. They are
%% requested to list a bibtex style file in the manuscript if they do
%% not want to use model2-names.bst.

%% References without bibTeX database:

% \begin{thebibliography}{00}

%% \bibitem must have one of the following forms:
%%   \bibitem[Jones et al.(1990)]{key}...
%%   \bibitem[Jones et al.(1990)Jones, Baker, and Williams]{key}...
%%   \bibitem[Jones et al., 1990]{key}...
%%   \bibitem[\protect\citeauthoryear{Jones, Baker, and Williams}{Jones
%%       et al.}{1990}]{key}...
%%   \bibitem[\protect\citeauthoryear{Jones et al.}{1990}]{key}...
%%   \bibitem[\protect\astroncite{Jones et al.}{1990}]{key}...
%%   \bibitem[\protect\citename{Jones et al., }1990]{key}...
%%   \harvarditem[Jones et al.]{Jones, Baker, and Williams}{1990}{key}...
%%

% \bibitem[ ()]{}

% \end{thebibliography}

\end{document}

%%
%% End of file `elsarticle-template-2-harv.tex'.
