%% This is file `elsarticle-template-2-harv.tex',
%%
%% Copyright 2009 Elsevier Ltd
%%
%% This file is part of the 'Elsarticle Bundle'.
%% ---------------------------------------------
%%
%% It may be distributed under the conditions of the LaTeX Project Public
%% License, either version 1.2 of this license or (at your option) any
%% later version.  The latest version of this license is in
%%    http://www.latex-project.org/lppl.txt
%% and version 1.2 or later is part of all distributions of LaTeX
%% version 1999/12/01 or later.
%%
%% The list of all files belonging to the 'Elsarticle Bundle' is
%% given in the file `manifest.txt'.
%%
%% Template article for Elsevier's document class `elsarticle'
%% with harvard style bibliographic references
%%
%% $Id: elsarticle-template-2-harv.tex 155 2009-10-08 05:35:05Z rishi $
%% $URL: http://lenova.river-valley.com/svn/elsbst/trunk/elsarticle-template-2-harv.tex $
%%
\documentclass[preprint,10pt,3p]{elsarticle}
\usepackage{setspace}
\doublespacing
%% Use the option review to obtain double line spacing
%% \documentclass[authoryear,preprint,review,12pt]{elsarticle}

%% Use the options 1p,twocolumn; 3p; 3p,twocolumn; 5p; or 5p,twocolumn
%% for a journal layout:
%% \documentclass[final,authoryear,1p,times]{elsarticle}
%% \documentclass[final,authoryear,1p,times,twocolumn]{elsarticle}
%% \documentclass[final,authoryear,3p,times]{elsarticle}
%% \documentclass[final,authoryear,3p,times,twocolumn]{elsarticle}
%% \documentclass[final,authoryear,5p,times]{elsarticle}
%% \documentclass[final,authoryear,5p,times,twocolumn]{elsarticle}

%% if you use PostScript figures in your article
%% use the graphics package for simple commands
\usepackage{graphics}
%% or use the graphicx package for more complicated commands
\usepackage{graphicx}
%% or use the epsfig package if you prefer to use the old commands
\usepackage{epsfig}

%% The amssymb package provides various useful mathematical symbols
\usepackage{amssymb}
%% The amsthm package provides extended theorem environments
\bibpunct{(}{)}{,}{a}{,}{,}

\usepackage[usenames,dvipsnames]{xcolor}
\usepackage{amsthm}
\usepackage{float}
\usepackage{epstopdf}
\usepackage{textcomp}
\usepackage{eurosym}
\usepackage{morefloats}
\usepackage{graphicx}
\usepackage{rotating}
\usepackage{caption}
\usepackage{csquotes}
\usepackage{multirow}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{natbib}
\usepackage{booktabs}
\usepackage{rotating}

\usepackage{hyperref}

%\usepackage[hidenotes]{authNote}
\usepackage[shownotes]{authNote}


%% The lineno packages adds line numbers. Start line numbering with
%% \begin{linenumbers}, end it with \end{linenumbers}. Or switch it on
%% for the whole article with \linenumbers after \end{frontmatter}.
\usepackage[right]{lineno}

%% natbib.sty is loaded by default. However, natbib options can be
%% provided with \biboptions{...} command. Following options are
%% valid:

%%   round  -  round parentheses are used (default)
%%   square -  square brackets are used   [option]
%%   curly  -  curly braces are used      {option}
%%   angle  -  angle brackets are used    <option>
%%   semicolon  -  multiple citations separated by semi-colon (default)
%%   colon  - same as semicolon, an earlier confusion
%%   comma  -  separated by comma
%%   authoryear - selects author-year citations (default)
%%   numbers-  selects numerical citations
%%   super  -  numerical citations as superscripts
%%   sort   -  sorts multiple citations according to order in ref. list
%%   sort&compress   -  like sort, but also compresses numerical citations
%%   compress - compresses without sorting
%%   longnamesfirst  -  makes first citation full author list
%%
%\biboptions{longnamesfirst,comma}

% \biboptions{}


\journal{Ecological Economics}

\begin{document}

	
\begin{frontmatter}

%% Title, authors and addresses

%% use the tnoteref command within \title for footnotes;
%% use the tnotetext command for the associated footnote;
%% use the fnref command within \author or \address for footnotes;
%% use the fntext command for the associated footnote;
%% use the corref command within \author for corresponding author footnotes;
%% use the cortext command for the associated footnote;
%% use the ead command for the email address,
%% and the form \ead[url] for the home page:
%%
%% \title{Title\tnoteref{label1}}
%% \tnotetext[label1]{}
%% \author{Name\corref{cor1}\fnref{label2}}
%% \ead{email address}
%% \ead[url]{home page}
%% \fntext[label2]{}
%% \cortext[cor1]{}
%% \address{Address\fnref{label3}}
%% \fntext[label3]{}

\title{Paper 2 Analysis}

%% use optional labels to link authors explicitly to addresses:
%% \author[label1,label2]{<author name>}
%% \address[label1]{<address>}
%% \address[label2]{<address>}

\author[label1]{Randall J. Pruim}
\ead{rpruim@calvin.edu}

\author[label2]{Matthew K. Heun}
\ead{mkh2@calvin.edu}

\address[label1]{Mathematics \& Statistics Department, Calvin College, Grand
Rapids, MI 49546, USA.}

\address[label2]{Engineering Department, Calvin College, Grand Rapids, MI 49546,
USA.}

\linenumbers

\begin{abstract}	

Need abstract here. 

\end{abstract}

\begin{keyword}
%% keywords here, in the form: keyword \sep keyword
CES function \sep Cobb-Douglas function \sep statistical precision \sep aggregate production function
\end{keyword}

\end{frontmatter}

\linenumbers

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Highlights}
\label{sec:highlights}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\emph{This will go in a separate document eventually.}

\begin{itemize}
\item Highlight 1
\item Highlight 2
\item Highlight 3
\item Highlight 4
\end{itemize}

%\linenumbers

%%%% Import Analysis chunks

<<child="../EcolEcon_2015A.Rnw", eval=TRUE>>=
@

<<include=FALSE>>=
knitr::opts_chunk$set(include = TRUE)
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Tables}
\label{sec:tables}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

These tables need to be changed to report $\rho_1$ and $\rho$ values.

<<CES_sigma_nest_aware_inner, results="asis">>=
sigma_inner_data <- 
  table_data %>% 
  filter(Model=="CES") %>% 
  select(Country, CSP, flavor, Energy, Nest, sigma_12, sigma_23, sigma_13) %>%
  plyr::rename( c("flavor" = "Factors of prod.",
                  "sigma_12" = "$\\sigma_{kl}$",
                  "sigma_23" = "$\\sigma_{le}$",
                  "sigma_13" = "$\\sigma_{ek}$"))
#
myXTable(sigma_inner_data,
         caption="Elasticities of substitution~($\\sigma$) for inner nests of CES models.",
         label=paste0("tab:", opts_current$get("label")), 
         digits=c(1,1,1,1,1,1, 3,3,3))
@


<<CES_sigma_nest_aware_outer, results="asis">>=
sigma_outer_data <- 
  table_data %>% 
  filter(Model=="CES") %>% 
  select(Country, CSP, flavor, Energy, Nest, sigma_12_3, sigma_23_1, sigma_13_2) %>%
  plyr::rename(c("flavor" = "Factors of prod.", 
                 "sigma_12_3" = "$\\sigma_{(kl)e}$",
                 "sigma_23_1" = "$\\sigma_{(le)k}$",
                 "sigma_13_2" = "$\\sigma_{(ek)l}$"))
myXTable(sigma_outer_data,
         caption="Elasticities of substitution~($\\sigma$) for outer nests of CES models.",
         label=paste0("tab:", opts_current$get("label")), 
         digits=c(1,1,1,1,1,1, 3,3,3))
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Graphs}
\label{sec:graphs}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<Historical_Plot_replay, include=TRUE, echo=FALSE, fig.pos="H", fig.align='center', fig.width=6.5, fig.height=4.0, fig.cap="Historical data.", warning=FALSE>>=
<<Historical_Plot>>
@


This graph needs to be changed to report $\rho$ values.

<<sigma_graph_3, fig.pos="H", fig.align='center', fig.width=6.5, fig.height=3.82, fig.cap="Elasticities of substitution~($\\sigma$) with factors of production on the vertical facet.">>=
breaks_labels = c(0.01, 0.1, 1, 10, 100)
p <- 
  ggplot(
    AllCoeffs %>% 
      gather(type, value, matches("sigma")) %>% 
      filter(!is.na(value)) %>% 
      filter(! type %in% c("sigma", "sigma_1")) %>%
      mutate(nest = plyr::mapvalues(nest, 
                                    from=c("kle", "lek", "ekl"), 
                                    to=c("(kl)e", "(le)k", "(ek)l")),
             Model = interaction(nest, CSP, sep = " ", drop=TRUE),
             Inputs = flavor,
             type = relevelFactor(type, rev(c("sigma_12", "sigma_23", "sigma_13", "sigma_12_3", "sigma_23_1", "sigma_13_2")))
             )
    ) + 
  geom_point(aes(x=value, 
                 y=type, 
                 shape = Model, 
                 fill=Model, 
                 size=Model
                 )
             ) + 
  facet_grid( Inputs ~ Country) + 
  scale_x_log10(limits = c(0.001,2000), breaks=breaks_labels, labels=breaks_labels) +
  xlab("") +
  geom_vline(xintercept = 1, color="gray50", size=0.2) +
  ylab("") +
  scale_y_discrete(labels = c(
    sigma_12 = expression(sigma[kl]),
    sigma_23 = expression(sigma[le]),
    sigma_13 = expression(sigma[ek]),
    sigma_12_3 = expression(sigma["(kl)"*e]),
    sigma_23_1 = expression(sigma["(le)"*k]),
    sigma_13_2 = expression(sigma["(ek)"*l]))
    ) +
  xy_theme() +
  theme(axis.text.y = element_text(size=12))

model_points_style_quad(p)
@


<<resample_graph_sigma1_delta1, fig.pos="H", fig.align='center', fig.width=6.5, fig.height=3.5, fig.cap="$\\sigma_{(kl)}$ and $\\delta_1$ values for resample models that adhere to the cost share theorem, include energy, use quality-adjusted factors of production, and employ the ($kl$)$e$ nesting.">>=
standardScatterPlot(data=resampleCoeffsCES, mapping=aes(delta_1, sigma_1), 
                    facet_formula=~Country, alpha=0.1) +
    coord_trans(y="sigma2") +
    scale_x_continuous(breaks=c(0, 0.5, 1.0, 2.0), limits=c(0,1)) +
    scale_y_continuous(breaks=c(0, 0.5, 1.0, 2.0), limits=c(0, 1e6)) +
    labs(x=expression(delta[1]), y=expression(sigma[kl]))
@


<<resample_graph_sigma_delta, fig.pos="H", fig.align='center', fig.width=6.5, fig.height=3.5, fig.cap="$\\sigma_{(kl)e}$ and $\\delta$ values for resample models that adhere to the cost share theorem, include energy, use quality-adjusted factors of production, and employ the ($kl$)$e$ nesting.">>=
standardScatterPlot(data=resampleCoeffsCES, mapping=aes(delta, sigma), 
                    facet_formula=~Country, alpha=0.1) +
    coord_trans(y="sigma2") +
    scale_x_continuous(breaks=c(0, 0.5, 1.0, 2.0), limits=c(0,1)) +
    scale_y_continuous(breaks=c(0, 0.5, 1.0, 2.0), limits=c(0, 1e6)) +
    labs(x=expression(delta), y=expression(sigma["(kl)"*e]))
@






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Conclusions}
\label{sec:conclusion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Acknowledgements}
\label{sec:acknowledgements}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%References
%%
%% Following citation commands can be used in the body text:
%%
%%  \citet{key}  ==>>  Jones et al. (1990)
%%  \citep{key}  ==>>  (Jones et al., 1990)
%%
%% Multiple citations as normal:
%% \citep{key1,key2}         ==>> (Jones et al., 1990; Smith, 1989)
%%                            or  (Jones et al., 1990, 1991)
%%                            or  (Jones et al., 1990a,b)
%% \cite{key} is the equivalent of \citet{key} in author-year mode
%%
%% Full author lists may be forced with \citet* or \citep*, e.g.
%%   \citep*{key}            ==>> (Jones, Baker, and Williams, 1990)
%%
%% Optional notes as:
%%   \citep[chap. 2]{key}    ==>> (Jones et al., 1990, chap. 2)
%%   \citep[e.g.,][]{key}    ==>> (e.g., Jones et al., 1990)
%%   \citep[see][pg. 34]{key}==>> (see Jones et al., 1990, pg. 34)
%%  (Note: in standard LaTeX, only one note is allowed, after the ref.
%%   Here, one note is like the standard, two make pre- and post-notes.)
%%
%%   \citealt{key}          ==>> Jones et al. 1990
%%   \citealt*{key}         ==>> Jones, Baker, and Williams 1990
%%   \citealp{key}          ==>> Jones et al., 1990
%%   \citealp*{key}         ==>> Jones, Baker, and Williams, 1990
%%
%% Additional citation possibilities
%%   \citeauthor{key}       ==>> Jones et al.
%%   \citeauthor*{key}      ==>> Jones, Baker, and Williams
%%   \citeyear{key}         ==>> 1990
%%   \citeyearpar{key}      ==>> (1990)
%%   \citetext{priv. comm.} ==>> (priv. comm.)
%%   \citenum{key}          ==>> 11 [non-superscripted]
%% Note: full author lists depends on whether the bib style supports them;
%%       if not, the abbreviated list is printed even when full requested.
%%
%% For names like della Robbia at the start of a sentence, use
%%   \Citet{dRob98}         ==>> Della Robbia (1998)
%%   \Citep{dRob98}         ==>> (Della Robbia, 1998)
%%   \Citeauthor{dRob98}    ==>> Della Robbia


%% References with bibTeX database:

% \bibliographystyle{agsm}
% \bibliography{references}


%% The Appendices part is started with the command \appendix;
%% appendix sections are then done as normal sections


\newpage
\section*{Author Notes}

\authNotes

\end{document}

%%
%% End of file `elsarticle-template-2-harv.tex'.s
