% This article has been prepared for publication in Energy Economics in RStudio with knitr.
% According to http://www.elsevier.com/author-schemas/the-elsarticle-latex-document-class, we should be using the
% elsarticle.cls file.
% According to http://cdn.elsevier.com/assets/pdf_file/0006/109392/journal_refstyles.pdf, we should be using
% elsarticle-template-2-harv.tex as the template for the text.
% Furthermore, we should be using model2-names.bst for the bibliographic references.
% The approach here is to load the frontmatter and backmatter from elsarticle-template-2-harv.tex
% both ahead of and behind the text for our paper.
% -- Matthew Kuperus Heun, 2013-01-18

%% This is file `elsarticle-template-2-harv.tex',
%%
%% Copyright 2009 Elsevier Ltd
%%
%% This file is part of the 'Elsarticle  Bundle'.
%% ---------------------------------------------
%%
%% It may be distributed under the conditions of the LaTeX Project Public
%% License, either version 1.2 of this license or (at your option) any
%% later version.  The latest version of this license is in
%%    http://www.latex-project.org/lppl.txt
%% and version 1.2 or later is part of all distributions of LaTeX
%% version 1999/12/01 or later.
%%
%% The list of all files belonging to the 'Elsarticle Bundle' is
%% given in the file `manifest.txt'.
%%
%% Template article for Elsevier's document class `elsarticle'
%% with harvard style bibliographic references
%%
%% $Id: elsarticle-template-2-harv.tex 155 2009-10-08 05:35:05Z rishi $
%% $URL: http://lenova.river-valley.com/svn/elsbst/trunk/elsarticle-template-2-harv.tex $
%%
\documentclass[preprint,authoryear,12pt]{elsarticle}

%% Use the option review to obtain double line spacing
%% \documentclass[authoryear,preprint,review,12pt]{elsarticle}

%% Use the options 1p,twocolumn; 3p; 3p,twocolumn; 5p; or 5p,twocolumn
%% for a journal layout:
%% \documentclass[final,authoryear,1p,times]{elsarticle}
%% \documentclass[final,authoryear,1p,times,twocolumn]{elsarticle}
%% \documentclass[final,authoryear,3p,times]{elsarticle}
%% \documentclass[final,authoryear,3p,times,twocolumn]{elsarticle}
%% \documentclass[final,authoryear,5p,times]{elsarticle}
%% \documentclass[final,authoryear,5p,times,twocolumn]{elsarticle}

%% if you use PostScript figures in your article
%% use the graphics package for simple commands
%% \usepackage{graphics}
%% or use the graphicx package for more complicated commands
%% \usepackage{graphicx}
%% or use the epsfig package if you prefer to use the old commands
%% \usepackage{epsfig}

%% The amssymb package provides various useful mathematical symbols
\usepackage{amssymb}
%% The amsthm package provides extended theorem environments
%% \usepackage{amsthm}

\usepackage{wrapfig}    % Allows wrapping of text around figures
\usepackage{soul}       % Provides strikethrough text
\usepackage{float}      % Allows precise positioning of tables and figures within the text
\usepackage{amsmath}    % Allows \begin{equation*} \end{equation*} for unnumbered equations
\usepackage{multirow}   % To create multirow tables
\usepackage{hyperref}   % To create hyperlinks in the paper
\usepackage{microtype}  % produces hanging punctuation and beautiful type
\usepackage{booktabs}   % produces beautiful tables


% From http://economics.utoronto.ca/osborne/latex/BIBTEX.HTM
\newcommand{\citeapos}[1]{\citeauthor{#1}'s (\citeyear{#1})} % Posessive citations. 

%% The lineno packages adds line numbers. Start line numbering with
%% \begin{linenumbers}, end it with \end{linenumbers}. Or switch it on
%% for the whole article with \linenumbers after \end{frontmatter}.
%% \usepackage{lineno}

%% natbib.sty is loaded by default. However, natbib options can be
%% provided with \biboptions{...} command. Following options are
%% valid:

%%   round  -  round parentheses are used (default)
%%   square -  square brackets are used   [option]
%%   curly  -  curly braces are used      {option}
%%   angle  -  angle brackets are used    <option>
%%   semicolon  -  multiple citations separated by semi-colon (default)
%%   colon  - same as semicolon, an earlier confusion
%%   comma  -  separated by comma
%%   authoryear - selects author-year citations (default)
%%   numbers-  selects numerical citations
%%   super  -  numerical citations as superscripts
%%   sort   -  sorts multiple citations according to order in ref. list
%%   sort&compress   -  like sort, but also compresses numerical citations
%%   compress - compresses without sorting
%%   longnamesfirst  -  makes first citation full author list
%%
%% \biboptions{longnamesfirst,comma}

% \biboptions{}

\usepackage[shownotes]{authNote}

\journal{Energy Economics}

\begin{document}

<<setup, echo=FALSE, message=FALSE, eval=TRUE>>=
require(EconModels)
require(EconData)
require(lattice)
require(latticeExtra)
require(ggplot2)
require(car)
require(mosaic)
require(xtable)
require(nlmrt)
require(dplyr)
# Provides access to data melting. 
# See http://cran.r-project.org/web/packages/reshape2/reshape2.pdf
require(reshape2) 
# tikz allows use of LaTeX formatting and font in graphs. 
# Allows for a consistent look across the paper.
# See http://r-forge.r-project.org/R/?group_id=440 for instructions 
# on installing tikzDevice.
# require(tikzDevice) 
trellis.par.set(theme=theme.mosaic())
options(width=75)
options(show.signif.stars=TRUE)
require(knitr)

opts_chunk$set(
  # ********************************************************
  eval=TRUE,
  # ********************************************************
  # tikz allows LaTeX code in graphical output. 
  # E.g., "$y$" for a variable name in the legend for a graph.  
  # dev='tikz',
  tidy=FALSE,
  comment=NA,
  # Tells whether to cache output from chunks are saved. Cacheing saves time. 
  # However, references to LaTeX tables DO NOT WORK if cacheing is turned on.
  cache=FALSE,
  warning=FALSE,  #Tells whether to show warnings in the output.
  # Turns off messages for all chunks. 
  # Set TRUE on an individual chunk to see it.
  message=FALSE, 
  # Tells whether to echo code for all chunks. 
  # Set TRUE on an individual chunk to see its code.
  echo=FALSE     
)
@

<<constants, include=FALSE, eval=TRUE>>=
# Graph Heights
maxHeight <- 8.5 # Inches
ninePanelScatterGraphHeight <- maxHeight # Inches

# Graph Widths
maxWidth <- 6.5 # Inches
fourPanelScatterGraphWidth <- maxWidth # Inches

presentationGraph1RowHeight <- 2.8 # Inches
presentationGraph2ColWidth <- 2 # Inches
presentationGraph1ColWidth <- 2*presentationGraph2ColWidth
h_param_graph <- 2.07 # Inches for a single panel
h_param_axis <- 0.86 # Inches (also includes whatever margin is applied)
# sfParameterGraphHeight <- h_param_graph + h_param_axis
cdParameterGraphHeight <- 2*h_param_graph + h_param_axis
cesParameterGraphHeight <- 3*h_param_graph + h_param_axis
linexParameterGraphHeight <- h_param_graph + h_param_axis
sfParameterGraphWidth <- maxWidth
cdParameterGraphWidth <- maxWidth
cesParameterGraphWidth <- maxWidth
linexParameterGraphWidth <- maxWidth
# Other graph parameters that apply to all graphs
scaleTextSize <- 0.8  # Multiple of normal size
scaleTickSize <- -0.5 # 50% of normal size and pointing INWARD!

spaghettiGraphLevel <- 1.0 # Spaghetti graph bands will encompass 95% of the data.
@

<<data>>=
# Load historical data
historicalData <- Calvin # From the EconData package

# The working directory is set to the directory that contains this file.
# To reach the post-processed data, we need to move 
# up two levels and into the data_postprocessed directory.
# So, in each of the loadPostProcessedData calls below, we use
# dir = "../../data_postprocessed".
pp_path <- file.path("..", "..", "data_postprocessed")

# Load coefficients from all models in one large data frame
coeffs_df <- loadPostProcessedData(Source = "Calvin", kind = "coeffs", dir = pp_path)
# Load fitted data from all models in one large data frame
fitted_df <- loadPostProcessedData(Source = "Calvin", kind = "fitted", dir = pp_path)
# Load the original models.
oModels <- loadPostProcessedData(Source = "Calvin", kind = "models", dir = pp_path)
@

% These equations are used in several locations in the paper.
% By defining commands for them, we ensure consistent appearance
% of the equations when they are used.

% Add an argument if you want a label. Example: "\label{eq:CES}"
\newcommand{\ceskl}[1]{\begin{equation} #1
  y = \gamma \: A \: \left[\delta_1 k^{-\rho_1} 
      + (1-\delta_1)l^{-\rho_1} \right]^{-1/\rho_1}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}}

\newcommand{\ceskle}[1]{\begin{equation} #1
  y = \gamma \: A \: \left\{\delta \left[\delta_1 k^{-\rho_1} 
      + (1-\delta_1)l^{-\rho_1} \right]^{\rho/\rho_1} 
      + (1-\delta) e^{-\rho} \right\}^{-1/\rho}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}
}

\newcommand{\ceslek}[1]{\begin{equation} #1
  y = \gamma \: A \: \left\{\delta \left[\delta_1 l^{-\rho_1} 
      + (1-\delta_1) e^{-\rho_1} \right]^{\rho/\rho_1} 
      + (1-\delta) k^{-\rho} \right\}^{-1/\rho}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}
}

\newcommand{\cesekl}[1]{\begin{equation} #1
  y = \gamma \: A \: \left\{\delta \left[\delta_1 e^{-\rho_1} 
      + (1-\delta_1) k^{-\rho_1} \right]^{\rho/\rho_1} 
      + (1-\delta) l^{-\rho} \right\}^{-1/\rho}; 
      A = \mathrm{e}^{\lambda (t-t_0)}
\end{equation}
}


\begin{frontmatter}

%% Title, authors and addresses

%% use the tnoteref command within \title for footnotes;
%% use the tnotetext command for the associated footnote;
%% use the fnref command within \author or \address for footnotes;
%% use the fntext command for the associated footnote;
%% use the corref command within \author for corresponding author footnotes;
%% use the cortext command for the associated footnote;
%% use the ead command for the email address,
%% and the form \ead[url] for the home page:
%%
%% \title{Title\tnoteref{label1}}
%% \tnotetext[label1]{}
%% \author{Name\corref{cor1}\fnref{label2}}
%% \ead{email address}
%% \ead[url]{home page}
%% \fntext[label2]{}
%% \cortext[cor1]{}
%% \address{Address\fnref{label3}}
%% \fntext[label3]{}

\title{An Empirical Analysis of the Role of Energy in Economic Growth}

%% use optional labels to link authors explicitly to addresses:
%% \author[label1,label2]{<author name>}
%% \address[label1]{<address>}
%% \address[label2]{<address>}

\author[CalvinEngr]{Matthew Kuperus Heun\corref{cor1}}
\ead{mkh2@calvin.edu}
\author[Stellenbosch]{Martin de Wit}
\author[CalvinMath]{Randall J. Pruim}
\author[CalvinEngr]{Caleb Reese}
\author[CalvinEngr]{Lucas Timmer}

\cortext[cor1]{Corresponding author}
\address[CalvinEngr]{Engineering Department, Calvin College, Grand Rapids, MI 49546, USA}
\address[Stellenbosch]{Faculty of Economics and Management Sciences, School of Public Leadership, Stellenbosch University, P.O. Box 610, Bellville 7535, South Africa}
\address[CalvinMath]{Mathematics \& Statistics Department, Calvin College, Grand Rapids, MI 49546, USA}

\begin{abstract}
%% Text of abstract
**** Add abstract ****
\end{abstract}

\begin{keyword}
%% keywords here, in the form: keyword \sep keyword
economic growth \sep energy \sep Cobb-Douglas \sep CES \sep LINEX
%% MSC codes here, in the form: \MSC code \sep code
%% or \MSC[2008] code \sep code (2000 is the default)
\end{keyword}

\end{frontmatter}

% \linenumbers
%% main text

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction} 
\label{sec:Introduction}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**** Additional references requested by Martin. Incorporate into paper? ****

\citet{Lindenberger:2011dx}

\citet{Stresing:2008cq}

The availability of adequate energy at affordable prices 
has become an important strategic issue in recent years.
Despite a slowdown in economic growth worldwide, 
longer-term trends in energy use remain strongly upwards, 
as the dynamics of energy markets are increasingly determined by emerging economies, 
notably China, India, and the Middle East \citep{IEA:2012ty}. 
A large body of literature points to the fact that 
economic growth and energy consumption are closely correlated 
for a diverse set of countries such as 
the United States \citep{Stern:2000wq, Cleveland:1984p5055}, 
India \citep{Paul:2004jl}, 
China \citep{Wang:2011fe}, 
South Africa \citep{Menyah:2010hl, Odhiambo:2009hj}, and 
sixteen Asian countries \citep{Lee:2008dm}
to name a few, 
although the causal relationship from energy consumption 
to economic growth remains controversial \citep{Chen:2012fs, Ozturk:2010kb, Stern:2013aa}. 
\citet[p. 347]{Ozturk:2010kb} in a survey of the literature on the topic, 
concluded that there is 
``\dots no consensus neither on the existence nor on the direction of 
causality between these variables in the literature,'' 
but does point out that ``\dots causality is running from 
electricity consumption to economic growth 
in the most of these studies [surveyed].''
\citet{Stern:2013aa} found similar results,
noting that the direction of causality may change over time.

Many who accept that energy use is closely correlated with
economic performance, regardless of the direction of causality,
express concern regarding the negative effects of 
rising energy prices and fossil fuel depletion 
on current and future economic growth.
\citet{Benes:2012tm}, incorporating views on both
geological physical constraints and 
technological solutions to oil production, 
suggest a near doubling of the real price of over the next decade.  
\citet{Kumhof:2012ua} point out that 
significant impacts on GDP growth could occur
for larger oil supply shocks, 
assuming production functions where oil plays a prominent role 
and reduced possibilities for substitution away from oil.  
\citet{Nel:2010fv} argue for the 
``\dots{}vital importance of energy security\dots'' 
on the basis of an economic growth model with explicit 
energy-based formulation.  
\citet{Hamilton:2013vc} argues that 
``[c]oping with a final peak in world oil production\dots%
[will] have much in common with previous historical episodes that resulted from 
temporary geopolitical conflict, 
being associated with significant declines in employment and output. 
If the future decades look like the last 5 years, we are in for a rough time.'' 

The current trends in energy production and consumption and 
the possible dire impacts on the world economy 
as argued by the above-mentioned scholars 
raise the question of
whether and how to include appropriate energy indicators 
in economic growth modeling.  
Neoclassical economic growth theory attributes output~($Y$) to factors of production:
capital stock~($K$) and labor~($L$). 
The Cobb-Douglas production function 
is the canonical representation of indexed economic output ($y$) as a function of indexed 
labor~($l$), indexed capital stock~($k$), and an additional exogenous, time-dependent 
term.
This production function can be expressed as
%
\begin{equation} \label{eq:CD}
  y = \theta \mathrm{e}^{\lambda(t-t_0)} k^\alpha l^\beta \;,
\end{equation}
%
\noindent where 
$y \equiv Y/Y_{0}$,
$\theta$ is a scale parameter,
e is the base of the natural logarithm, 
$\lambda$ is represents the pace of technological progress,
$t$ (time) is measured in years,
$k \equiv K/K_{0}$, 
$l \equiv L/L_{0}$, 
$Y$ is represented by GDP, 
$K$ is expressed in currency units, 
$L$ is expressed in workers or work-hours/year, and
0 subscripts indicate values at an initial year.
The parameters $\alpha$ and $\beta$ indicate the relative roles 
of capital and labor in the economy.
Typically, the constraint $\alpha + \beta = 1$ is assumed, 
indicating constant returns to scale.%
  \footnote{Dimensionless, indexed quantities are represented by 
  lower-case symbols 
  ($y$, $k$, $l$, and $q$), and dimensional 
  quantities are represented by upper-case symbols 
  ($Y$, $K$, $L$, and $Q$). 
  Model parameters are represented by Greek letters
  ($\alpha$, $\beta$, $\lambda$, $\theta$).} 

Neoclassical economic growth theory as expressed in the Cobb-Douglas production 
function makes no attempt, beyond growth in capital~($k$) and labor~($l$), 
to describe the mechanisms that affect economic growth, 
nor does it attempt, beyond different fitting parameters,
to describe how such phenomena as
slowdowns, speedups, and improvements of the education of the labor force
might vary from one economy to the next. 

As shown in Equation~\ref{eq:CD} above, neoclassical economic theory does not 
include an explicit term for the role of energy in economic growth. 
However, \citet{Bashmakov:2007ek}, \citet{Hamilton:2009ui}, \citet{Murphy:2011jh}, 
\citet{Benes:2012tm}, \citet{Kumhof:2012ua}, \citet{Ayres:2013aa} and others indicate that the 
importance of energy for economic growth may far outweigh its cost share in the 
economy. 
That neoclassical economic growth theory ignores energy is, therefore, 
cause for concern, and inquiry into the proper approach for including energy 
as a factor of production in economic growth modeling is both relevant and important.

Some energy economists augment economic growth models by including energy as an 
additional (or the only) factor of production. 
However, there is little agreement on how this should be done. 
Neither the mathematical form of the energy-augmented 
production function nor the quantification%
  \footnote{
  Various energy quantifications have been used in economic growth modeling: 
  thermal energy (primary and final), 
  exergy (primary and final), and useful work.
  }
of energy is consistent in the 
literature. 
Furthermore, there has been little empirical work assessing the predictive ability 
of various energy-augmented production functions for different types of economies. 
And, very few studies of the importance of energy in economic growth include 
rigorous statistical assessments of energy-related fitting parameters. 
This paper contributes to the literature on the role of energy in economic growth
by applying statistically rigorous 
methods along two coordinates of analysis: 
form of the energy augmented production function 
and type of economy.

The remainder of this paper is organized as follows. 
Section~\ref{sec:lit_review} provides a necessarily brief overview of relevant literature.
Section~\ref{sec:Coordinates} discusses the coordinates of analysis for the present study. 
Section~\ref{sec:Sources_of_Data} details sources of data and calculations to 
generate time series for economic output ($y$) and factors of production ($k$, $l$, and $q$). 
The procedures for and results from parameter estimation for the various production functions 
are discussed in Section~\ref{sec:Parameter_Estimation}. 
Section~\ref{sec:Discussion_of_Results} discusses implications of the parameter estimation 
results, and Section~\ref{sec:Conclusion} concludes.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Literature Review} 
\label{sec:lit_review}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\citet[p.~26]{Stern:2011bq} provides an overview of approaches to including energy 
in ecological economic and resource economic models of growth.  
\citeauthor{Stern:2011bq} points out that 
energy is seen as the \emph{central driver of growth} 
in ecological economic (including biophysical economic) models
and that energy \emph{is included in} resource economic models, 
but \emph{remains isolated} within the sub-discipline.  
To break through this theoretical impasse, 
Stern proposes a synthesized Constant Elasticity of Substitution (CES) 
production function 
where the constraints or abundance of energy 
determines whether to include energy explicitly 
as a factor of production.  
On the basis of this model, 
\citet[p. 45]{Stern:2011bq} points out that 
energy availability plays
``\dots{}a key role in enabling growth,''
despite evidence of decreasing energy consumed per unit of output.  
He concludes, based on theory and time-series results, 
that including energy in the production function is warranted, 
and that further clarification is needed 
on the role of energy in economic growth.  

The inclusion of energy as a factor of production 
in Cobb-Douglas and CES production functions 
is generally accepted by most 
resource and energy economists
\citep{Smulders:2003wc, vanderZwaan:2002wn, Kemfert:1998vd}.
Researchers interested in explaining long-term economic growth 
and possible constraints on growth 
have started to include energy as an explicit factor of production
\citep{Froling:2009vo, Tahvonen:2001tz}.  
An alternative approach, attempting to be 
``\dots more consistent with physical laws \dots'' \citep{Ayres:2001tx}
and classified by \citet{Stern:2011bq} as an ecological economic model of growth, 
is the LINEX model, 
wherein energy is the only factor of production,
and capital~($k$), labor~($l$), and energy~($q$)
combine to provide efficiencies that augment energy.
Technological change is manifest as increased efficiency:
more useful work done per joule of exergy \citep{Ayres:2005kn}.
There is no Solow-style term ($\mathrm{e}^{\lambda t}$) for technological change.

Unsatisfactorily, the choice of a production function 
and the parameters used to populate these functions 
affects results significantly.
This situation leaves far too much latitude 
for misuse of model specifications 
and selection of parameters 
to support certain theories (rather than empirically testing the theories
and parameters \emph{before} they are employed).  
For example, \citet{Lecca:2011kr} pointed out that 
the modellers' choice for the structure of a production function 
reflects his or her assumptions about
the elasticities among inputs, and 
``\dots the point at which energy enters the [nested CES] production function 
has a significant impact on CGE [computable general equilibrium] model results.''
\citet{Duffy:2000ty} rejected the Cobb-Douglas production function altogether, 
finding that capital and labour are more substitutable 
in richer countries and less substitutable in poorer countries 
than Cobb-Douglas implies.  
However, \citet{Miller:2008vd} points to the 
``\dots reasonably accurate long-term economic forecasts,'' 
achieved with the use of Cobb-Douglas production functions in economic models.  
\citet{Shen:2013vp} provide a recent example 
wherein empirical analysis on the estimated substitution elasticities 
is performed before choosing any particular 
nested CES production function structure. 
As a result, \citeauthor{Shen:2013vp} propose an atypical structure 
for the Chinese economy. **** More detail here about nesting? ****  
Both the choice of production function structure 
and the value of the model parameters 
drive model results, and empirical and statistical testing 
of such approaches is prudent, but rarely conducted.

These are not idle academic debates. 
Macroeconomic growth models are used often to inform economic policy,
and the paths of economies worldwide are determined by
such policy choices. 
Therefore, we agree with those who have serious concerns 
about the reliability of the results from economic growth models \citep{Lecca:2011kr}. 
We understand, however, 
that macroeconomic policymaking is needed 
and is increasingly informed by integrated energy-economic models, 
in a world where energy constraints are possible 
\citep{Beckman:2011gb, Benes:2012tm, Nel:2010fv}.  
We support the call from \citet{Shen:2013vp} that both
the structure of the production function 
and the parameters used to populate this function
need empirical testing. 
Building on the argument of \citet{Stern:2011bq} 
that energy may or may not be required in production functions 
depending on its abundance or scarcity, 
we will further argue in this paper that different types of countries 
may need different factors of production to explain their respective growth paths.  
This further leaves open the possibility for 
different explanations of growth in various countries
at different stages of their development, 
a central point of long-wave economic growth modeling 
\citep{Froling:2009vo, Jones:2001wn, Galor:2000up}.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Coordinates of Analysis} 
\label{sec:Coordinates}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

This section describes our two coordinates of analysis.


%++++++++++++++++++++++++++++++
\subsection{Mathematical Forms of the Energy-augmented Production Function} 
\label{sec:Prod_Func_Forms}
%++++++++++++++++++++++++++++++

In this paper, we assess three prominent energy-augmented production functions 
that appear in the literature: 
Cobb-Douglas (CD), 
Constant Elasticity of Substitution (CES), and 
LINear EXponential (LINEX). 
The following subsections describe each.


%------------------------------
\subsubsection{Cobb-Douglas (CD) Production Function} 
\label{sec:CDe}
%------------------------------

The capital-labor Cobb-Douglas production function shown in Equation~\ref{eq:CD}
can be augmented to include an energy term:
%
\begin{equation} \label{eq:CDe}
  y = \theta \mathrm{e}^{\lambda(t-t_0)}  k^\alpha l^\beta e^\gamma \;,
\end{equation}
%
where $e \equiv E/E_0$, and $E$ is in units of energy per time, typically TJ/year. 
The energy-augmented Cobb-Douglas production function 
is often assumed to have constant returns to scale for the three factors 
of production: $\alpha + \beta + \gamma = 1$.


%------------------------------
\subsubsection{Constant Elasticity of Substitution Production Function (CES)} 
\label{sec:CES}
%------------------------------

Other energy economists use an energy-augmented 
Constant Elasticity of Substitution (CES) production function to 
describe economic growth. The \texttt{R} \citep{R} package 
\texttt{micEconCES} \citep{Henningsen:2011td} estimates CES production 
functions of the following forms (among others):
%
\ceskl{\label{eq:CES}}
%
\ceskle{\label{eq:CESkle}}
%
\noindent Equation~\ref{eq:CES} is a CES production function with 
capital stock ($k$) and labor ($l$) factors of production. 
Equation~\ref{eq:CESkle} augments Equation~\ref{eq:CES} with energy 
using a ($kl$) + ($e$) nesting structure, as is typical in the literature. 
Equation~\ref{eq:CES} is a degenerate form of Equation~\ref{eq:CESkle} 
where $\delta \rightarrow 1$. 

$\gamma$ is a scale factor.
The fitting parameters $\rho_1$ and $\rho$ indicate elasticities 
of substitution ($\sigma_1$ and $\sigma$).
The elasticity of substitution 
between capital ($k$) and labor ($l$) is given by 
$\sigma_1 = \frac{1}{1+\rho_1}$, and
the elasticity of substitution between ($kl$) and ($e$) is given by 
$\sigma = \frac{1}{1+\rho}$. 
As $\rho_1 \rightarrow 0$, $\sigma_1 \rightarrow 1$,
and the embedded CES production function for $k$ and $l$ degenerates 
to the Cobb-Douglas production function.
Similarly, as $\rho \rightarrow 0$, $\sigma \rightarrow 1$,
and the CES production function for $(kl)$ and $(e)$ degenerates 
to the Cobb-Douglas production function.
As $\sigma \rightarrow \infty$ ($\rho \rightarrow -1$), 
($kl$) and ($e$) are perfect substitutes. 
As $\sigma \rightarrow 0$ ($\rho \rightarrow \infty$), 
($kl$) and ($e$) are perfect complements: 
no substitution is possible. Similarly, 
as $\sigma_1 \rightarrow 0$ ($\rho_1 \rightarrow \infty$),
$k$ and $l$ are perfect complements.
$\delta_1$ describes the relative importance of capital ($k$)
and labor ($l$), and
$\delta$ describes the importance of ($kl$) relative to ($e$).

Constraints on the fitting parameters include 
$\delta_1 \in [0,1]$,
$\delta \in [0,1]$,
$\rho_1 \in [-1,0) \cup (0,\infty)$, and
$\rho \in [-1,0) \cup (0,\infty)$. 

Two other nestings of the factors of production ($k$, $l$, and $e$)
are possible with the CES model.
%
\ceslek{\label{eq:CESlek}}
%
\cesekl{\label{eq:CESekl}}
%
\noindent Note that the parameters $\rho$ ($\sigma$) and $\delta$ have different
meanings depending upon the nesting of the factors of production.


%------------------------------
\subsubsection{LINEX Production Function} 
\label{sec:LINEX}
%------------------------------

A third production function, the LINear EXponential (LINEX) function
%
\begin{equation} \label{eq:LINEX}
  y = \theta \; \mathrm{e}^{a_0\left[2 \left(1 - \frac{1}{\rho_k} \right) 
    + c_t \left(\vphantom{\frac{1}{\rho_k}}\rho_l - 1 \right)\right]} \; e \;,
\end{equation}
%
was derived from thermodynamic considerations
\citep{Kummel:1980wx,Kummel:1982vy,Kummel:1985vz,Kummel:1989tf,Kummel:2002tx,Kummel:2010vz}. 
In contrast to both the Cobb-Douglas model (Equations~\ref{eq:CD} and 
\ref{eq:CDe}) and the CES model (Equations~\ref{eq:CES}--\ref{eq:CESekl}), 
the LINEX model (Equation~\ref{eq:LINEX}) does not include a generic, 
time-dependent augmentation term ($A$).
The LINEX models assumes energy ($e$) is the only factor of production.

The LINEX model does, however, include terms that represent
efficiencies among capital, labor, and energy, in the form of 
the ratios $\rho_k$ and $\rho_l$ which are defined by\footnote{The notation
for the LINEX model breaks from the conventions used in the Cobb-Douglas and CES
models:  $a_0$ and $c_t$ are parameters and $\rho_k$ and $\rho_l$ are not.}
%
\begin{equation} \label{eq:rho_k}
  \rho_k \equiv \frac{k}{(1/2)(l+e)}
\end{equation}
%
and
%
\begin{equation} \label{eq:rho_l}
  \rho_l \equiv \frac{l}{e}
\end{equation}
%
and represent 
%
(\ref{eq:rho_k}) capital stock increase relative to the average of labor and energy and 
(\ref{eq:rho_l}) labor increase relative to energy.
The effect of energy ($e$) on production is enhanced if either
%
\begin{itemize}
\item{capital stock ($k$) has increased more than the average 
      of labor ($l$) and energy ($e$), i.e. if $\rho_k >$ 1, or}
\item{labor ($l$) has increased more than energy ($e$), i.e. if $\rho_l >$ 1.}
\end{itemize}
%
An economy that increases 
capital stock ($k$) and labor ($l$) at the same rate as energy will have
capital and labor efficiency ratios ($\rho_k$ and $\rho_l$, respectively) of unity.
In that case, economic output ($y$) increases at the same rate as energy consumption ($e$).
According to the LINEX model, an economy that increases 
capital stock ($k$) without a commensurate increase in labor ($l$) 
and energy ($e$) will experience an increase in output ($y$) in excess 
of its increase of energy consumption ($e$), because
%
\begin{equation*}
  \mathrm{e}^{a_0\left[2 \left(1 - \frac{1}{\rho_k} \right) 
      + c_t \left(\vphantom{\frac{1}{\rho_k}}\rho_l - 1 \right)\right]}
  	> 1.
\end{equation*}
%
Similarly, an economy benefits by increasing labor ($l$) 
without a commensurate increase in energy ($e$). 
Thus, $\rho_k$ is an 
efficiency of using additional labor and energy to make 
additional capital stock available to the economy, 
and $\rho_l$ is an efficiency of using additional energy to make 
additional labor available to the economy. 
Increases in $\rho_k$ and $\rho_l$ provide upward pressure on economic output ($y$),
as the only factor of production ($e$) is used more efficiently.

The parameter $a_0$ represents the overall importance of efficiencies $\rho_k$ and $\rho_l$, 
and the parameter $c_t$ represents the relative importance 
of the labor efficiency term ($\rho_l$) compared to the capital stock efficiency term ($\rho_k$). 
Both $a_0$ and $c_t$ are assumed constant with respect to time. 


%++++++++++++++++++++++++++++++
\subsection{Economy Types} 
\label{sec:Economy_Types}
%++++++++++++++++++++++++++++++

In the energy-economic growth literature, the focus is 
almost exclusively on developed economies from North America 
and Europe. 
Examples include \citet{Kummel:1980wx} applying 
LINEX to describe the West German economy, 
\citet{Serrenho:2010vq} applying Cobb-Douglas variants to EU-15 countries, 
\citet{VanderWerf:2008tc} applying CES nesting variants 
to the 12 OECD countries, 
\citet{Lecca:2011kr} applying CES nesting variants to the Scottish economy, 
\citet{Stern:2012ey} applying CES to describe the Swedish economy, 
and \citet{Warr:2012cg} using LINEX and Cobb-Douglas to describe the Austrian, 
American, British, and Japanese economies.

But, the near-exclusive focus on developed economies closes off 
the possibility of discovering any role that energy plays 
in the economic development process. 
To gain insights from different countries 
across different stages of development, 
we present a comparative analysis among representatives of
the World Bank's main categories of countries, 
namely Developed Countries (DCs), 
Newly Industrialized Countries (NICs), 
OPEC countries, and 
Least Developed Countries (LDCs). 
Table~\ref{tab:Economy_Examples} shows our example countries.

\begin{table} \caption{Example economies and years of evaluation.} \label{tab:Economy_Examples} 
  \begin{center}
    \begin{tabular}{r c c l l} 
      \toprule
      \multirow{3}{*}{Developed} & \includegraphics[height=0.11in]{flag/flag_US.png} & US & USA & \multirow{3}{*}{1980--2011}\\
                                 & \includegraphics[height=0.11in]{flag/flag_UK.png} & UK & United Kingdom & \\
                                 & \includegraphics[height=0.11in]{flag/flag_JP.png} & JP & Japan          & \\
      \midrule
      \multirow{2}{*}{NICs}      & \includegraphics[height=0.11in]{flag/flag_CN.png} & CN & China & \multirow{2}{*}{1991--2011}        \\
                                 & \includegraphics[height=0.11in]{flag/flag_ZA.png} & ZA & South Africa & \\
      \midrule
      \multirow{2}{*}{OPEC}      & \includegraphics[height=0.11in]{flag/flag_SA.png} & SA & Saudi Arabia & \multirow{2}{*}{1991--2011} \\
                                 & \includegraphics[height=0.11in]{flag/flag_IR.png} & IR & Iran         &  \\
      \midrule
      \multirow{2}{*}{LDCs}      & \includegraphics[height=0.11in]{flag/flag_TZ.png} & TZ & Tanzania & \multirow{2}{*}{1991--2011}     \\
                                 & \includegraphics[height=0.11in]{flag/flag_ZM.png} & ZM & Zambia      & \\
      \bottomrule
    \end{tabular}
  \end{center}
\end{table}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Sources of Data}
\label{sec:Sources_of_Data}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

To assess energy-augmented models of economic growth along the 
coordinates of analysis outlined in Section~\ref{sec:Coordinates}, 
historical data for 
economic output~($Y$), 
capital stock~($K$), 
labor~($L$), and 
thermal energy~($Q$)
are required. 
Subsections below describe sources for and calculations to obtain historical data. 
A final subsection presents the historical data in graphical form.

%++++++++++++++++++++++++++++++
\subsection{Economic Output} 
\label{sec:Economic_Output_Data}
%++++++++++++++++++++++++++++++

We measure economic output ($Y$) by gross domestic product (GDP). 
GDP data in real 2005 U.S. dollars for all countries was obtained from the
RGDP$^{\mathrm{NA}}$ time series of the Penn World Table.~\citep{Feenstra:2013aa}

%++++++++++++++++++++++++++++++
\subsection{Capital Stock}
\label{sec:Capital_Stock_Data}
%++++++++++++++++++++++++++++++

Gross capital stock in real 2005 U.S. dollars 
for all countries was obtained from the
RK$^{\mathrm{NA}}$ time series of the Penn World Table.~\citep{Feenstra:2013aa}

%++++++++++++++++++++++++++++++
\subsection{Labor and Employment}
\label{sec:Labor_Data}
%++++++++++++++++++++++++++++++

Total employment (persons engaged) for all countries
was obtained from the 
EMP time series of the Penn World Table.~\citep{Feenstra:2013aa}
The EMP time series was used as the labor factor of production 
for CN, ZA, SA, IR, TZ, and ZM.
For the developed nations (US, UK, and JP), 
average hours worked per worker per year 
was obtained from the AVH time series of the Penn World Table.~\citep{Feenstra:2013aa}
The product of EMP and AVH was used as the labor factor of production 
for the developed nations.


%++++++++++++++++++++++++++++++
\subsection{Energy} 
\label{sec:Energy_Data}
%++++++++++++++++++++++++++++++

To account for all energy input to an economy, we summed consumption data 
for many energy sources, including coal, oil and petroleum products, 
dry natural gas and natural gas plant liquids, nuclear power generation, 
and renewable energy sources (solar, wind, geothermal, biomass/fuel wood, 
and hydro). 
We also added animal muscle work. 
Following \citet{Ayres:2010ug}, 
human muscle work is excluded from the energy time series,
because it is counted as labor.
Similar to the economic data discussed in 
Sections~\ref{sec:Economic_Output_Data}--\ref{sec:Labor_Data}, 
we obtained energy data for developed countries from 1980--2011. 
For all other countries, 
we obtained energy data for 1991--2011. 

Thermal energy ($Q$) for fuels (in units of TJ/year) was calculated by
%
\begin{equation} \label{eq:thermal_energy}
  Q_{fuel} = C_{fuel}h_{fuel}
\end{equation}
%
\noindent where $C_{fuel}$ is the consumption rate of the fuel 
(in units of short tons/year for coal, barrels/year for oil and petroleum, 
ft$^3$/year for dry natural gas and natural gas plant liquids, 
and m$^3$/year for biomass and fuel wood) and $h_{{fuel}}$ is 
the heat content of the fuel (in kJ/short ton for coal, kJ/barrel for oil, 
kJ/ft$^3$ for dry natural gas and natural gas plant liquids, 
and kJ/kg for biomass and fuel wood). 
Fuel wood density of 300~kg/m$^3$ 
was taken from \citet{Ragland:2013wp} at the low end of the range 
of density of dry wood and bark.

Yearly consumption rates ($C_{fuel}$) of coal, oil and petroleum, 
dry natural gas and natural gas plant liquids, and biofuels 
(ethanol and biodiesel) were obtained from the \citet{EIA:2013a} 
for all economies. 
Yearly average heat content data for coal, oil, 
and natural gas and natural gas plant liquids was obtained from the 
\citet{EIA:2013a} for all economies. 
We used lower (net) heating values of 
26.8~MJ/kg \citep[Table~A-27]{Cengel:2011ww} and 37.8~MJ/kg 
\citep[Table~7.3]{Gupta:2010vg} for the heat content of ethanol 
and corn-based biodiesel, respectively. 
Yearly consumption and 
heat content data for biomass/fuel wood was obtained from the 
``Fuelwood'' time series of the FAO Statistics Database 
\citep{FAO:2013a}.

For renewable and nuclear energy sources, yearly electricity 
generation (in BTU/year) was available directly from 
the \citet{EIA:2013a} for all economies, so 
Equation~\ref{eq:thermal_energy} was unnecessary.

Animal muscle work was estimated using an approach 
similar to \citet{Ayres:2010ug}, using data from Warr's 
REXS database \citep{Warr:2012a} and results from 
\citet{Wirsenius:2000vi}. 
Similar to Warr, we excluded human muscle work from the energy term
on the grounds that labor terms are
already present in all production functions.
For animal work, our analysis was 
restricted to draught animals (horses and mules). Muscle work 
from animals ($Q_{animals}$) was calculated using
%
\begin{equation} \label{eq:animal_muscle}
  Q_{animals} = Q_{m,horse}N_{horses} + Q_{m,mule}N_{mules}
\end{equation}
%
\noindent where $Q_m$ is metabolizable energy (in kcal/day-animal) 
and $N$ is the number of animals. Metabolizable energy values 
($Q_{m,horses}$ = 19,110 kcal/day-horse and $Q_{m,mules}$ = 
7,215 kcal/day-mule) were taken from \citet{Warr:2012a}. 
$Q_m$ represents the amount of energy in the feed consumed by 
animals for a day of work, and they are assumed constant for 
all countries and years. The number of horses and mules for 
each economy was taken from the ``Live Animals'' section of the 
FAO Statistics online database \citep{FAO:2013a}.

%++++++++++++++++++++++++++++++
\subsection{Historical Data} 
\label{sec:Historical_Data}
%++++++++++++++++++++++++++++++

Figure~\ref{fig:Historical_Graph} presents historical data, 
including indexed values for 
output ($y$), 
capital stock ($k$), 
labor ($l$), and 
energy ($q$) 
for 1980--2011 (developed economies) and 1991--2011 (other economies). 
% Factors of production track each other closely, 
% and high covariances among these variables can be seen in 
% Tables~\ref{tab:Covariance_US}--\ref{tab:Covariance_ZM}. 
% \authNote{Do we want to discuss the covariances?}
%
<<Historical_Graph, fig.pos="H", fig.align='center', fig.width=3, fig.height=7.5, fig.cap="Historical data: indexed GDP ($y$), capital stock ($k$), labor ($l$), and thermal energy ($q$).">>=
mdata <- melt(historicalData, 
              measure.vars = c("iGDP", "iK", "iL", "iQp"), 
              value.name = "value", 
              variable.name = "variable") 
historicalPlot(data=mdata, 
               mapping=aes(x=Year, y=value, group=variable, linetype=variable), 
               facet_formula = Country ~ Source, 
               line_types = c(1,5,2,3)) +
  xlab("") +
  ylab("Indexed (1980=1 or 1991=1)")
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Parameter Estimation}
\label{sec:Parameter_Estimation}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%++++++++++++++++++++++++++++++
\subsection{Point Estimates}
%++++++++++++++++++++++++++++++

Each of the economic growth models discussed in 
Section~\ref{sec:Prod_Func_Forms} has parameters which must be estimated (fitted)
using data for each economy (see Sections~\ref{sec:Economy_Types} and~\ref{sec:Sources_of_Data}).
We obtained parameter estimates by applying the method of least-squares to 
log-transformed data using the \texttt{R} \citep{R} functions
\texttt{lm} (for Cobb-Douglas and LINEX models) 
and \texttt{cesEst} \citep{Henningsen:2011td} (for CES models).

Although the details vary from model to model, each of our three models has the general form
%
\begin{equation}
  y = f(t,k,l,e; \theta) + \mathrm{error} \;,
\end{equation}
%
where $\theta$ is a vector of parameters for the function $f$.
\authNote{if we use $\theta$ this way, we need a new scaling parameter. --rjp}%
Parameter estimates are chosen to minimize
\authNote{Randy edit the following equation to reflect the fact that we're fitting in log space.}
%
\begin{equation} \label{eq:sse}
  sse = \sum_{i} (y_i - f(t,k,l,e; \theta) )^2
\end{equation}
%
within constraints.
For the optimal parameter values $\hat \theta$, we define the 
fitted response by
%
\begin{equation}
  \hat y_i = f(t_i, k_i, l_i, e_i; \hat \theta)
\end{equation}
%
and the residuals ($r_i$)
as the difference between the observed response and the fitted response
%
\begin{equation} \label{eq:residual}
  r_i 
  = y_i - \hat y_i
  = y_i - f(t,k,l,e; \hat\theta)
\end{equation}
%
The details for each of the models are discussed in 
Sections~\ref{sec:CD_Parameter_Estimation}--\ref{sec:LINEX_Parameter_Estimation} below.


%++++++++++++++++++++++++++++++
\subsection{Resampling Methods}
\label{sec:Resampling}
%++++++++++++++++++++++++++++++

Bootstrapping is a statistical resampling technique for assigning
measures of accuracy and precision to sample estimates by measuring
properties of an estimator when sampling from a resampling
distribution.  
Resampling distributions can be formed in a number of 
ways in accordance with the type of data, experimental design,
and modeling assumptions involved.  
In each case, many new resamples 
are created, each of which is a randomized version of the original sample data to 
which the desired analysis method can be applied.  
By investigating, for example,
the variability of a parameter estimate from one resample to another,
one can learn about the precision of the estimation method.
\authNote{Add some references here. --rjp}

In the context of linear models (regression), resamples are generally created
by residual resampling.  
In our case, we formed resamples by adding to the fitted 
response ($\hat{y}$) the product of a residual from the original model fit and 
random sign ($-1$ or $1$, each with probability $0.5$).  
For the case of Cobb-Douglas and LINEX models, 
this residual resampling occurs on the 
log-transformed data.

Intuitively, this method assumes that the residuals are indicative of 
the variability (from many potential sources) inherent in the data such that
it would be unsurprising if the residual from 
any particular year had been observed in a different year. 
Thus, a resampled response $\tilde Y'$ can be computed as 
%
\begin{equation}
  \tilde Y_i' = \hat y_i \pm r_j
\end{equation}
%
where 
%
\begin{equation}
  r_i = y_i - \hat y_i
\end{equation}
%
both the sign ($\pm$) and the index of the residual 
($j$,~typically different from $i$) 
are chosen at random (with replacement). 
We repeated the resampling process 1000 times for each
combination of growth model and country, 
both with and without energy as appropriate.

The coefficients from the fit to a resampled time series
(the ``resample coefficients'') will be different from the coefficients 
obtained from the fit to historical data (the ``base coefficients'').
When these resample coefficients are highly variable, 
it is an indication
that the data do not determine the parameter estimates very precisely.
Lack of precision can stem from a number of factors, most obviously
a poor model fit, low model sensitivity to one or more parameters, 
or correlations between parameter estimates.

It is important to note that large residuals can arise from either
(a) poor quality historical time series data, or 
(b) a mathematical model that does not describe the underlying phenomena well.
It is also important to note that (c) even when the residuals are small and the 
model produces fitted values that track the observed data closely, it may
yet be difficult to estimate some or all of the model parameters precisely.
The resampling method employed herein reflects all three of these potential 
sources of uncertainty in parameter estimates.


%++++++++++++++++++++++++++++++
\subsection{Cobb-Douglas Models}
\label{sec:CD_Parameter_Estimation}
%++++++++++++++++++++++++++++++

The Cobb-Douglas model without energy is given by 
Equation~\ref{eq:CD}. Equation~\ref{eq:CD} was
reparameterized as
%
\begin{equation} \label{eq:CD_reparam}
  y = \theta \mathrm{e}^{\lambda (t-t_0)} k^{\alpha} l^{1-\alpha}
\end{equation}
%
\noindent to ensure $\alpha + \beta = 1$ for constant returns to scale. 
$\theta$, $\lambda$, and $\alpha$ were estimated by the 
\texttt{R} \citep{R} function \texttt{lm} in log-transform space. 
If the estimated value for $\alpha$ was found outside the interval $[0,1]$, 
we set $\alpha$ to its boundary value and re-estimated $\lambda$. 
The value of $\beta$ was found with $\beta = 1 - \alpha$. 

To estimate the parameters $\theta$, $\lambda$, $\alpha$, $\beta$, and $\gamma$ 
in the energy-augmented Cobb-Douglas model, Equation~\ref{eq:CDe} 
was reparameterized as
%
\begin{equation} \label{eq:CDe_AB_reparam}
  y = \theta \mathrm{e}^{\lambda (t-t_0)} k^{\alpha} l^{\beta} e^{1 - \alpha - \beta}
\end{equation}
%
ensuring that $\alpha + \beta + \gamma = 1$,
thereby providing constant returns to scale.
The \texttt{R} \citep{R} function \texttt{lm} was used to estimate 
values of $\lambda$, $\theta$, $\alpha$, and $\beta$ in log-transform space.
If the fitted value for $\alpha$ or $\beta$ fell outside the interval $[0,1]$,
we fit along all boundaries 
($\alpha = 1$,
$\beta = 1$,
$\gamma = 1$,
$\alpha = 0$,
$\beta = 0$, and
$\gamma = 0$)
and chose the boundary fit with
minimum $sse$ (Equation~\ref{eq:sse}) as the winner.
$\gamma$ was recovered with $\gamma = 1 - \alpha - \beta$.

Figure~\ref{fig:CD_lambda_theta_graph} shows $\lambda$ and $\theta$ values
for Cobb-Douglas resample models with and without energy.
Each reample is shown as a gray dot on the graph. 
The fit to historical data is shown as a gray crosshairs.

Figure~\ref{fig:CD_Ternary_Scatter_Graph} shows ternary plots 
for $\alpha$, $\beta$, and $\gamma$ parameter values 
for Cobb-Douglas (without and with energy) resample models.

Figure~\ref{fig:CD_GDP_Spaghetti_Graph} compares predictions 
from the Cobb-Douglas models 
(without and with energy) to historical data.
Historical data are shown as a black line. 
The fit to historical data is shown as a white line.
The gray band encompasses \Sexpr{spaghettiGraphLevel * 100.0}\% of the fits to resampled data.

<<CD_lambda_theta_graph, fig.pos="H", fig.align='center', fig.width=2.8, fig.height=7.0, fig.cap="$\\lambda$ and $\\theta$ values for CD resample models.">>=
cdCoeffsData <- filter(coeffs_df, model=="cd", nestStr %in% c("iK+iL", "iK+iL+iQp"))
standardScatterPlot(data=cdCoeffsData, mapping=aes(x=scale, y=lambda), facet_formula=country~energy, alpha=0.05) +
    scale_x_continuous(limits=c(0.8, 1.2), breaks=c(0.8, 1.0, 1.2)) +
    scale_y_continuous(limits=c(-0.05, 0.15), breaks=c(0, 0.05, 0.1)) +    
    labs(x=expression(theta), y=expression(lambda))
@

\twocolumn{}
<<CD_Ternary_Scatter_Graph, fig.pos="H", fig.align='center', fig.width=2.9, fig.height=7.7, fig.cap="Cobb-Douglas resample model parameters.">>=
standardTriPlot(data=cdCoeffsData, facet_formula=country~energy)
@

<<CD_GDP_Spaghetti_Graph, fig.pos="H", fig.align='center', fig.width=3, fig.height=8.2, fig.cap="Cobb-Douglas fitted models.">>=
cdFittedData <- filter(fitted_df, model=="cd", nestStr %in% c("iK+iL", "iK+iL+iQp"))
spaghettiPlot(data=cdFittedData, facet_formula=Country~energy, level=spaghettiGraphLevel) +
    labs(y="Indexed GDP (1980=1 or 1991=1)")
@
\onecolumn{}


%++++++++++++++++++++++++++++++
\subsection{CES Models}
\label{sec:CES_Parameter_Estimation}
%++++++++++++++++++++++++++++++

The CES model without and with energy is given by 
Equations~\ref{eq:CES}--\ref{eq:CESekl}. 
The \texttt{R} \citep{R} package \texttt{micEconCES} 
\citep{Henningsen:2011td} was used to estimate parameters 
$\lambda$, $\gamma$, $\delta$, $\delta_1$, $\rho$, and $\rho_1$. 
The \texttt{cesEst} function of \texttt{micEconCES} provides 
several algorithm options for parameter estimation.
The default algorithm (Levenberg-Marquardt) does not respect
parameter constraints (see Section~\ref{sec:CES}) and, 
in our testing, nearly always violated them, often returning
negative values for elasticity of substitution~($\sigma$) parameters.
Thus, we used the two fitting algorithms available in \texttt{cesEst} that
respect coefficient constraints: \texttt{PORT} and \texttt{L-BFGS-B}. 

Our CES parameter estimation algorithm starts with an eleven-value grid search
in $\rho$ and $\rho_1$ (9, 2, 1, 0.43, 0.25, 0.1, -0.1, -0.5, -0.75, -0.9, -0.99),
which corresponds to $\sigma$ and $\sigma_1$ values of
0.1, 0.33, 0.5, 0.7, 0.8, 0.9, 1.11, 2, 4, 10, and 100, respectively.
During the grid search, values of $\rho$ and $\rho_1$ are fixed,
and values of $\lambda$, $\gamma$, $\delta$, and $\delta_1$ are estimated 
by gradient search with the \texttt{PORT} and \texttt{L-BFGS-B} algorithms.
In all, 121 gradient searches in $\lambda$, $\gamma$, $\delta$, and $\delta_1$
at grid points representing all combinations of $\rho$ and $\rho_1$ are attempted.
During the grid search portion of our algorithm, starting values for the free parameters
are $\lambda$ = 0.015/year, $\delta$ = 0.5, $\delta_1$ = 0.5, 
and $\gamma$ is set to a value such that the mean of the residuals is zero
by the \texttt{cesEst} function.

Next, a gradient search (using both \texttt{PORT} and \texttt{L-BFGS-B}) 
is attempted wherein all fitting parameters 
($\lambda$, $\gamma$, $\delta$, $\delta_1$, $\rho$, and $\rho_1$)
are allowed to float. 
The start values for fitting parameters are taken from 
the grid search fit that provided the lowest $sse$ (Equation~\ref{eq:sse}).

If resampled data are being fitted, a prior fit to historical data is available.
In the final step of our algorithm, 
a gradient search (using both \texttt{PORT} and \texttt{L-BFGS-B})
uses coefficients from the best 
fit to historical data as its starting point. 
In this final gradient search, all model parameters 
($\lambda$, $\gamma$, $\delta$, $\delta_1$, $\rho$, and $\rho_1$)
are considered free parameters.

The fit with lowest $sse$ of all above trials is deemed the winner,
and its fitting parameters are used as the model.

\citet{Henningsen:2011td}, 
in their detailed analysis of \citet{Kemfert:1998vd}, found that 

\begin{quote}
\ldots the Levenberg-Marquardt and the \texttt{PORT} algorithms 
are---at least in this study---most likely to find the 
coefficients that give the best fit to the model, 
where the \texttt{PORT} algorithm can be used to restrict the estimates 
to the economically meaningful region.
\end{quote}

In our testing, we found that to be mostly true. 
\texttt{PORT} nearly always provided lower
$sse$ than \texttt{L-BFGS-B}, despite the fact that 
\texttt{L-BFGS-B} often reports convergence
and \texttt{PORT} does not for the same data
(i.e., for the same $y$, $k$, $l$, and $e$ time series).

Coefficients for each resampled CES model for all countries and all nests
are shown in 
Figures~\ref{fig:CES_lambda_gamma_graph}--\ref{fig:CES_sigma_delta_graph}. 
The white crosshair on each graph shows the location 
of the fit to historical data. 
In Figures~\ref{fig:CES_sigma1_delta1_graph} and~\ref{fig:CES_sigma_delta_graph},
the bottom of the vertical axis represents $\sigma = 0$ (perfect complements).
The top of the vertical axis represents $\sigma = \infty$ (perfect substitutes).

Note that as $\delta$ or $\delta_1$ approaches 0 (1) 
in Equations~\ref{eq:CES}--\ref{eq:CESekl},
the corresponding value of $\sigma$ or $\sigma_1$ becomes irrelevant, and
resample points along the left (right) edge of
Figures \ref{fig:CES_sigma1_delta1_graph} and \ref{fig:CES_sigma_delta_graph}
are equivalent.
That is, all points along the left (right) edge of
Figures \ref{fig:CES_sigma1_delta1_graph} and \ref{fig:CES_sigma_delta_graph}
have the same $sse$. 
As a consequence, 
the \texttt{cesEst} fitting algorithm has no way 
to discriminate among points along the left (right) edge of
Figures \ref{fig:CES_sigma1_delta1_graph} and \ref{fig:CES_sigma_delta_graph}. 
Thus, resample point estimates where $\delta$ or $\delta_1$ approaches 0 (1)
tend to cluster at the locations of the initial grid search in 
$\sigma$ or $\sigma_1$
(0.1, 0.33, 0.5, 0.7, 0.8, 0.9, 1.11, 2, 4, 10, and 100).

<<CES_lambda_gamma_graph, fig.pos="H", fig.align='center', fig.width=fourPanelScatterGraphWidth, fig.height=ninePanelScatterGraphHeight, fig.cap="$\\lambda$ and $\\gamma$ values for CES resample models.">>=
cesCoeffsData <- filter(coeffs_df, model=="ces", nestStrParen %in% c("(iK + iL) + ()", 
                                                                     "(iK + iL) + (iQp)", 
                                                                     "(iL + iQp) + (iK)", 
                                                                     "(iQp + iK) + (iL)"))
standardScatterPlot(data=cesCoeffsData, mapping=aes(gamma_coef, lambda), facet_formula=country~nestStrParen, alpha=0.05) +
    scale_x_continuous(breaks=c(0.9, 1.0, 1.1)) +
    scale_y_continuous(limits=c(-0.05, 0.15), breaks=c(0, 0.05, 0.1)) +    
    labs(x=expression(gamma), y=expression(lambda))
@

<<CES_sigma1_delta1_graph, fig.pos="H", fig.align='center', fig.width=fourPanelScatterGraphWidth, fig.height=ninePanelScatterGraphHeight, fig.cap="$\\sigma_1$ and $\\delta_1$ values for CES resample models.">>=
standardScatterPlot(data=cesCoeffsData, mapping=aes(delta_1, sigma_1), facet_formula=country~nestStrParen, alpha=0.05) +
    coord_trans(y="sigma") +
    scale_x_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    scale_y_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    labs(x=expression(delta[1]), y=expression(sigma[1]))
@

<<CES_sigma_delta_graph, fig.pos="H", fig.align='center', fig.width=4.5, fig.height=7, fig.cap="$\\sigma$ and $\\delta$ values for CES resample models.">>=
standardScatterPlot(data=subset(cesCoeffsData, nestStrParen != "(iK + iL) + ()"),
                    mapping=aes(delta, sigma), facet_formula=country~nestStrParen, alpha=0.05) +
    coord_trans(y="sigma") +
    scale_x_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    scale_y_continuous(breaks=c(0, 0.5, 1.0, 2.0)) +
    labs(x=expression(delta), y=expression(sigma))
@

We can develop pseudo $\alpha$, $\beta$, and $\gamma$ parameters 
for the CES model, based on values of $\delta$ and $\delta_1$.
Table~\ref{tab:CES_abg_equations} shows the permuted equations for each CES nesting.

\begin{table} \caption{Equations for $\alpha$, $\beta$, and $\gamma$ for the various CES nestings.} 
\label{tab:CES_abg_equations} 
  \begin{center}
    \begin{tabular}{c c c c c} 
      \toprule
      Nesting    & Equation        & $\alpha$                & $\beta$                 & $\gamma$       \\
      \midrule
      ($kl$) + ()     & \ref{eq:CES}    & $\delta_1$              & $1 - \delta_1$          & 0          \\
      ($kl$) + ($e$)  & \ref{eq:CESkle} & $\delta \delta_1$       & $\delta (1 - \delta_1)$ & $1 - \delta$ \\   
      ($le$) + ($k$)  & \ref{eq:CESlek} & $1 - \delta$            & $\delta \delta_1$       & $\delta (1 - \delta_1)$ \\
      ($ek$) + ($l$)  & \ref{eq:CESekl} & $\delta (1 - \delta_1)$ & $1 - \delta$            & $\delta \delta_1$ \\
      \bottomrule
    \end{tabular}
  \end{center}
\end{table}

Figure~\ref{fig:CES_ternary_graph} shows 
$\alpha$, $\beta$, and $\gamma$ parameters for the CES model for all nests and countries.
Figure~\ref{fig:CES_ternary_graph} is comparable to
the ternary graph for the Cobb-Douglas models, 
Figure~\ref{fig:CD_Ternary_Scatter_Graph}.

<<CES_ternary_graph, fig.pos="H", fig.align='center', fig.width=5.5, fig.height=7.5, fig.cap="$\\alpha$, $\\beta$, and $\\gamma$ values for CES resample models.">>=
standardTriPlot(data=cesCoeffsData, facet_formula=country~nestStrParen)
@

Figure~\ref{fig:CES_Spaghetti_Graph} compares CES model predictions 
to historical data for all nestings. 
As with the Cobb-Douglas results, 
historical data are shown as a black line, 
the fit to historical data is shown as a white line, and 
the gray band encompasses \Sexpr{spaghettiGraphLevel * 100.0}\% of the fits to resampled data.

<<CES_Spaghetti_Graph, fig.pos="H", fig.align='center', fig.width=6.5, fig.height=8.5, fig.cap="CES fitted models.">>=
cesFittedData <- filter(fitted_df, model=="ces", nestStrParen %in% c("(iK + iL) + ()", 
                                                                     "(iK + iL) + (iQp)", 
                                                                     "(iL + iQp) + (iK)", 
                                                                     "(iQp + iK) + (iL)"))
spaghettiPlot(data=cesFittedData, facet_formula=Country~nestStrParen, level=spaghettiGraphLevel) +
    labs(y="Indexed GDP (1980=1 or 1991=1)")
@


%++++++++++++++++++++++++++++++
\subsection{LINEX Models}
\label{sec:LINEX_Parameter_Estimation}
%++++++++++++++++++++++++++++++

The LINEX model is given in Equation~\ref{eq:LINEX}. 
If the fitting algorithm drives $a_0 \rightarrow 0$, 
any changes to $c_t$ have no effect on $sse$. 
Therefore, we transformed the LINEX model into
%
\begin{equation} \label{eq:LINEX_transformed}
  y = \theta A e; 
  A = \mathrm{e}^{\left[2 a_0 \left(1 - \frac{1}{\rho_k} \right) 
    + a_1 \left(\vphantom{\frac{1}{\rho_k}}\rho_l - 1 \right)\right]},
\end{equation}
%
\noindent where $a_1 \equiv a_0 c_t$. 
We used the \texttt{lm} function in \texttt{R}
\citep{R} to estimate least-squares values for $a_0$ and $a_1$ in 
Equation~\ref{eq:LINEX_transformed} in log-transformed space. 
We recovered a value for $c_t$ with $c_t = a_1 / a_0$. 
Figure~\ref{fig:LINEXq_Resample_Graph}
shows the coefficients estimated from resampled data.
We fit $a_0$ and $c_t$ unconstrained.

Figure~\ref{fig:LINEX_Spaghetti_Graph} compares LINEX model predictions to historical data.
Again, historical data are shown as a black line, 
the fit to historical data is shown as a white line and 
the gray band encompasses \Sexpr{spaghettiGraphLevel * 100.0}\% of the fits to resampled data.

\twocolumn{}
<<LINEXq_Resample_Graph, fig.pos="H", fig.align='center', fig.width=2, fig.height=7, fig.cap="LINEX model (with energy) resampling results.">>=
linexCoeffsData <- filter(coeffs_df, model=="linex", energy=="iQp")
standardScatterPlot(data=linexCoeffsData, aes(a_0, c_t), facet_formula=country~energy, alpha=0.05) +
    labs(x=expression(a[0]), y=expression(c[t])) +
     scale_x_continuous(limits=c(0, 2), breaks=c(0, 1.0, 2.0)) +
     scale_y_continuous(limits=c(0, 10), breaks=c(0, 5, 10))
@

<<LINEX_Spaghetti_Graph, fig.pos="H", fig.align='center', fig.width=2, fig.height=7.1, fig.cap="LINEX fitted models.">>=
linexFittedData <- filter(fitted_df, model=="linex", energy=="iQp")
spaghettiPlot(data=linexFittedData, facet_formula=Country~energy, level=spaghettiGraphLevel) +
    labs(y="Indexed GDP (1980=1 or 1991=1)")
@
\onecolumn{}

The LINEX model coefficients $a_0$ and $c_t$ imply time-varying
values of $\alpha$, $\beta$, and $\gamma$ as shown by \citet[Equations~7]{Warr:2012cg}.
Thus, each fitted model implies a trajectory of $\alpha$, $\beta$, and $\gamma$ values as time proceeds.
We found unconstrained fitting produced $\alpha$,$\beta$,$\gamma$ trajectories
that violated parameter constraints ($[0,1]$) for all countries, with the exception of Iran.
If the LINEX model were forced to respect the constraints,
it would fit worse than it already does for those countries where
the constraints are violated (that is, for every country except Iran).
\citet{Warr:2012cg} selected values of $a_0$ and $c_t$, while still holding them constant
for the entire time series, such that the constraints on $\alpha$, $\beta$, and $\gamma$
were respected throughout their time series.
But, Warr's approach necessarily leads to larger $sse$ values than unconstrained fitting.
Because in our results unconstrained LINEX models already fit worse than 
constrained Cobb-Douglas and CES models,
we chose to report unconstrained LINEX model fits in this paper.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Discussion of Results}
\label{sec:Discussion_of_Results}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

We find it beneficial to discuss results through a series of questions, 
answers to which are illuminated by the techniques and results presented above.


%++++++++++++++++++++++++++++++
\subsection{Is it important to include energy in the production function?} 
\label{sec:important_to_include_energy}
%++++++++++++++++++++++++++++++

For the Cobb-Douglas and CES production functions, 
augmentation with energy improves goodness of fit when $\gamma > 0$.%
  \footnote{
  The LINEX function is unhelpful in answering the question 
  ``Is it important to include energy in production functions?'' 
  because LINEX presupposes that energy is the only factor of production.
  }

First, we look at the results of the Cobb-Douglas functions 
in Figures~\ref{fig:CD_lambda_theta_graph} and~\ref{fig:CD_Ternary_Scatter_Graph}. 
Visually, $\gamma > 0$ is shown in the right column 
of Figure~\ref{fig:CD_Ternary_Scatter_Graph} 
as data points that are above the horizontal base of the ternary plots. 
We note that the list of countries for which $\gamma \gg 0$ includes 
Tanzania, South Africa, Saudi Arabia, and the United Kingdom. 
Especially for Tanzania, but also for Saudi Arabia and the United Kingdom, 
it appears certain that including energy improves goodness of fit: 
both the fit to historical data (crosshairs) 
and all resample data points (black dots) 
are above the base of the triangle in the energy columns of Figure~\ref{fig:CD_Ternary_Scatter_Graph}. 
However, for South Africa, significant uncertainty in $\gamma$, 
as shown by the large vertical spread of resample data points, 
leads us to exercise caution in concluding that adding energy to the production function is helpful
for improving fit to historical data. 
A robust result 
($\gamma$ equal or close to zero and very little vertical spread of the resample points) 
indicates that including energy does not help to explain economic growth in Zambia,
while for United States, Japan, China, and especially Iran, 
it is less certain that augmenting with energy is unhelpful 
(larger vertical spread of resample points).

The results for the CES analysis (Figure~\ref{fig:CES_ternary_graph}) 
indicate that including energy is clearly helpful 
in explaining economic growth in Saudi Arabia, 
because all resample data points are consistently far above the base of the ternary plots 
($\gamma \gg 0$) for all possible ways of nesting of energy with capital and labor. 
Two out of the three possible nestings suggest the importance of including energy for Japan and Tanzania.
For Iran, the crosshairs indicate that energy may explain some growth, 
but this is highly uncertain as the resample data points have a very large vertical spread.  
Explaining economic growth in the United States, China, and Zambia will benefit 
relatively less by including energy, 
but the vertical spreads indicate some uncertainty 
in the cases of the United States and Zambia.  
The results for both the United Kingdom and South Africa 
exhibit significant uncertainty and are contradictory for the various nests.

Based on this analysis of the empirical data, 
we find no grounds to argue for augmenting the production function 
with energy for all economies. 
Our results support \citeapos{Stern:2011bq} conclusion that energy 
may or may not be required in production functions,
depending on its abundance or scarcity. 
But, one cannot know \emph{a-priori} the economies 
for which augmenting by energy will improve goodness of fit. 
Statistical testing is clearly warranted. 


%++++++++++++++++++++++++++++++
\subsection{Are the World Bank country categories
helpful for conceptualizing the role of energy in economic growth?} 
\label{sec:wb_categories_helpful}
%++++++++++++++++++++++++++++++

Some developed economies (US) benefit little from including energy as a factor of production, 
while some others (UK) benefit in a minor way. 
For other developed economies (JP), the results of CD and CES models point in opposite directions.  
For NICs the results are mixed; 
China does not convincingly benefit from energy-augmented production functions, 
and results are uncertain for South Africa (ZA) due to lack of precision in determining $\gamma$.  
In one OPEC country (SA), adding energy clearly helps to explain economic growth, 
while in another (IR), the benefit of energy augmentation is small and uncertain. 
For LDCs there is a either a strong indication that energy-augmented production functions 
are beneficial as an explanation for growth (TZ) or string indication otherwise (ZM).  

In summary, we observe that World Bank country categories (Table~\ref{tab:Economy_Examples}) 
do not predict whether energy augmentation will be beneficial. 
In fact, 
there is as much variation of the role of energy in economic growth 
within World Bank country categories
as between World Bank country categories. 
Thus, we conclude that the World Bank’s country categories are not helpful 
in explaining the role of energy in economic growth. 
Rather, a nuanced approach is necessary wherein the energy situation 
in each economy is assessed independently.


%++++++++++++++++++++++++++++++
\subsection{Does augmentation by energy reduce the Solow residual?} 
\label{sec:energy_reduce_solow}
%++++++++++++++++++++++++++++++

The so-called Solow residual ($\lambda$ in Equations~\ref{eq:CD}--\ref{eq:CESekl}) 
accounts for “slowdowns, speed-ups, improvements in the education of the labor force, 
and all sorts of things [that] appear as ``technical change.''~\citep{solow1957technical} 
The time-dependent term is often associated with
``technological progress,'' but that is a very narrow reading of Solow's original intent:
  \begin{quote}
    It will be seen that I am using the phrase ``technical change''
    as a short-hand expression for any kind of shift 
    in the production function. 
    Thus slowdowns, speed-ups, improvements in the education of the labor force, 
    and all sorts of things will appear as ``technical change.''~\citep{solow1957technical}
  \end{quote}

It has been shown elsewhere~\citep{Ayres:2010ug}
that consideration of energy (specifically, useful work) 
in the production function eliminates the need for the Solow residual~($\lambda$) 
over the very long run (e.g.,~1900--2000). 
The purpose of this paper, however, is to assess common production functions \emph{as used in practice}, 
so we include $\lambda$ terms in all fitted production functions. 
The present approach allows us to answer the question of whether augmentation by 
primary energy in the production function reduces the \emph{value of} the Solow residual,
as opposed to eliminating the \emph{need for} the Solow residual altogether (Ayres and Warr's question).
After augmenting by energy, the Solow-residual ($\lambda$) 
in the Cobb-Douglas~(Figure~\ref{fig:CD_lambda_theta_graph}) 
and CES models~(\ref{fig:CES_lambda_gamma_graph}) 
still explains a part of economic growth in several economies, 
especially China, but also in the United Kingdom, Japan, and Tanzania,  
and to a lesser extent in the United States and Iran. 
In South Africa and Zambia, the Solow-residual is zero, while in Saudi Arabia it is negative.%
  \footnote{
  The negative Solow residual ($\lambda$) for Saudi Arabia is a consequence
  of the fact that all indexed factors of production ($k$, $l$, and $e$) are greater than 
  economic output ($y$) for most of the period under study (1991--2011).
  }
For the Chinese economy, energy augmentation significantly reduces 
the uncertainty of the value of the Solow residual~(Figure~\ref{fig:CES_lambda_gamma_graph}). 
Furthermore, no economies show reduced magnitude of the Solow residual from left to right
in Figures~\ref{fig:CD_lambda_theta_graph} and~\ref{fig:CES_lambda_gamma_graph}.

Thus, we conclude that energy augmentation of the production function 
by primary thermal energy does not decrease the value of the Solow residual~($\lambda$) 
over the years studied (1980--2011 and 1991--2011). 
Longer-term analyses involving other energy quantifications (exergy or useful work) 
are warranted.


%++++++++++++++++++++++++++++++
\subsection{Does the CES model structure (nesting) matter?} 
\label{sec:nest_matter}
%++++++++++++++++++++++++++++++

The choice of CES nesting structure has significant influence 
on model results for both 
relative importance of factors of production ($\delta$ and $\delta_1$ values) and 
substitutability among factors of production ($\sigma$ and $\sigma_1$ values). 


%------------------------------
\subsubsection{Relative importance of factors of production ($\delta$ and $\delta_1$ values)} 
\label{sec:importance_of_factors}
%------------------------------

For most economies (UK, JP, CN, ZA, SA, IR, and TZ), 
Figure~\ref{fig:CES_ternary_graph} shows that the relative importance of 
production factors capital~($k$), labour~($l$), and energy~($e$) 
is different for the three different CES nestings (Equations~\ref{eq:CESkle}--\ref{eq:CESekl}). 
In other words, you cannot view two of the ternary plots 
in the rightmost three columns of Figure~\ref{fig:CES_ternary_graph} and predict the third. 
Nesting structure matters little for the economies of the United States and Zambia.

Certain combinations of economy, parameter values, and CES nesting structure 
come with very large resampling spreads, 
indicating large fitted parameter uncertainties. 
For example, 
for Iran's ($kl$)$e$ nesting in Figures~\ref{fig:CES_sigma1_delta1_graph}--\ref{fig:CES_ternary_graph} 
there is virtually no useful information 
in $\delta$, $\delta_1$, $\alpha$, $\beta$, and $\gamma$. 


%------------------------------
\subsubsection{Elasticity of substitution among factors of production ($\sigma$ and $\sigma_1$ values)} 
\label{sec:elasticity_of_substitution}
%------------------------------

The interpretation of elasticities of substitution 
among factors of production ($k$, $l$, and $e$) is challenging,
because a version of each elasticity of substitution appears three or four times 
among the various nests. 
For example, an elasticity of substitution between capital~($k$) and labor~($l$) 
appears in the following nests: 
($\underline{kl}$), 
($\underline{kl}$)$e$, 
($\underline{l}e$)$\underline{k}$, and 
($e\underline{k}$)$\underline{l}$. 
The following tables assist interpretation: 
C (c) indicates strong (weak) complementarity, 
S (s) indicates strong (weak) substitutability, 
$\sim\sim\sim$ indicates large uncertainty, 
and $\sim$ indicates small uncertainty. 

**** Need to think this presentation through, 
want to see how balances with the rest of the paper; 
do we have the space seems to be the limiting factor? --MdW ****

**** I'm fine if we want to change to another form of these tables.
But, I found the presentation below to be a good way to think about the results.
My idea was to say ``hang on! We have several ways to get at some of these elasticities.
Let's compare all the different ways to look at the elasticity between any two factors of production.
Do they agree?  
Are they in conflict?''  
Another point to make is that these comparisons need to be done honestly. 
We should not claim anything when the data are uncertain.

Regarding Martin's question about length, 
I've seen other papers in \emph{Energy Economics} that are 51 printed journal pages. (Saunders, 2008)
I expect we are fine on length. --MKH ****

\begin{table} \caption{Elasticities of substitution (US).} \label{tab:sigma_US} 
  \begin{center}
    \begin{tabular}{r l c l c l c} 
      \toprule
         & \multicolumn{2}{c}{$k$ \& $l$} & \multicolumn{2}{c}{$k$ \& $e$} & \multicolumn{2}{c}{$l$ \& $e$} \\
      \midrule
      \multirow{2}{*}{$\sigma_1$} & ($\underline{kl}$) & C 
                                        &  & 
                                              & &  \\
                                  & ($\underline{kl}$)$e$ & C 
                                        & ($\underline{ek}$)$l$ & $\sim\sim\sim$ 
                                              & ($\underline{le}$)$k$ & $\sim\sim\sim$ \\
      \midrule
      \multirow{3}{*}{$\sigma$} & &
                                      & ($\underline{k}l$)$\underline{e}$ & $\sim\sim\sim$
                                            & ($k\underline{l}$)$\underline{e}$ & $\sim\sim\sim$ \\
                                & ($\underline{l}e$)$\underline{k}$ & C
                                      & ($l\underline{e}$)$\underline{k}$ & C
                                            &  & \\
                                & ($e\underline{k}$)$\underline{l}$ & C
                                      & &
                                            & ($\underline{e}k$)$\underline{l}$ & C \\
      \midrule
                                & \multicolumn{2}{c}{C} & \multicolumn{2}{c}{C} & \multicolumn{2}{c}{C} \\
      \bottomrule
    \end{tabular}
  \end{center}
\end{table}

\begin{table} \caption{Elasticities of substitution (UK).} \label{tab:sigma_UK} 
  \begin{center}
    \begin{tabular}{r l c l c l c} 
      \toprule
         & \multicolumn{2}{c}{$k$ \& $l$} & \multicolumn{2}{c}{$k$ \& $e$} & \multicolumn{2}{c}{$l$ \& $e$} \\
      \midrule
      \multirow{2}{*}{$\sigma_1$} & ($\underline{kl}$) & C 
                                        &  & 
                                              & &  \\
                                  & ($\underline{kl}$)$e$ & $\sim\sim\sim$ 
                                        & ($\underline{ek}$)$l$ & C
                                              & ($\underline{le}$)$k$ & C \\
      \midrule
      \multirow{3}{*}{$\sigma$} & &
                                      & ($\underline{k}l$)$\underline{e}$ & C
                                            & ($k\underline{l}$)$\underline{e}$ & C \\
                                & ($\underline{l}e$)$\underline{k}$ & C
                                      & ($l\underline{e}$)$\underline{k}$ & C
                                            &  & \\
                                & ($e\underline{k}$)$\underline{l}$ & $\sim\sim\sim$
                                      & &
                                            & ($\underline{e}k$)$\underline{l}$ & $\sim\sim\sim$ \\
      \midrule
                                & \multicolumn{2}{c}{C} & \multicolumn{2}{c}{C} & \multicolumn{2}{c}{C} \\
      \bottomrule
    \end{tabular}
  \end{center}
\end{table}

**** For the time being, I've added two of these tables.
We can add the remaining seven tables easily, either here or in an appendix. --MKH ****

For many estimates of elasticity of substitution, the resampling technique indicates high uncertainty. 
Where results are not uncertain, 
we find complementarity among factors of production 
for most economies with the exception of China 
where an indication of substitutability between labor and energy is observed.

That so many estimates of elasticity of substitution exhibit large uncertainty, 
often spanning the range from perfect complements ($\sigma, \sigma_1 = 0$) 
to perfect substitutes ($\sigma, \sigma_1 = 1$), 
is a troubling characteristic of the estimated CES models. 
For some countries (IR, ZM), 
estimating any elasticity of substitution at all is problematic and fraught with peril. 
Note that this result is unlikely to be caused by poor-quality data alone. 
Presumably the best data in the world (US, UK, JP) exhibits large uncertainty. 
(See US and UK rows in Figures~\ref{fig:CD_Ternary_Scatter_Graph}  
and~\ref{fig:CES_sigma1_delta1_graph}--\ref{fig:CES_ternary_graph}.)

Some of the uncertainty is explained by the structure of the CES model. 
If $\delta$ or $\delta_1$ achieves an extreme value (0 or 1), 
the corresponding elasticity of substitution ($\sigma$ and $\sigma_1$) becomes meaningless. 
(See Equations~\ref{eq:CES}--\ref{eq:CESekl}.) 
Thus, large uncertainty in $\sigma$ and $\sigma_1$ is expected for any resampled model 
in which parameter estimates are positioned on the left or right boundaries 
of Figures~\ref{fig:CES_sigma1_delta1_graph} or~\ref{fig:CES_sigma_delta_graph}.

Some of the uncertainty in parameter estimates may be explained by structural change in the economies. 
For example, 
**** Martin: can you select one of the highly uncertain economies and discuss it? 
Perhaps Iran or Zambia? ****. 
To account for the large uncertainty, 
it may be useful to perform piecewise analyses of smaller time periods. 
For the present study, doing piecewise analysis of, say, 
Iran **** Use the economy that Martin discusses above **** 
would mean that the CES model is estimated on a 10-year period. 
Considering that there are six fitted parameters in the CES model 
($\gamma$, $\lambda$, $\delta$, $\delta_1$, $\rho$, and $\rho_1$), 
ten years of historical data leaves precious few (only 4) degrees of freedom for the fitting process. 

Based on the results and discussions above 
regarding the relative importance of and 
the elasticity of substitution among factors of production, 
we conclude that use of the CES model for energy analysis 
should be undertaken with utmost caution. 
Indeed, empirical testing on the relative importance 
of production factors and elasticities of substitution is highly recommended. 
Sensitivity analysis is essential. 
Our results support \citeapos{Lecca:2011kr} conclusion 
for the need to econometrically specify production function relationships and 
to perform sensitivity analysis on nesting choices in economies to enhance the reliability of results. 


%++++++++++++++++++++++++++++++
\subsection{Which production function is best for energy augmentation?} 
\label{sec:which_best}
%++++++++++++++++++++++++++++++

**** Shall we have a section here discussing which function is ``best''? --MKH ****
What are the criteria?

Allows assymetric uncertainty estimation via resampling: all work fine.

Best match to historical data: CES. 

No ambiguity from model structure: CD and LinEx OK here. 
CES has the undesireable characteristic that form (nesting) affects outcome.

Easy to estimate: CD and LinEx can be fitted with linear function. 
CES requires complex and time-consuming optimzation techniques.

Small uncertainties in fitted parameters: CD and LinEx better than CES.

Our assessment: None of the production functions is perfect. 
Probably CD is best compromise among ease of estimating, good (but not best) fit to historical data, and
small uncertainties in fitted parameters. 

Caution: none of the production functions analyzed herein allows for complex energy-economy phenomena
like rebound effect, backfire, and super-conservation.


%++++++++++++++++++++++++++++++
\subsection{Implications of resampling results } 
\label{sec:implications}
%++++++++++++++++++++++++++++++

In addition to the usual parameter estimation process 
by linear coefficient determination (Cobb-Douglas and LinEx) 
and non-linear optimization algorithms (CES), 
the resampling/bootstrapping analysis performed herein 
provides insight into the question of how accurately parameters are known. 
We chose the resampling approach instead of the more-common technique 
of estimating confidence intervals from standard errors for two reasons. 
(1)~Model parameters are highly constrained, and confidence intervals often violate the constraints. 
For example a result of $\alpha = 0.25 \pm 0.3$ is nonsensical, 
because $ \alpha \in [0, 1]$. 
(2)~True confidence intervals for constrained parameters are often asymmetric
(e.g., $\alpha = 0.2 + 0.1, -0.05$), 
but the standard error approach yields symmetric confidence intervals. 
The resampling approach that we employed both respects constraints 
and allows for asymmetric confidence intervals.%
  \footnote{
    We have chosen to present parameter uncertainty results visually, 
    both because the resampling technique lends itself to visual presentation and 
    because we believe visual comparison is more effective than tablefuls of numbers.
  }
A significant result to emerge from this work is that large parameter uncertainty 
does not necessarily lead to poor model fit to economic output. 
To choose one example of many, 
the value of $\gamma$ for the Cobb-Douglas model for Tanzania (0.59) 
shows a resampling range of 0.2–0.9. 
(See Figure~\ref{fig:CD_Ternary_Scatter_Graph}.) 
Yet, Cobb-Douglas models for Tanzania, with and without energy, both 
(a)~fit historical data very well 
(white line compared to black line in Tanzania row of Figure~\ref{fig:CD_GDP_Spaghetti_Graph}) 
and 
(b)~exhibit a very narrow range of resampled fits 
(thin gray band in Tanzania row of Figure~\ref{fig:CD_GDP_Spaghetti_Graph}). 
This means that a good fit to historical data does not indicate 
that model parameters have small uncertainty. 
In fact, similar to Tanzania, 
many economies exhibit both large uncertainty in model parameters and
very good fit to historical data. 
(See Figures~\ref{fig:CD_lambda_theta_graph} ~\ref{fig:CD_Ternary_Scatter_Graph} 
compared to Figure~\ref{fig:CD_GDP_Spaghetti_Graph}
for the Cobb-Douglas models and 
Figure~\ref{fig:CES_lambda_gamma_graph}--\ref{fig:CES_sigma_delta_graph}
compared to Figure~\ref{fig:CES_Spaghetti_Graph} for CES models.) 
This result is consistent across almost all economies and models. 
Thus, we conclude that great care must be taken when interpreting estimated parameters: 
it is very easy to claim more certainty than is warranted. 
Where large uncertainty is observed, 
additional work is needed to contextualize the results, 
for example, 
sector-based analysis or ****. **** Martin, add more here? ****

**** Not sure whether contextualization will work. 
Could be read that macroeconomic growth modeling in such cases is not really useful at all? 
--MdW ****

We further caution against using $R^2$ only as the criteria for choosing a model, 
because, in our experience, 
both Cobb-Douglas and CES models yield high $R^2$ values for all countries. 
(See Figures~\ref{fig:CD_GDP_Spaghetti_Graph} and~\ref{fig:CES_Spaghetti_Graph}.) 
LinEx models fare poorly in some cases and might be excluded on that basis. 
(See SA and TZ in Figure~\ref{fig:LINEX_Spaghetti_Graph}.) 
It is more important to know the uncertainty of estimated parameters than to assess $R^2$. 
With rigorous uncertainty testing as we have done here, 
the quality of parameter estimates is exposed: 
at a glance, the tightness of resampled results indicates 
whether or not confidence in the model and data is warranted. 
We conclude that it is insufficient to argue 
in favor of a particular production function 
on the grounds of its ability to fit historical data.

The implications of parameter uncertainties should be obvious, 
but we will state them here. 
Basing policy upon parameters with high uncertainty can lead to bad, or completely wrong, policy. 
**** Martin: can you find an example in our results that drives this point home? --MKH  
May be barking up wrong production factor, may assume subs when complementarity: ****

We conclude that the best policy will be made 
with a macroeconomic modeling approach that is highly interpretative, 
uses several production functions, and 
estimates asymmetric uncertainties of fitted parameters.

**** Other notes from our word document ****

Lastly, what do aggregate models say? 

What direction can take from this work? 

What is the status of ME growth modeling after this?


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Conclusion}
\label{sec:Conclusion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


Conclusion goes here.



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Future Work}
\label{sec:FutureWork}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**** Revisit this section when we finish writing the paper. ****

In the future, we intend add an additional coordinate of analysis 
(Section~\ref{sec:Coordinates}):
energy quantification.
Specifically, we want to analyze exergy ($X$) and useful work ($U$)
energy quantifications within the framework established in this paper.
Doing so will provide an opportunity to engage the 
literature around useful work as a driver 
of economic growth.\citep{Ayres:2003ec, Ayres:2005kn, Ayres:2010ug, 
Warr:2006hc, Warr:2010ga, Warr:2010ht, Warr:2012cg}
And, we will be able to assess the interaction between economic models
and energy quantification:
are there combinations of economic models and energy quantifications
that provide significantly better descriptions of growth?
We intend to evaluate additional countries as data become available.
And, we wish to perform analyses over longer time scales.
In particular, we wish to investigate the effects of significant 
economic processes (such as industrialization) and political events (world wars)
using the resampling techniques presented herein.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Acknowledgements}
\label{sec:Acknowledgements}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Funding for Caleb Reese and Lucas Timmer was provided 
by the Jack and Lois Kuipers Applied Mathematics Endowment and 
the Calvin College Alumni Association. 
Partial support for Matthew Kuperus Heun was 
provided by a Calvin College Research Followship. 
Partial funding for Martin de Wit was provided 
by the South African National Research Foundation (NRF).\footnote{Any opinion, 
findings, and conclusions or recommendations expressed herein are those 
of the authors, and, therefore, NRF does not accept any liability in regard thereto.} 
The authors are grateful to Benjamin S. Warr (INSEAD) for providing 
the REXS database \citep{Warr:2012a}. 
The authors thank Loren L. Heun (Western Michigan University) 
for insightful critique of the statistical analyses presented herein.
The computations in this paper were accomplished using \url{http://dahl.calvin.edu}, 
a Beowulf cluster built with support from the National Science Foundation's 
Major Research Instrumentation and Cyber Infrastructure programs, 
grant number OCI-0722819.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Reproducible Research}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In the spirit of Reproducible Research \citep{Gandrud:2013vx}, 
all data, spreadsheets, \texttt{R} code \citep{R}, and other materials 
associated with this paper can be found at\\*
\protect\url{https://github.com/MatthewHeun/Econ-Growth-R-Analysis}.

%% The Appendices part is started with the command \appendix;
%% appendix sections are then done as normal sections
%% \appendix
%% \section{}
%% \label{}


%% References
%%
%% Following citation commands can be used in the body text:
%%
%%  \citet{key}  ==>>  Jones et al. (1990)
%%  \citep{key}  ==>>  (Jones et al., 1990)
%%
%% Multiple citations as normal:
%% \citep{key1,key2}         ==>> (Jones et al., 1990; Smith, 1989)
%%                            or  (Jones et al., 1990, 1991)
%%                            or  (Jones et al., 1990a,b)
%% \cite{key} is the equivalent of \citet{key} in author-year mode
%%
%% Full author lists may be forced with \citet* or \citep*, e.g.
%%   \citep*{key}            ==>> (Jones, Baker, and Williams, 1990)
%%
%% Optional notes as:
%%   \citep[chap. 2]{key}    ==>> (Jones et al., 1990, chap. 2)
%%   \citep[e.g.,][]{key}    ==>> (e.g., Jones et al., 1990)
%%   \citep[see][pg. 34]{key}==>> (see Jones et al., 1990, pg. 34)
%%  (Note: in standard LaTeX, only one note is allowed, after the ref.
%%   Here, one note is like the standard, two make pre- and post-notes.)
%%
%%   \citealt{key}          ==>> Jones et al. 1990
%%   \citealt*{key}         ==>> Jones, Baker, and Williams 1990
%%   \citealp{key}          ==>> Jones et al., 1990
%%   \citealp*{key}         ==>> Jones, Baker, and Williams, 1990
%%
%% Additional citation possibilities
%%   \citeauthor{key}       ==>> Jones et al.
%%   \citeauthor*{key}      ==>> Jones, Baker, and Williams
%%   \citeyear{key}         ==>> 1990
%%   \citeyearpar{key}      ==>> (1990)
%%   \citetext{priv. comm.} ==>> (priv. comm.)
%%   \citenum{key}          ==>> 11 [non-superscripted]
%% Note: full author lists depends on whether the bib style supports them;
%%       if not, the abbreviated list is printed even when full requested.
%%
%% For names like della Robbia at the start of a sentence, use
%%   \Citet{dRob98}         ==>> Della Robbia (1998)
%%   \Citep{dRob98}         ==>> (Della Robbia, 1998)
%%   \Citeauthor{dRob98}    ==>> Della Robbia


%% References with bibTeX database:

\bibliographystyle{model2-names}
%%\bibliography{<your-bib-database>}
\bibliography{EconGrowth.bib}

%% Authors are advised to submit their bibtex database files. They are
%% requested to list a bibtex style file in the manuscript if they do
%% not want to use model2-names.bst.

%% References without bibTeX database:

% \begin{thebibliography}{00}

%% \bibitem must have one of the following forms:
%%   \bibitem[Jones et al.(1990)]{key}...
%%   \bibitem[Jones et al.(1990)Jones, Baker, and Williams]{key}...
%%   \bibitem[Jones et al., 1990]{key}...
%%   \bibitem[\protect\citeauthoryear{Jones, Baker, and Williams}{Jones
%%       et al.}{1990}]{key}...
%%   \bibitem[\protect\citeauthoryear{Jones et al.}{1990}]{key}...
%%   \bibitem[\protect\astroncite{Jones et al.}{1990}]{key}...
%%   \bibitem[\protect\citename{Jones et al., }1990]{key}...
%%   \harvarditem[Jones et al.]{Jones, Baker, and Williams}{1990}{key}...
%%

% \bibitem[ ()]{}

% \end{thebibliography}

\end{document}

%%
%% End of file `elsarticle-template-2-harv.tex'.
