---
title: "Triplots and Output Elasticities"
output:
  pdf_document: 
    fig_height: 4
    fig_width: 7
  html_document:
    fig_height: 3
    fig_width: 4
date: "September 16, 2015"
---

```{r, setup, include=FALSE}
require(mosaic)
require(EconModels)
require(EconData)
require(knitr)
knitr::opts_chunk$set(cache=TRUE)
```

```{r, models}
UK <- Leeds %>% filter(Country == "UK")
PT <- IST %>% filter(Country == "PT")

modUK <- cesModel( iGDP ~ iKservO.WwithRD + ihLest + iU + iYear, data = UK)
modPT <- cesModel( iGDP ~ iKservS.L + ihLest + iUMP + iYear, data = PT)
```

```{r}
UK2 <- 
  modUK$data %>%
  mutate(
    iGDP = iGDP / tail(iGDP, 1),
    iKservO.WwithRD = iKservO.WwithRD / tail(iKservO.WwithRD, 1),
    ihLest = ihLest / tail(ihLest, 1),
    iU = iU / tail(iU, 1)
  )

PT2 <- 
  modPT$data %>%
  mutate(
    iGDP = iGDP / tail(iGDP, 1),
    iKservS.L = iKservS.L / tail(iKservS.L, 1),
    ihLest = ihLest / tail(ihLest, 1),
    iUMP = iUMP / tail(iUMP, 1)
  )

modUK2 <- cesModel( iGDP ~ iKservO.WwithRD + ihLest + iU + iYear, data = UK2)
modPT2 <- cesModel( iGDP ~ iKservS.L + ihLest + iUMP + iYear, data = PT2)
```

```{r, plotfun, cache=FALSE} 
model2OE <- function( model ) {
  data <- fortify(model)
  if (! "Country" %in% names(data)) data$Country <- "  "
  data <- data %>% group_by(Country) %>% mutate( start = iYear == min(iYear))
  
  ggplot() +
    tri_theme() +
    tri_grid() +
    tri_labels(labels = c("alpha[k]", "alpha[l]", "alpha[e]"), parse = TRUE) +
    geom_tripath( 
      data = data, aes(x=oe1, y=oe2, z=oe3),
      alpha=0.6, colour = "black") +
    geom_tripoint( 
      data = data, aes(x=oe1, y=oe2, z=oe3, colour = Year), 
      alpha=0.6) +
    scale_colour_gradient(low = scales::muted("navy"),  high = "green") +
    facet_grid( ~ Country)
}
```

## Trajectories of Ouput Elasticities (2 examples)
```{r, plots, cache = FALSE}
bigData <-
  bind_rows(
    fortify(modUK) %>% mutate(Country = "UK", reindex = "first"),
    fortify(modPT) %>% mutate(Country = "PT", reindex = "first"),
    fortify(modUK2) %>% mutate(Country = "UK", reindex = "last"),
    fortify(modPT2) %>% mutate(Country = "PT", reindex = "last")
  )
model2OE(bigData) + facet_grid(reindex ~ Country)
```   

 