---
title: "Investigation of results"
author: "MK Heun"
date: "June 29, 2015"
output: pdf_document
---

```{r setup, echo=FALSE, include=FALSE}
require(EconModels)
require(EconData)
require(dplyr)
require(ggplot2)
require(xtable)
```

```{r models}
# Set working directory to the location of these data files relative to the location of this file.
setwd("../..")
fileName <- "ESEE2015Models.rds"
fileNameCST <- "EESE2015ModelsCST.rds"
# load from the file on disk
models <- readRDS(fileName)
modelsCST <- readRDS(fileNameCST)
```

```{r investigation}
mod <- models$PT$adjusted$withE$CES$ekl
naturalCoef(mod)
summary(mod)

sum(resid(mod)^2)

attempts <- attr(mod, "model.attempts")

df <- lapply(attempts, function(attempt){
  coeffs <- naturalCoef(attempt)
  sse <- sum(resid(attempt)^2)
  coeffs$sse <- sse
  return(as.data.frame(coeffs))
}) %>% do.call(plyr::rbind.fill, .)
```


```{r all_model_attempts, tidy=FALSE, comment=NA, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
print(xtable(df), type = "latex", include.rownames = T, floating=FALSE)
```

```{r sse, tidy=FALSE, comment=NA, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
print(xtable(select(df, sse), digits = 6), type = "latex", include.rownames = T, floating=FALSE)
```
