---
title: "CES function"
output: pdf_document
---


\large



\[
C = \theta  e^{\lambda  t} 
  \left(
     \delta \left(\delta _1 x_1^{-\rho _1} +
     \left(1-\delta _1\right) x_2^{-\rho _1}\right){}^{\frac{\rho }{\rho _1}} +
     (1-\delta ) x_3^{-\rho } 
     \right){}^{-1/\rho }
\]
   
Let 
\[
Q = \delta_1  x_1^{-\rho_1} + (1-\delta_1) x_2^{-\rho_1} \;,
\]
and let 
\[
R = Q^{\rho / \rho_1 -1} \;.
\]

Note that
\[
\delta Q = (\alpha_1 + \alpha_2) Q =  \alpha_1  x_1^{-\rho_1} + \alpha_2 x_2^{-\rho_1} \;.
\]

We can use this to simplify the expressions for the output elasticities as follows:

\begin{align*}
\frac{
\frac{\partial C}{\partial x_1} }{
\frac{C}{x_1}
}
& = \frac{\delta  \delta _1 x_1^{-\rho _1} \left(\delta _1 x_1^{-\rho _1}-\left(\delta
   _1-1\right) x_2^{-\rho _1}\right){}^{\frac{\rho }{\rho _1}-1}
   }{
   \delta  \left(\delta _1
   x_1^{-\rho _1}-\left(\delta _1-1\right) x_2^{-\rho _1}\right){}^{\frac{\rho }{\rho
   _1}}-(\delta -1) x_3^{-\rho }}
   \\
& = \frac{\alpha_1 x_1^{-\rho _1} R
   }{
   (\alpha_1 + \alpha_2) Q R + \alpha_3 x_3 ^{-\rho}}
   \\
& = \frac{\alpha_1 x_1^{-\rho _1} R
   }{
   (\alpha_1 x_1^{-\rho_1} + \alpha_2 x_2^{-\rho_1}) R + \alpha_3 x_3 ^{-\rho}}
\\[6mm]
\frac{
\frac{\partial C}{\partial x_2} }{
\frac{C}{x_2}
}
& =
\frac{\delta  \left(1-\delta _1\right) x_2^{-\rho _1}
   \left(\delta _1 x_1^{-\rho _1}-\left(\delta _1-1\right) x_2^{-\rho
   _1}\right){}^{\frac{\rho }{\rho _1}-1}}{\delta  \left(\delta _1 x_1^{-\rho
   _1}-\left(\delta _1-1\right) x_2^{-\rho _1}\right){}^{\frac{\rho }{\rho _1}}-(\delta
   -1) x_3^{-\rho }}
\\
& = \frac{\alpha_2 x_2^{-\rho _1} R
   }{
   (\alpha_1 + \alpha_2) Q R + \alpha_3 x_3 ^{-\rho}}
   \\
& = \frac{\alpha_1 x_1^{-\rho _1} R
   }{
   (\alpha_1 x_1^{-\rho_1} + \alpha_2 x_2^{-\rho_1}) R + \alpha_3 x_3 ^{-\rho}}
\\[6mm]
\frac{
\frac{\partial C}{\partial x_3} }{
\frac{C}{x_3}
}
& =  \frac{1-\delta}{\delta  x_3^{\rho } 
   \left(\delta _1 x_1^{-\rho _1} - \left(\delta _1-1\right) 
                   x_2^{-\rho _1} \right)^{\frac{\rho }{\rho _1}} 
   + (1 -\delta)
   }
\\
& = \frac{\alpha_3 x_3^{-\rho} 
   }{
   (\alpha_1 + \alpha_2) Q R + \alpha_3 x_3 ^{-\rho}}
   \\
& = \frac{\alpha_3 x_3^{\rho} 
   }{
   (\alpha_1 x_1^{-\rho_1} + \alpha_2 x_2^{-\rho_1}) R + \alpha_3 x_3 ^{-\rho}}
\end{align*}

From this we see that the output elasticities sum to 1 and are in the ratio

\[
\alpha_1 x_1^{-\rho_1} R : \alpha_2 x_2^{-\rho_1} R : \alpha_3 x_3 ^{-\rho}
\]

## Special case

When $x_1 = x_2 = x_3$, we get 
$Q = 1$ and $R = 1$, so the  output elasticities are given by

\[
\frac{ \alpha_i}{\alpha_1 + \alpha_2 + \alpha_3}
\]



## Limiting Cases
Need to deal with limiting cases. When $\rho \to \infty$ or $\rho_1 \to \infty$.



